### ISSUE TITLE
Dynamically load OSM data that doesn't exist in local table

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#101]
Since we're now using OSM as the geographic gazetteer and its a bit burdensome to efficiently load all of OSM into a database (especially since all we want is a subset) we're just loading one country at a time based upon where the research is happening. This poses a challenge when we need to describe organizations or events that are centered outside those countries. Let's find a way to load particular features on demand so that when a researcher wants to use them, they will be available. One way of doing this would be to design a fallback mechanism that only fetches features from a web based OSM API when we can't find them in them in the local table.

**Comment by tlongers** [comment]
Resolved differently in Sept 2018 with new location app. Closing.
