### ISSUE TITLE
Importer - Areas, OrganizationMembership

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#102]
@evz It looks like data related to an Organization's Area and OrganizationMembership didn't make it into the CMS from the importer...

**Comment by evz** [comment]
@tonysecurityforcemonitor How did you confirm this (just so I can debug where it might be going wrong)?

**Comment by tonysecurityforcemonitor** [comment]
Hey @evz I checked out the entry for the 1 Mechanised Division in the staging site CMS --- there don't seem to be any entries for anything other than attributes for name, parent org and site. I tried to edit the entry to add area but wasn't able to

**Comment by evz** [comment]
So, the reason the areas weren't showing on that page is because I forgot to put a map in there :flushed: 

It looks like there are some organizations that have members so, for instance, https://sfm.datamade.us/en/organization/detail/81/

Are there some organizations that you expect to have members that don't? If I can narrow it down, it'll make it easier to debug the importer.

**Comment by tonysecurityforcemonitor** [comment]
@evz re: Area(s) - ah ok! ;)

re: OrganizationMembership - Sorry to clarify I meant all the attribute's attached to an Organization's OrganizationMembership (OrganizationMembership:member_id, OrganizationMembership:organization_id, OrganizationMembership:date_first_cited, OrganizationMembership:date_last_cited) not PersonMembership. So it should show that the organization 1 Mechanised Division was a member of Operation BOYANA for instance.


In the current Master Import Sheet (which I'll leave untouched at this point) these are the organizations which should have at least one OrganizationMembership:

1 Battalion
1 Brigade
1 Mechanised Division
103 Battalion
146 Battalion
174 Battalion
19 Battalion
192 Motorised Battalion
195 Battalion
2 Amphibious Brigade
2 Battalion
2 Mechanised Division
21 Armoured Brigade
213 Battalion
22 Armoured Brigade
22 Battalion
222 Battalion
223 Armoured Battalion
23 Armoured Brigade
234 Special Operations Battalion
241 Recce Battalion
26 Battalion
28 Task Force Brigade
29 Battalion
3 Armoured Division
3 Battalion
3 Motorized Brigade
301 Artillery Regiment
31 Field Artillery Brigade
32 Artillery Brigade
322 Artillery Regiment
323 Artillery Regiment
33 Artillery Brigade
35 Artillery Brigade
4 Mechanized Brigade
7 Division
72 Special Forces Battalion
73 Battalion
75 Strike Group
81 Battalion
81 Division
82 Mechanised Battalion
9 Brigade
93 Battalion
Edo State Police Command
Police Mobile Force Squadron 27
Police Mobile Force Squadron 4
Police Mobile Force Squadron 44
Police Mobile Force Squadron 45

**Comment by evz** [comment]
@tonysecurityforcemonitor I think I fixed this. Are there still organizations missing memberships?

**Comment by tonysecurityforcemonitor** [comment]
@evz Thanks for flagging - yep this seems to be working
