### ISSUE TITLE
Exporting csv data?

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#108]
@evz picking up on this --- is it possible to have a function for a download of the Monitor's data in csv format?

Thinking through implementation issues, we might host a download link on the webpage of the Security Force Monitor, rather than through the application itself.

**Comment by evz** [comment]
Ha! I totally just opened an issue for this over in the UI repo: https://github.com/security-force-monitor/sfm-ui/issues/44

**Comment by tonysecurityforcemonitor** [comment]
:) - I'll go there
