### ISSUE TITLE
Source parsing question

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#109]
@evz  Have a look [here](http://ffctn.com/clients/on/sfm/M19/#country/ng/o/d68b415c-c1de-4a48-aa8b-8c90daca2d3a!date=2014-01-01&focus=map). Rather than display a link to a source, the full citation is displayed. Is this by design, or a parsing glitch somewhere?

![image](https://cloud.githubusercontent.com/assets/2115933/22823900/aab39462-ef7d-11e6-9900-2641aa785335.png)

(initially tagged Derek, sorry!)

**Comment by evz** [comment]
In some cases, I was unable to parse out the individual components of the citation from the spreadsheet. There were many ways those citations were entered so I chose the path away from the regular expression road to madness. Since everything needs a source, I didn't want to have the import fail in those cases so I just put the whole citation into the title field figuring that we could loop back around and parse those out (either through the Django admin or by machine) at a later point. A lot of them can probably be picked up by using a probabilistic parser (and it just so happens DataMade maintains a thing for making those: https://github.com/datamade/parserator).

**Comment by tonysecurityforcemonitor** [comment]
@tlongers @evz Eventually I'd prefer the full citation to be displayed anyway (unless there is a reason not to?) I like the idea of the user being able to see the publication, date, and to choose the IA url in the very likely event the original url is [404'd](http://www.homestarrunner.com/404error.html)

**Comment by tlongers** [comment]
Hmm. Full text citations make sense in a journal article, but not a web application. I like the current approach of a link, but would include the source and date in the ```<a>``` label. Following that, I'd have the Internet Archive link bracketed) e.g.

>División Territorial Militar – II Región Militar, Mexicali, B.C.. Secretaría de la Defensa Nacional (Mexico). Date crawled: 8 September 2005. http://www.sedena.gob.mx/ejercito/comandancias/imagenes/IIRM.gif Internet Archive Link: https://web.archive.org/web/20050908204237/http://www.sedena.gob.mx/ejercito/comandancias/imagenes/IIRM.gif 

Becomes...

[División Territorial Militar – II Región Militar, Mexicali, B.C.. Secretaría de la Defensa Nacional (Mexico). Date crawled: 8 September 2005](http://www.sedena.gob.mx/ejercito/comandancias/imagenes/IIRM.gif) ([Archived copy]( https://web.archive.org/web/20050908204237/http://www.sedena.gob.mx/ejercito/comandancias/imagenes/IIRM.gif))

**Comment by tlongers** [comment]
@evz "we could loop back around and parse those out" - agreed; it's probably a few hours work for us to tidy up any oddities if they can be detected and spat out in a form that can then be reimported easily.  There will be weirdness in the citation set how careful we are though. Ultimately, this is an importation problem, no one we have for data directly entered through the CMS.

**Comment by tlongers** [comment]
@jeancochrane Is the situation with source parsing still the same at the current time?

**Comment by jeancochrane** [comment]
Looks like it is. We have 433 sources total, and 125 are missing a URL (which I take to be an indication that the parsing failed.) 

Let's add this to the Milestone, and later today I can get you 1) a list of locations of malformed sources and 2) a suggested format that I'm confident we can parse?

**Comment by tlongers** [comment]
Ok, thanks for letting us know.  We have a  proposal to move all our sources to a standard based on Dublin Core Metadata Standard (DCMI) - that'd give them more structure and remove the need for parsing. We *could* crunch the sources into this format BUT the challenge then be how to bring them into the import process. Think this is something we can solve now?

**Comment by jeancochrane** [comment]
Mind giving me an example of your proposed new system? If the DCMI is indeed structured enough to remove the need for parsing, bringing it into the import process could be a simple change.

**Comment by tlongers** [comment]
Here's the basics of the direction we want to go in, but it needs some more work:

- `title` ([documentation](http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#terms-title)) - the title of the resources
- `creator` ([documentation](http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#terms-creator))  - used to record named authors 
- `publisher` ([documentation](http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#terms-publisher)) - used to record the distributing entity, like the newspaper or journal
- `created` ([documentation](http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#terms-created)) - the date of creation of the resource
- `issued`([documentation](http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#terms-issued)) - the date of publication of the resource
- `format` ([documentation](http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-format)) - "The physical or digital manifestation of the resource", including the original url and its archived versions (possibly this includes fields for `source url`, `internet archive url` and `internal archive url` (when we have built this ))
- `language`([documentation](http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#terms-language))
- `country`([documentation](http://dublincore.org/usage/terms/history/#ISO3166-004))

What we would need is:
- a complete list of all sources mentioned in the dataset
- a way to relate the cleaned-up version back to the dataset (and that made sense to the importer)

**Comment by tlongers** [comment]
Pausing this for now. We don't have time this run. Closing and will re-open for Chunk 2.
