### ISSUE TITLE
Dumb question - does the importer aggregate for a specific entity?

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#110]
@evz Dumb question, which I'll do my best to outline...

Does the import aggregate all information that if finds associated with a specific entity? 

For example, take the below as a source:

Person, Parent,Hair Colour, Spirit Animal
Luke,Darth,Green,Pony
Luke,NULL,Blue,Chaffinch
Luke,NULL,NULL,Komodo

Would the ultimate CMS entry for Luke look like so:

Person: Luke
Parent: Darth
Hair colour: Green, Blue
Spirit Animal(s): Pony, Chaffinch, Komodo

I ask because in our Master Spreadsheet we are about to have 1600 new rows covering 40+ organisations where the only difference between rows is the Area of Operations and date coverage. Do I have to place Parent Organisation information in each of those rows, or can it be covered once  in a separate row and the importer will pick it up?

**Comment by evz** [comment]
It should aggregate as in your example where we expect more than one value. If we don't, it'll update the value.

**Comment by tlongers** [comment]
So if an ```Organization``` has an existing value for ```OrganizationOrganization:parent_id``` and a subsequent row is left empty, after import the value be empty?

**Comment by evz** [comment]
Oh, except in that case. I guess by "value" I mean not null.

**Comment by tlongers** [comment]
Thanks Eric!
