### ISSUE TITLE
Re-run Import

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#113]
Hi @evz can you re-run the import? Did some cleaning of Mexico data that would be good to test out in the UI. Thanks!

**Comment by evz** [comment]
Are there any events that need refreshing? Only reason why I ask is there is a shortcut I can take if we don't need to refresh events.

**Comment by tonysecurityforcemonitor** [comment]
I updated one event but's not that important... we can check that at a
later date.

**Comment by tonysecurityforcemonitor** [comment]
@evz - no need to refresh the events right now - I'm just interested in testing the organizations and people. Will do a larger update of events this week.

**Comment by evz** [comment]
Everything except for the events should be updated now.

**Comment by tonysecurityforcemonitor** [comment]
Hi @evz sorry - when was the import run? I ask because there are some organizations in Mexico with the classification - Policía Ministerial del Estado - that aren't showing up... it may be because I added them over the weekend...

**Comment by evz** [comment]
@tonysecurityforcemonitor Yeah, I ran it on Friday. I just kicked it off again and will let you know when it's done.

**Comment by evz** [comment]
@tonysecurityforcemonitor The newer organizations look like they are showing up now.

**Comment by tonysecurityforcemonitor** [comment]
Yep it's working quite well - thanks @evz !
