### ISSUE TITLE
Future dates should make the importer fail

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#115]
@evz Where any date is beyond the current date, the importer should fail it - this'll help us pick up any dumb errors our side (for example, we goofed here - see the end date on parent relationship [here](http://ffctn.com/clients/on/sfm/M27/#country/mx/o/44d09483-9fbe-4403-aab9-e7956cfbdffd!date=2014-05-25&focus=map))

**Comment by tlongers** [comment]
Bumping. Is this implemented?

**Comment by jeancochrane** [comment]
Not to my knowledge, but it's a quick fix.
