### ISSUE TITLE
API error - events

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#116]
@evz  Ignore if you're working something and it'll self-fix but I got and API error here just now:
https://sfm.datamade.us/api/events/312ad4d0-1763-429f-9608-1feec76c5172/

**Comment by evz** [comment]
Urgh. This is an error that I have not been able to put my finger on or reliably reproduce. It has to do with comparing the overlaps between when an event occurred and what organizations occupied the 35km radius around that event at that time. I take another dive into it.

**Comment by evz** [comment]
@tonysecurityforcemonitor @tlongers OK, I think I found the culprit. Somehow my importer script is interpreting the dates in the spreadsheet in rows 800 & 801, column AX incorrectly which is causing a nonsensical date range for when that unit occupied that area of operations. One "easy" fix would be to make those dates easier for a machine to read by removing the apostrophe from the beginning and formatting them like MM/DD/YYYY or something. I can also look at what's actually happening there with the importer.

**Comment by tonysecurityforcemonitor** [comment]
@evz - ah this is related to #114 - we use the apostrophe because otherwise Google Sheets normalizes February 1999 to 2/1/1999....

**Comment by evz** [comment]
@tonysecurityforcemonitor Ah! Good to know. I'll adjust the importer to strip out the apostrophe and then hopefully this will not break anymore.

**Comment by evz** [comment]
@tonysecurityforcemonitor Is there a list of date formats that are being used? If I tried these would I cover everything?

* `MMMM YYYY` (ex May 2013)
* `YYYY` (ex 2013)
* `MM/DD/YY` (ex 05/04/2013 or 5/4/2013)

**Comment by tonysecurityforcemonitor** [comment]
@evz you've just made the list ;)

Yes those are all of the date formats being used. I just went through to corrected some outstanding errors in the Master Import (Google will reformat any YYYY into an equation that generally goes XX/XX/1905 when you copy and paste between Google Sheets... oh the fun!)

**Comment by evz** [comment]
@tonysecurityforcemonitor Hopefully this will be a non-issue soon when we get up on the CMS.

**Comment by tlongers** [comment]
Not had date issues for some time. Closing.
