### ISSUE TITLE
Nigeria - Person with no start or end date for command

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#117]
Likely one for @tonysecurityforcemonitor 

http://ffctn.com/clients/on/sfm/M27/#country/ng/p/3cf94f07-247e-4e1a-8c92-d24ce820b132!date=2012-12-06&focus=map&overlay=person-dossier

Command of ```Ike Nwachukwu``` over ```81 Batallion``` displayed with ```N/A``` for both Start Date and End Date. 

Incomplete date entry or deliberate? Here's the [source data](https://docs.google.com/spreadsheets/d/16cRBkrnXE5iGm8JXD7LSqbeFOg_anhVp2YAzYTRYDgU/edit#gid=394650791&range=200:200).

I can't check the sources as they are paywalled.

**Comment by tonysecurityforcemonitor** [comment]
@tlongers deliberate - the article gives a run down of their history but isn't clear when exactly they served in that role. My preference in cases like this is to have it be clear to the user that at some point in time this person was affiliated with this organization - but we could probably have that be more clearly communicated than is currently

**Comment by tlongers** [comment]
Resolved. Closing.
