### ISSUE TITLE
HTTPS on front.~

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#128]
HTTPS is broken on https://front.securityforcemonitor.org/ :(

**Comment by jeancochrane** [comment]
Thanks for flagging this @tlongers! @evz is taking a look now.

**Comment by jeancochrane** [comment]
HTTPS is back up on https://front.securityforcemonitor.org/. We're upgrading the cert renewal infrastructure on that server to make sure this doesn't happen again.
