### ISSUE TITLE
OSM object types and import script

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#130]
@evz In our data, we include fields for the object's name, ID number but not its content type.  An OSM ID number can be a `node`, `way` and `relation` simultaneously. How does the import script determine which is the correct one? 

For example, take the ID number `273587922`: `node/273587922` is a unique `node` and `way/273587922` is a unique `way`. However with just the ID number `273587922` there is not a way to tell whether it is the `node` or `way` that we need. In this example, we want `node/273587922` which is right in the centre of [the city of Chihuahau](http://www.openstreetmap.org/node/273587922) . But `way/273587922` also exists in OSM (a [building in St Gallenkappel, Switzerland](http://www.openstreetmap.org/way/273587922#map=19/47.24586/8.96171)).  

Does the importer use the additional `name` value we include to pick between the content types?

**Comment by evz** [comment]
I think there are a couple ways we are avoiding this, neither of which is probably 100% foolproof. Firstly, I'm not importing all OSM data for the entire planet, just those countries which are covered by the research. Secondly, I'm only importing things that are either points or boundaries (so, nodes and relations) and from those only those that have a name (you'd be surprised how many things this eliminates). 

One simple way of making sure that these things are kept distinct would be to only consider something unique if the OSM ID and the feature type were unique (so ID + node, or ID + relation, etc). That's pretty simple to implement at the database level and would pretty much work with everything else we already have implemented. I'll open an issue to make sure we do that.

**Comment by tlongers** [comment]
Thanks @evz . 

>only consider something unique if the OSM ID and the feature type were unique (so ID + node, or ID + relation, etc). 

Thinking ahead for this month, we will have a few more imports to run before switching over to the CMS for data capture and management. Your solution will  catch IDs that have node or relation, and in some cases we'll have choose the correct entry by hand. 

After that, any new data that is entered through the CMS should capture the OSM feature type as a separate value. I think it worth capturing this so when people download data from the CMS it's accessible to them. I can see some use cases for having it as a value, such as doing geocoding (e.g. node to lat/lon) using Nominatim and the OSM API.

**Comment by tlongers** [comment]
Think this issue is now superceded and de facto resolved with the new (Sept 2018) Location app. Closing.
