### ISSUE TITLE
Search improvements

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#132]
## Search page

- [x] Wire up facets to work as filters
- [x] Truncate long facet names
- [x] Show the number of results on each search
- [x] Add fallback for "No results found"
- [x] Add "Clear all filters" button
- [x] Add date filters
- [x] Add date facets
- [ ] Add "Country" filters
- [x] Update the table metadata to match the mockup
- [ ] Wire up column sorting
- [x] Truncate violation types
- [X] ~Make sure clearable filters all have Xs on the same side~ (not really possible with select2; we should think about how much we care to edit it)

## Home page

- [x] Add option to immediately filter on entity type for the global search

**Comment by tlongers** [comment]
Seems useful to suggest these: 
- applied filters should persist until cleared, so the user can update the search term without the need to re-do the filter again (is this inherent in the "Clear all filters" wiring?) 
- the tooltip that appears over truncated facet labels should appear instantly (currently 2 sec delay)
- for any given facet, is it possible we select a couple of obviously massive facets  to sit at the top (per the Topic facet on Councilmatic)?

![search_results_for__test_test__-_chicago_councilmatic](https://user-images.githubusercontent.com/2115933/28729651-19fa8cd8-73c5-11e7-9c95-748c64ea9557.png)

**Comment by tlongers** [comment]
Truncated facet labels get a little difficult to see  in cases where the facets have similar language in the first words, like with how we categorise abuses:

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/28730218-044e9b8e-73c7-11e7-819c-39bc3e806cc9.png)

Short of text-wrapping and making the text smaller, how to make this more usable?

**Comment by tlongers** [comment]
Also need a way to clear the location filter (though I guess this may change its form, so ignore if that's the case)

**Comment by jeancochrane** [comment]
I added all of the easy changes listed here in [f5cc160](https://github.com/security-force-monitor/sfm-cms/commit/f5cc160a9f06ee92e87c5aa7a242dbd0c5758788), including:

- persisting facets
- clearable location filter
- faster-loading tooltips

To your other two questions:

> for any given facet, is it possible we select a couple of obviously massive facets to sit at the top (per the Topic facet on Councilmatic)?

Definitely! This is an easy change - it just requires knowing ahead of time which facets you're interested in calling out. If you get me a list of these, I can code it in quickly. (Or, if you imagine that you'll want to curate that list and edit it as your data changes, we could think about making it editable by administrators in the admin interface.)

> Short of text-wrapping and making the text smaller, how to make [truncated facet labels with similar names] more usable?

We can write up some template filters to handle these facets differently. Violation type strikes me as the easiest to implement, since there's a nice and limited set of possible values; any other facets that seem to be good candidates for this kind of custom treatment?

**Comment by tlongers** [comment]
>persisting facets

Works as expected.

>clearable location filter

This is good. It alerts me to a UX consistency issue - the cross denoting the clear option should be on the same side in all chips. Currently, there's a mix of left and right positioning.

> obviously massive facets

OK, good to know that's a quick fix. I'll do a quick consult before asking for more action on this.

>truncated facet labels with similar names

You're right. For now I can only think of Violation type, so sorting that out would be great. Depending on the shape that location filter takes, it may be necessary there too.

**Comment by tlongers** [comment]
Don't see it listed so adding in a note to add in controls for results page pagination + number of search results to show.

**Comment by jeancochrane** [comment]
I think this issue should be superceded by the milestone, do you agree @tlongers?

**Comment by tlongers** [comment]
Yup.
