### ISSUE TITLE
500 error on staging site

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#133]
```en/search/?entity_type=Person```

gives me:

```Server Error (500)```

**Comment by jeancochrane** [comment]
Thanks for flagging this @tlongers! I'll take a look this morning. Are you getting a 500 error anywhere else on the site, or just at this endpoint?

**Comment by tlongers** [comment]
Thanks for picking this up so quick Jean.

500 error at:

en/search/?entity_type=Person
en/search/?entity_type=Organization
en/search/?entity_type=Violation
en/search/?q=&entity_type=Person&entity_type=Organization&entity_type=Violation

No issues at:

en/countries/
en/organization/detail/5/ (and direct links to record details)

**Comment by jeancochrane** [comment]
OK, it should be back up now. Looks like we're not restarting the app properly in some of our deploy scripts. The site's back up, but I'll leave this open until I've confirmed that the deploy pipeline is working smoothly again.

**Comment by jeancochrane** [comment]
Closed by [c1885d4](https://github.com/security-force-monitor/sfm-cms/commit/c1885d403ce8b8e3262fdf2e72254ab62fd9592a).
