### ISSUE TITLE
No results found page - what should go on it?

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#134]
When no results are found, what options are there for the user?

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/28723673-65c00bae-73af-11e7-8122-23b34be472be.png)

The "Think we're missing something? Let us know!" is useful but can't be the only thing we offer.

Some options:
- include some tips about how to search
- link out to a help page on searching
- display some near miss matches, or mis-spellings (@evz what does solr provide us with here?)

**Comment by jeancochrane** [comment]
All of those sound great! I don't have much to add yet, but solr's [Suggester](https://lucene.apache.org/solr/guide/6_6/suggester.html#Suggester-ExampleUsages) feature seems like a promising lead to thinking through point 3.

**Comment by tlongers** [comment]
Picking up on this. Is the ```suggester``` functionality enabled? Would be good for it to detect near misses and suggest a search e.g. ```"johnn"``` turns up no results.

```/search/?q=johnn&entity_type=Person&entity_type=Organization&entity_type=Violation&radius=1&start_date=&end_date=```

**Comment by jeancochrane** [comment]
Basic suggestions are in as of https://github.com/security-force-monitor/sfm-cms/commit/deb73f37451368f107141213ae3fad595661a992:

![suggester](https://user-images.githubusercontent.com/14170650/31154597-d7689f62-a86d-11e7-83f9-2eb202b9dd6a.png)

I think there's still some work to be done fine-tuning it (e.g. `johnn` still returns no results, and doesn't find any suggestions) so I'm going to leave this open for now. Time to spend some quality time with the docs.

**Comment by tlongers** [comment]
Nice! This will probably reward us more - and be easier to tweak - once the full datasets are imported.
