### ISSUE TITLE
Improve data-entry wizard

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#135]
## General

- [x] Add "Add new source" to the navbar
- [x] Add icons for "Continue," "Go back," and "Skip"
- [x] Make all type-ahead boxes clearable
- [x] Use icons in titles
- [x] Double-check back/skip/next buttons for all pages
- [ ] Simple logic checks
- [x] Pages should save data when you switch back and forth between them
- [x] Figure out where confidence values are stored in the DB, and add those as inputs to the UI (replace `/set-confidence/` endpoint)
- [X] Check form validation (since oftentimes we use EJS for the initial form and Django formsets for validation)

## Step bar

- [x] Step bar should highlight the current step
- [x] Box should not extend past the final step

## 3. People

- [x] Layout of the form fields should match the layout of the rest of the pages
- [x] Make "Organizations" field a select2 box (to match the rest of the fields)
- [x] "Remove person" button should be red, have a better icon

## 4. Relations (Organization memberships)

- [x] The title of this page and its wizard step need to have the same name
- [x] How do we add new roles/ranks?

## 5. Geographies

This page needs some serious love. See #136.

## 6. Events

- [x] "Continue" button should be "Finish"
- [x] "Add violation" button should be "Add event" (to match title)
- [x] "Violation type" needs to return distinct values, right now it's full of dupes (also, how do we add new ones?)

## End

- [x] Flash a message to the user when the data has been saved
- [ ] Update the search index and materialized views after data has been saved

**Comment by jeancochrane** [comment]
Just about done here. The last step is adding simple logic checks, and figuring out when/how to update the search index.

**Comment by tlongers** [comment]
Refers to earlier version of data creation tool. Closing.
