### ISSUE TITLE
Redo "Geographies" data entry page

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#136]
[Detailed thoughts here.](https://github.com/security-force-monitor/sfm-cms/wiki/Data-legibility-and-interface-challenges#adding-geographical-information-to-a-record)

At minimum, we need:

- [x] A map that lets you browse nodes and relations, and search for places
- [x] A way to create multiple geographies at once (multiselect box?)
- [x] Field for the type of location
- [ ] Some indication about what an "area" and a "site" are, and how to distinguish them
- [ ] Confidence values
- [ ] Cookies integration that maintains form state across back/next buttons

Some nice things to have:

- [ ] ~A toggle that displays already-existing geographies~ Doesn't seem totally necessary?

**Comment by jeancochrane** [comment]
@reginafcompton has made awesome progress on this as of [1130125](https://github.com/security-force-monitor/sfm-cms/commit/11301255c2da8dfb00bfe28ff369838a6bfeaa72).

**Comment by tlongers** [comment]
Refers to older version of widget for adding geographies. Closing.
