### ISSUE TITLE
Write option to "refresh" search index

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#137]
Let's write a method to refresh the search index, as opposed to redoing it entirely. This will make it feasible to quickly update the search index each time a user adds new data (part of #135).

**Comment by jeancochrane** [comment]
We'll also want to either a) refresh materialized views or b) not build our index off of them, since views don't automatically get refreshed when new data is added to the DB.

**Comment by jeancochrane** [comment]
The first half of this is done as of [00c6072](https://github.com/security-force-monitor/sfm-cms/commit/00c60722e2bc38715d921b82d23df1e60487e146).

**Comment by jeancochrane** [comment]
I added this on to #196, so the form should refresh the search index when you finish the wizard now.

Unfortunately there's a delay of about 15-20 seconds while the server does all the processing it needs to do to refresh the index, and during that time the user's browser has to sit and wait. We can introduce task delaying to make this more friendly, but for now I wanted to get in a solution that would work as quickly as possible.

**Comment by tlongers** [comment]
I got the expected wait, then a timeout and a bad gateway message after hitting "finish" in the data creation wizard. I can see through the admin interface that the record I entered has been committed to the database (see ```~en/admin/person/personname/852/change/```) but it is not appearing in front-end search results.
