### ISSUE TITLE
Record view improvements

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#139]
### Immediate
- [x] Show chain of command - issue #162 
- [x] Show subordinates
- [ ] Show sources
### Long term
- [x] Make org charts
- [x] Figure out how to show changes over time

### Immediate
- [ ] Show sources
### Long term
- [x] Make org charts - issue #215
- [x] Figure out how to show changes over time (org charts, maps)

### Immediate
- [x] Add information to the header (Country? Perpetrators?)
- [x] Show more information in the "details" body
- [x] Write templatetag to hide long descriptions behind a JS "Read more"
- [ ] Add sources
- [ ] Add perpetrators

### Long term
- [ ] Come up with some kind of better UI for exploring changes

**Comment by tlongers** [comment]
@jeancochrane are you still working off this, or shall we close in favour of the Milestone?

**Comment by jeancochrane** [comment]
@tlongers let's work off of the Milestone.
