### ISSUE TITLE
Some dates need to be nonspecific.

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#14]
When users are entering dates, they should be allowed to enter just a year or just a month and a year. The fields that should validate this way are:
- [ ] Association_AssociationStartDate
- [ ] Association_AssociationEndDate
- [ ] Composition_CompositionStartDate
- [ ] Composition_CompositionEndDate
- [ ] Emplacement_EmplacementStartDate
- [ ] Emplacement_EmplacementEndDate
- [ ] MembershipPerson_MembershipPersonFirstCitedDate
- [ ] MembershipPerson_MembershipPersonLastCitedDate
- [ ] Organization_OrganizationFoundingDate
- [ ] Person_PersonDeathDate
- [ ] Violation_ViolationStartDate
- [ ] Violation_ViolationEndDate

**Comment by tlongers** [comment]
Implemented in https://github.com/security-force-monitor/sfm-cms/commit/af033910ec8ece955a911174868eedd0b608888e. Closing.
