### ISSUE TITLE
Defining default behaviour on date filters

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#140]
I'm liking the appearance of the date filters, but I can't unravel their default behaviour. The aim of the date filter is to enable the use to filter for records that exist at a point in time or during a range. Does the below make sense at describing the behaviour, and if so do we think that the UX is right to deliver it?

# Setting both filters

In the context of organizations, my expectation is that:

* Start Date corresponds to ```organization:date_first_cited```
* End Date corresponds to ```organization:date_last_cited```

The aim of setting a filter on both Start Date and End Date would be to include ```organizations``` where there is a complete  overlap between the dates set by the filter range and the last/first cited. I imagine it like this:

![date filters- how results are included or excluded](https://user-images.githubusercontent.com/2115933/28863600-8be5d934-7761-11e7-8577-51dbadd30d38.png)

It would include by default organizations where ```organization:date_last_cited``` is empty and the ```Organization:open_ended?``` is set to ```N``` or ```E```.

# Setting only a Start Date filter

Show organizations for which there is data on or after the Start Date.

This would exclude records where ```organization:date_last_cited```<= the Start Date, or where ```organization:date_first_cited``` <= the Start Date AND ```Organization:open_ended?``` is set to ```N``` or ```E```  (which @tonysecurityforcemonitor will shortly explain in his update to the data model)

![start date filter- how results are included or excluded](https://user-images.githubusercontent.com/2115933/28863889-83615940-7762-11e7-996a-54f1c4038468.png)

# Setting only an End Date filter

Shows organizations for which there is no data on or after the filter End Date. 

So this would exclude organizations where ```organization:last_cited``` <=  End Date or where ```organization:date_last_cited``` is empty and ```organization:open_ended?``` is ```N```

![end date filters- how results are included or excluded](https://user-images.githubusercontent.com/2115933/28864084-52b320a2-7763-11e7-8d53-53449d3b7437.png)

**Comment by jeancochrane** [comment]
This is really helpful, thanks @tlongers. I'm going to do some more work on dates today, so I'll have questions/comments as I move to implement this.

**Comment by tlongers** [comment]
Still some issues making this work. Starting from here:

```en/search/?q=&entity_type=Person&osm_id=501489268&radius=100&start_date=&end_date=```

Adding a general facet ```Start Date``` of ```2008-02-01``` should remove from the search listings the record for ```Bashiru Azeez```, the ```First citation``` date for whom is ```29th March 2004```, but it doesn't.

**Comment by tlongers** [comment]
This isn't quite working yet.

**Comment by jeancochrane** [comment]
https://github.com/security-force-monitor/sfm-cms/commit/e90035228ed116f05c3b881ad9d47cc6be3cc75a got this to a point where I was satisfied that it fulfilled @tlongers' charts. Feel free to open if you notice things still aren't working properly!
