### ISSUE TITLE
Facet on rank gives unexpected results

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#143]
@jeancochrane Not deluging you with feedback quite yet :) but this is pulling up unusual results for me:

~/en/search/?entity_type=Person&selected_facets=person_current_rank_ss_exact%3AGeneral%20de%20Brigada

I would expect a small results set, from Mexico and Military only, and not including ```Commissioner Of Police```.

**Comment by jeancochrane** [comment]
Good catch @tlongers! Looking into it now.

**Comment by jeancochrane** [comment]
This was the result of a boneheaded typo that was failing silently. Fixed in [50d7b72](https://github.com/security-force-monitor/sfm-cms/commit/50d7b72c7c79e50d27486ca3734985ce6648b40b).
