### ISSUE TITLE
What entry in a command history is the "First cited" facet operating on?

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#144]
On what value is the ```First cited``` facet operating on in a command history? I can see a difference between the behaviour of the facet and the way that results are displayed:

Facet person on rank = General de Brigada AND First cited in 2014:

~/en/search/?selected_facets=person_current_rank_s_exact:General%20de%20Brigada&entity_type=Person&selected_facets=person_first_cited_dt_exact%3A2014-01-01T00%3A00%3A00Z

This gives the below list, which give what I might expect, with one exception where a start date is ```10 October 2012```:

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/29330888-94438df6-81f2-11e7-8cdb-56cc17ea244b.png)

This record is the only one where the person does not have a single entry in their command history:

~/en/person/detail/598/

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/29331231-a47e9796-81f3-11e7-9f3a-9379f74df5af.png)

So I would think that the facet is operating on the top row in the command history. But  the search table displaying the earliest start date in time, which is drawn from the second row.

**Comment by jeancochrane** [comment]
Yup, your diagnosis seems right. Looks like for the search index we use the citation for the most recent membership (in this case, `2014-03-26`), but the value we display is the first citation we have for that person across all memberships (`2012-10-10`).

Which one is the right citation to use for the search index? First time ever cited, or first citation for the most recent membership?

**Comment by tlongers** [comment]
Whilst I ponder your question, I also spotted some other unexpected behaviour with this facet:

Searching with a ```First cited``` facet set to 2010:

~/en/search/?q=&entity_type=Person&selected_facets=person_first_cited_dt_exact%3A2010-01-01T00%3A00%3A00Z

Unexpected item in the search results:

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/29339483-51f9c378-8212-11e7-9d2f-176d18a9ba44.png)

This refers to ~/en/person/detail/579/ The data in the results table is a mishmash this person's command history:

 * The ```organization``` is incorrectly displayed as ```XII Región Militar``` when the only entry in the person's command history that stars in ```2010``` refers to ```I Región Militar```
*  The value in the ```First citation``` field is later than that displayed in the ```Last citation``` field.

It seems the facet has correctly found the entry in this person's command history that starts in 2010, but has incorrectly returned data from other entries.

**Comment by jeancochrane** [comment]
Something really weird is happening with person 579. You can see from the memberships table on the detail page that their command history is in ascending order instead of descending:

![image](https://user-images.githubusercontent.com/14170650/29370374-c5d619ba-826a-11e7-9866-e62c0b190f6c.png)

This is causing the weirdness that you identified.

A quick look at other personnel with multiple memberships (like 598 above) shows that this isn't universal, so it's not that we're simply querying in the wrong order. There must be something wrong with the query that fails on this particular edge case. I'm going to look into it this afternoon.

**Comment by tlongers** [comment]
This person has three postings at the same rank of ```General de Brigada``` -
 ```/en/person/detail/569/``` - including one starting in 2006. If this person appears in a list of search results faceted on ```General de Brigada``` shouldn't the ```First cited``` facet also show ```2006``` as an option.

Currently it does not:

```en/search/?selected_facets=person_current_rank_s_exact:General%20de%20Brigada&selected_facets=person_first_cited_dt_exact:2009-01-01T00:00:00Z&entity_type=Person&selected_facets=person_last_cited_dt_exact%3A2009-01-01T00%3A00%3A00Z```

**Comment by tlongers** [comment]
Not sure we ever completely debugged this. Keeping it alive for now.

**Comment by tlongers** [comment]
Got fixed at some point; closing.
