### ISSUE TITLE
More 500 errors 

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#145]
Searching on ```Felipe de Jesús Espitia Hernández``` throws ```Server Error (500)```:

~/en/search/?q=Felipe+de+Jes%C3%BAs+Espitia+Hern%C3%A1ndez&entity_type=Person&entity_type=Organization&entity_type=Violation&radius=1&start_date=&end_date=

**Comment by jeancochrane** [comment]
I think this is a UTF encoding error. Looking into it now.

**Comment by jeancochrane** [comment]
I think we may have fixed this issue. I don't see the error anymore. Are you still seeing it @tlongers?

**Comment by jeancochrane** [comment]
I'm not seeing this anymore, but feel free to reopen if you encounter it again!
