### ISSUE TITLE
Make sure to get country names from the Country object

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#147]
In a few places I retrieve it with a custom helper function. This is redundant and dangerous; refactor to use the Country model instead.

**Comment by tlongers** [comment]
@evz This still an issue? Or close?

**Comment by beamalsky** [comment]
The location app, as it's currently put together, attaches a country code to every location as it's created. @evz should confirm but I think this can be closed.

**Comment by tlongers** [comment]
No longer an issue.
