### ISSUE TITLE
Internationalize the site

### ISSUE THREAD

**Issue by reginafcompton** [security-force-monitor/sfm-cms#148]
This entails a few steps:

(1) Adding translation tags, as specified here: https://docs.djangoproject.com/en/1.11/topics/i18n/translation/

(2) Determining process for using django-rosetta: https://github.com/mbi/django-rosetta

**Comment by reginafcompton** [comment]
Notes:

* the form auto-detects the language (e.g., with the site in French, the form creates models instances with a "lang" of "fr") @evz - it seems to me that we want to have users select the language of their entry, rather than assuming alignment between the browser lang and the data input.

**Comment by reginafcompton** [comment]
Remaining TODOs: 
* ensure that the form content (e.g., error messages) have translation wrappers
* do all model fields have translation wrappers?

**Comment by jeancochrane** [comment]
Another thing to think about is [translator comments](https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#comments-for-translators). How does the Rosetta interface look? We may want to tag ambiguous elements to give SFM translators a hint of how words are used.

RE: README -- down at the bottom sounds fine to me. The README needs some love in general, and I imagine we'll do an overhaul once the product goes public, so no need to stress too much about it yet.

**Comment by reginafcompton** [comment]
RE: Translator comments

I added some clarifying comments, but I have a few questions... @jeancochrane could you tell me about the following variables?

Object sources – sfm_pc/utils.py:500
Real context? – when creating or editing a membership person (e.g., templates/membershipperson/edit.html:89)
Confidence – templates/modals/source.html:9
Geoname name (and ID)– templates/site/search.html:67

**Comment by jeancochrane** [comment]
@evz I'm not sure what "Object sources" and "Real context" are. Any ideas?
