### ISSUE TITLE
Violation form needs to ensure dates aren't null

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#149]
Regina was having trouble making the search index because Postgres was mad about null date types. Let's figure out if dates can be null; if they can, then we need to adjust the query. Otherwise, we should enforce form validation.

**Comment by tonysecurityforcemonitor** [comment]
@jeancochrane - violation dates should not be null - (are there null dates in the dataset - we should clean if there are!)

**Comment by jeancochrane** [comment]
Great to know @tonysecurityforcemonitor! It came from a few dummy violations that I had made in the process of testing the data entry wizard, everything is fine on your end. This means the violation form is not validating correctly.

**Comment by tonysecurityforcemonitor** [comment]
Ah ok @jeancochrane - thanks!
