### ISSUE TITLE
How should we define an area?

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#15]
The way things are currently setup, there's really no way to define a new boundary for an area. Do we expect that users will draw the boundaries on a map or do we want to have some kind of gazetteer that users can pick from? Or both?

**Comment by tonysecurityforcemonitor** [comment]
> The way things are currently setup, there's really no way to define a new boundary for an area. Do we expect that users will draw the boundaries on a map or do we want to have some kind of gazetteer that users can pick from? Or both?

@evz We are using http://www.geonames.org/ as our gazetteer - I haven't yet figured out how to get the shapefiles from their data though it appears there is a way. All that being said it would be good to be able to draw on a map in the instance that geonames doesn't have corresponding data. However - drawing on a map is something I have to think about on the research methodology side of things as it has quite a few implications for research.

**Comment by tonysecurityforcemonitor** [comment]
> We are using http://www.geonames.org/ as our gazetteer

@evz We follow geonames feature class - http://www.geonames.org/export/codes.html - meaning all areas are pulled from the "A country, state, region,..." feature class. Almost all areas are ADM1 or ADM2. There are a few cases where ADM1H or ADM2H may come into play.

**Comment by evz** [comment]
@tonysecurityforcemonitor Looks like the shapefiles are a paid feature: http://www.geonames.org/products/premium-data-polygons.html

**Comment by tonysecurityforcemonitor** [comment]
> @tonysecurityforcemonitor Looks like the shapefiles are a paid feature: http://www.geonames.org/products/premium-data-polygons.html

@evz Ah ok - thanks for finding that

**Comment by tlongers** [comment]
Old discussion. We moved to OSM, and (at at late 2018) import OSM objects using a combination of OSM's Overpass API  and Wambacher boundary service.

Closing.
