### ISSUE TITLE
Remove unused code

### ISSUE THREAD

**Issue by reginafcompton** [security-force-monitor/sfm-cms#157]
The codebase has a fair amount of unused and out-of-date code, e.g., the delete logic for person membership and the utils functions. 

https://github.com/security-force-monitor/sfm-cms/blob/master/sfm_pc/utils.py#L488
https://github.com/security-force-monitor/sfm-cms/blob/master/membershipperson/views.py#L204

Let's identify such unneeded code and remove it.

**Comment by tlongers** [comment]
Seems sensible, dev time allowing. Keeping it around until otherwise nixed.

**Comment by tlongers** [comment]
:) always good to have an issue on removing unused code, but closing this one.
