### ISSUE TITLE
Spanish translation not working

### ISSUE THREAD

**Issue by MichelManzur** [security-force-monitor/sfm-cms#160]
Hi @jeancochrane !!

I just accessed the platform and apparently the Spanish translation is not working yet:

![image](https://user-images.githubusercontent.com/26383493/29832827-7921a358-8cb7-11e7-8e95-abb98d3bab91.png)

Maybe is just my account?

**Comment by jeancochrane** [comment]
Hi @MichelManzur! Looks from [the docs](http://django-rosetta.readthedocs.io/en/latest/usage.html?highlight=wsgi#translate-away) like we might need to restart the web server each time we edit the messages file. I just restarted it; check again to see if it's working.

Another thing to check: does Rosetta show that fields have been translated? I just realized that if you had already done any translation work last week, we may have accidentally overriden it by deploying our changes! If so, that's something we should definitely avoid in the future.

**Comment by tonysecurityforcemonitor** [comment]
@jeancochrane - hmm it doesn't seem to be working for me either after the restart...

![image](https://user-images.githubusercontent.com/18744855/29834427-d39e1faa-8cbc-11e7-8b80-f5c1985d64fc.png)

**Comment by MichelManzur** [comment]
Hi @jeancochrane I just accessed Rosetta through @tlongers account and apparently the translations were erased. I will translate thing again, but it will take me a while.

**Comment by jeancochrane** [comment]
Really sorry to hear that @MichelManzur. We should have been more careful deploying our changes.

Superceding this with #161, where I'll fix the problem with deployments erasing translations. Making this high priority for today.

**Comment by MichelManzur** [comment]
@jeancochrane don't worry! 

Yes, just let me know when I can start translating again. Thanks!
