### ISSUE TITLE
Setup daily database backups

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#161]
As per #160, translations are currently set to get deleted when we deploy. We need to avoid doing this in the future. We also should backup translations on AWS.

**Comment by jeancochrane** [comment]
Translations are no longer being deleted. Changing this to an issue about the backup.

**Comment by tlongers** [comment]
Maybe a bigger ticket here regarding overall backup protocol?

**Comment by jeancochrane** [comment]
Translations are now being backed up daily as of [92d3e16](https://github.com/security-force-monitor/sfm-cms/commit/92d3e16082684a98b430ea101db96686b67c8a90).

Changing this issue to reflect @tlongers' question: what's our backup protocol? Once data entry begins, should we plan to do a daily snapshot of the database and expire each snapshot after 30 days? Curious to hear what @derekeder and @evz think.

**Comment by jeancochrane** [comment]
Updated the title to reflect the remaining work that needs to be done.

**Comment by jeancochrane** [comment]
Production backups are in as of https://github.com/security-force-monitor/sfm-cms/commit/daae17d09ce7b55c655011c301754bb2b2663db9.
