### ISSUE TITLE
How a guest views the site

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#164]
If possible, can we have an account that corresponds to the read-only ```guest``` role, which will have no data entry, update, deletion capabilities?

**Comment by jeancochrane** [comment]
Related to #171.

**Comment by jeancochrane** [comment]
Guest views are ready to roll in #232. If you all are OK with it I can pull it in and password protect the site on the server level.

**Comment by tlongers** [comment]
Thanks - pause on this for a moment whilst we cogitate on launch plans.

**Comment by tlongers** [comment]
So, when deployed, activate guest view and htaccess the

**Comment by jeancochrane** [comment]
Done in #232. Credentials coming shortly.
