### ISSUE TITLE
Colour scheme / contrast / red

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#165]
* Colour scheme needs a refresh. Perhaps a sepia base with one or two standout colours?

Some specifics:

* Site-wide replace of red links (and other elements like icons, mouseovers)  with standard blue (helps out people with [red/green colour blindness](https://www.w3.org/TR/low-vision-needs/#color-vision) ). Open question about use of red in warnings/alerts.
* Increase contrast between selected/unselected colours on front-page entity select boxes. Currently it is possible but hard to tell which is selected:

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/29856411-81db6694-8d4a-11e7-96a3-36de28789273.png)

**Comment by jeancochrane** [comment]
Agreed. Let's talk today about color inspirations.

**Comment by tlongers** [comment]
Leave colourscheme as it is but lighten the selected entity?
