### ISSUE TITLE
Drop down width in general facet panel

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#167]
Certain drop downs don't respond to narrowing of  the window width:

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/29856968-0b1d5cf2-8d4e-11e7-9d98-4ab391e14d8b.png)

**Comment by jeancochrane** [comment]
I've been struggling with getting select2 to be mobile responsive in general. Do you have any experience with this @evz?
