### ISSUE TITLE
Facet visibility for empty values

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#169]
```en/search/?entity_type=Person&selected_facets=person_current_role_s_exact%3AJefe%20de%20personal```

This search yields a sole person result. The person's current ```rank``` is ```none```. Where there is no value, I would expect a facet to still display and to tell me there is a category of ```none```.

**Comment by jeancochrane** [comment]
Sounds like we want to [turn `facet.missing` on](https://wiki.apache.org/solr/SimpleFacetParameters#facet.missing).

**Comment by tlongers** [comment]
Ah those solr folk think of everything :)

**Comment by jeancochrane** [comment]
That's why we love them!

**Comment by tlongers** [comment]
:/ `en/search/?entity_type=Person&selected_facets=person_current_rank_s_fct_exact%3ANone` throws a 500.

**Comment by jeancochrane** [comment]
Oops, that was from some boneheaded logic in the suggester. https://github.com/security-force-monitor/sfm-cms/commit/43a66b39e93a946fe85c55c6b72c07ca39bca7b2 should fix it.

**Comment by tlongers** [comment]
An oddity possibly related to this: `Location Description` facet on `incidents` records is currently showing only showing `none` as a value.

**Comment by jeancochrane** [comment]
Looks like I was using the wrong key for the facet. https://github.com/security-force-monitor/sfm-cms/commit/2eb30fe6f83fff2bsdc3e3491cda817a8050a2e1b should fix it.

**Comment by tlongers** [comment]
That fix  had an unusual effect on the display of items in the search results list:
![sfm_dashboard](https://user-images.githubusercontent.com/2115933/31348614-259b0770-ad18-11e7-9f6c-edafb8c7459a.png)

**Comment by jeancochrane** [comment]
Whoops, that was part of my (too) big expansion of citation coverage in https://github.com/security-force-monitor/sfm-cms/commit/a381a652ea0effaaf54d5eb173c82039529c7468. Quick fix in https://github.com/security-force-monitor/sfm-cms/commit/48387ca08b0728aeedc7dc082abaa319816cf110 should do the trick.

**Comment by tlongers** [comment]
Citation tag rampage!
