### ISSUE TITLE
Translations review for new SFM site 

### ISSUE THREAD

**Issue by MichelManzur** [security-force-monitor/sfm-cms#174]
Hi @reginafcompton and @jeancochrane 

I'll start throwing in here screenshots of the new tool, flagging which translations are still not reflected or they were not displayed in the Rosetta list.

Also I will spend some time doing some necessary corrections on the language to make it more logic.

I will let you guys know when I am done so you can reboot the system and go over existing errors (if any).

Thanks for all the work! This is looking great!

**Comment by MichelManzur** [comment]
![image](https://user-images.githubusercontent.com/26383493/29892612-32a519dc-8d9d-11e7-8ae8-36c8afcf4e91.png)

**Comment by MichelManzur** [comment]
![image](https://user-images.githubusercontent.com/26383493/29892680-81cce1ca-8d9d-11e7-9198-dbce2bfc58b3.png)

![image](https://user-images.githubusercontent.com/26383493/29892785-f460b630-8d9d-11e7-9773-5b9dee7a1e6c.png)

![image](https://user-images.githubusercontent.com/26383493/29893012-abaec7c8-8d9e-11e7-885f-94d9b0de4f8f.png)

![image](https://user-images.githubusercontent.com/26383493/29893226-60c31f6a-8d9f-11e7-98e7-404301bc252d.png)

![image](https://user-images.githubusercontent.com/26383493/29893432-0fefead6-8da0-11e7-8643-297d57c7a88b.png)

**Comment by jeancochrane** [comment]
This is super helpful @MichelManzur! Keep posting them as you find them. @reginafcompton and I are going to make fixing these mistakes high priority.

I'm going to edit your comments and mark them with the text **Done** when we think they're done -- does that work for you?

**Comment by MichelManzur** [comment]
Sure @jeancochrane @reginafcompton! That works for me. I´ll keep spending time on it and keep flagging any missing translation. 

Also, I realized there is a bunch of concepts and words that wont appear in the platform as such (because they will be used for setting up accounts and email text). Is there a way I can check these? Can I  create a mock up account to test it?

**Comment by reginafcompton** [comment]
@MichelManzur – we'll need to do a little decoding in the JavaScript for the language dropdown to work. Can you confirm that you'll translate "English," "French" and "Spanish" as such?

French – 'Français' and 'Francés'
English – 'Anglais' and 'Inglés'
Spanish – 'Espanol' and 'Español'

**Comment by MichelManzur** [comment]
Hi @reginafcompton 

I think Spanish in Frnech is "Espagnol".

The rest is correct.

**Comment by MichelManzur** [comment]
![image](https://user-images.githubusercontent.com/26383493/29933971-7f09dfc4-8e47-11e7-87df-e64864d1b372.png)

**Comment by MichelManzur** [comment]
This section is not translated at all:


https://back.securityforcemonitor.org/es/set-confidence/

![image](https://user-images.githubusercontent.com/26383493/29936240-767253c0-8e4f-11e7-90ee-4e4f94315da2.png)

**Comment by jeancochrane** [comment]
@MichelManzur the set-confidence page is deprecated, you shouldn't be able
to get to it! We'll remove it this afternoon, but in the meantime do you
recall how you navigated there?

**Comment by MichelManzur** [comment]
@jeancochrane yes, do you mean this page?

![image](https://user-images.githubusercontent.com/26383493/29936240-767253c0-8e4f-11e7-90ee-4e4f94315da2.png)

 It showed up automatically at the end of the "create new source process"
My navigation was as follow:


New source > Next > Units >Next > Personnel > Next >Positions >Next > Geographies > Skip

**Comment by tlongers** [comment]
This refers to 2017 deployment. Closing.
