### ISSUE TITLE
Missing map in record view in Spanish 

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#177]
```~/es/organization/detail/151/``` is missing  map for ```Areas of operation```. It's fine on ```~/en/~```.

**Comment by jeancochrane** [comment]
I'm guessing this is a formatting error related to commas/periods for decimals, right @reginafcompton?

**Comment by reginafcompton** [comment]
That seems like a good hypothesis...looking into it, now!
