### ISSUE TITLE
Adding Source - Unable to add country

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#180]
**What I'm trying to do**
I am trying to enter a source from the Premium Times a publication from Nigeria

**What I expect**
After entering Premium Times in the "Publication" field I move down to "Publication Country" and type Nigeria - this does not bring up any results. I'd expect that it would already be in the system or that the system has a standard taxonomy of country names to force standardization. Tabbing or clicking once this is displayed I would assume my country designation would be saved.

**What happened**
The entry of Nigeria did not save leaving the field blank

**screenshots**
Putting Nigeria in
![image](https://user-images.githubusercontent.com/18744855/29938007-53562398-8e55-11e7-833b-46a10a74939c.png)

Result of tabbing or clicking away
![image](https://user-images.githubusercontent.com/18744855/29938048-6fb4d714-8e55-11e7-9860-b1ae74a6ed51.png)

**Comment by jeancochrane** [comment]
Great catch @tonysecurityforcemonitor. It looks like the table that provides our Country models hadn't been created during migration. Just created it, I'm going to confirm that it's fixed in a second.

**Comment by jeancochrane** [comment]
Closed by [7e9c563](https://github.com/security-force-monitor/sfm-cms/commit/7e9c5632a636dfad88637baf5b99eb92a1516c00). 

It worked for me on the staging server, but if you notice this again feel free to reopen @tonysecurityforcemonitor and @MichelManzur !
