### ISSUE TITLE
CMS / After creating a new source

### ISSUE THREAD

**Issue by MichelManzur** [security-force-monitor/sfm-cms#183]
I was expecting to see a pop-up notification that I uploaded a new source or that I did the process correctly. 

Also not sure how the "archive" part works.

**Comment by jeancochrane** [comment]
Hm, this should be implemented already. The code also doesn't have any links to the `set-confidence` page on our end, which you were somehow linked to in . I'm wondering if the site is caching too aggressively and you're seeing an old version -- do you mind [clearing your cache for the staging site](https://superuser.com/questions/173210/how-can-i-clear-a-single-site-from-the-cache-in-firefox) and letting me know if the issue persists?

**Comment by MichelManzur** [comment]
I cleared my cache and created a new source the same way. I still end up at the set-confidence page:

![image](https://user-images.githubusercontent.com/26383493/29942549-4a9133c4-8e64-11e7-8e03-19296c915979.png)

**Comment by jeancochrane** [comment]
OK, thanks for giving it a shot! I'll look into it.

**Comment by tlongers** [comment]
Refers to earlier version of data creation tool. Closing.
