### ISSUE TITLE
Adding Unit - tab/enter don't work as expected

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#184]
**What I'm trying to do**
I'm entering the names of units from a source - the small drop down appears with the same text as I entered, from there I want to hit enter or tab so that I can quickly move to the next field (rather than navigating via mouse and clicking on the drop down tab).

**What happens**
Hitting enter or tab clears or does not save the name I entered.

**Screenshots**
I've entered in the name in the text field and the drop down appeared with the same name highlighted in blue
![image](https://user-images.githubusercontent.com/18744855/29938587-4d0e3fc8-8e57-11e7-9ebe-bda6c8e833b8.png)

clicking enter or tab clears the name
![image](https://user-images.githubusercontent.com/18744855/29938635-706c73fe-8e57-11e7-868d-6114434c4d23.png)

**Comment by tlongers** [comment]
Refers to earlier development. Closing.
