### ISSUE TITLE
Adding Unit - unable to add second unit

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#185]
**What I'm trying do to**
I'm trying to add a second unit and when I finish enter the name I expect clicking on the blue selection in the drop down menu my entry will be saved and I can move on to another field.

**What happens**
Clicking on the blue selection of the drop down just clears my entry. It's unclear how I would enter more than one unit at the same time.

**screenshots**
I've entered the text and want to click on the blue drop down to confirm my entry
![image](https://user-images.githubusercontent.com/18744855/29938966-61b96cb2-8e58-11e7-8a9e-be06ae0cf4f0.png)

After clicking my selection it clears
![image](https://user-images.githubusercontent.com/18744855/29938928-4b6438d4-8e58-11e7-8e10-452b14a0bcd3.png)

**Comment by tonysecurityforcemonitor** [comment]
It appears I got this error because I was automatically logged out. When I clicked "Next" I was sent to the login screen.

There was no indication that this had happened or warning that it was going to happen.

**Comment by tonysecurityforcemonitor** [comment]
Logging back in I was taken back to the screen to add Units - my entry of the source had been saved which is nice:

![image](https://user-images.githubusercontent.com/18744855/29939179-03ea7cf6-8e59-11e7-8607-2f913a7e4238.png)

**Comment by jeancochrane** [comment]
Sorry about that @tonysecurityforcemonitor! @evz is fixing some sticky authentication bugs, and had to log everyone out temporarily. We'll let you know if we have to do that again.

**Comment by jeancochrane** [comment]
As to the tabbing issues, I think this is the same issue as #184. Something's up with the validation on certain select2 search/dropdown fields, I'm seeing it occasionally clear the box when I select something too (although it seems from the page source that it's recording the changed information properly, it's just not displaying it).

**Comment by tlongers** [comment]
Can't reproduce this.

**Comment by jeancochrane** [comment]
Are you still seeing this @tonysecurityforcemonitor? I figured out that we hadn't been using the proper API method for clearing select2 boxes, and tried to change it everywhere I noticed the problem (a few form fields had been like this). Let me know if you find any more instances of it and I can take a look.

**Comment by tlongers** [comment]
Refers to previous work on data entry. Closing.
