### ISSUE TITLE
CMS / Duplicated sources

### ISSUE THREAD

**Issue by MichelManzur** [security-force-monitor/sfm-cms#187]
The system allowed me to enter the same information from the same source, without any warning or notification.

Also

After creating a new source, if I go back to the "Personnel" and look up for the person's information I just entered:

https://back.securityforcemonitor.org/en/person/detail/660/

**Comment by jeancochrane** [comment]
True, we don't do any validation to check for duplicate sources. This raises the interesting question of what constitutes a "duplicate" source -- do you think it's same title/publication? Or are publication/publication date necessary too? Curious what @tonysecurityforcemonitor and @tlongers think, too.

**Comment by tonysecurityforcemonitor** [comment]
@jeancochrane 

- I'd think title/publication/date published would be a good catch to suggest a duplicate (would handle most sources where the information is just a copy/paste)
- I'd also say url by itself would be a good catch as well - especially for sources where the title is not clear and different researchers might enter something different. In general the url would catch most cases.
- It would be great if the system could suggest that a source is a duplicate and allow the researcher the option resolve it somehow to a "canon" version of the source information - or not if the researcher believes it is not a duplicate. 
- So in my mind duplicates are suggested either by title and publication and date published match - or - by url match

**Comment by tlongers** [comment]
Source handling has been completely reworked (Sept 2018) to avoid this issue. Closing.
