### ISSUE TITLE
CMS / Duplicated classification 

### ISSUE THREAD

**Issue by MichelManzur** [security-force-monitor/sfm-cms#188]
After creating a duplicated new source, the classification duplicates as well instead of merging it, showing something like this:

![image](https://user-images.githubusercontent.com/26383493/29940641-dbd8d00a-8e5d-11e7-9ec8-3b3d15df64b7.png)

Maybe this happened because the source and information was duplicated?

**Comment by jeancochrane** [comment]
@tlongers I think we should leave this open, but since it has to do with fixing the data entry wizard I propose to remove it from the Milestone. (These duplicates will be removed when I pull in #245 and redo the data import.) Any objections?

**Comment by tlongers** [comment]
Cleared.

**Comment by tlongers** [comment]
Not an issue now. Closing.
