### ISSUE TITLE
CMS / Adding a new Publication

### ISSUE THREAD

**Issue by MichelManzur** [security-force-monitor/sfm-cms#189]
I was trying to create a new source from the "Gobierno del Estado de Zacatecas", however I first typed in the "Publication": SEDENA". When I tried to change it to "Gobierno del Estado de Zacatecas", the page kept putting "SEDENA".

I refreshed the page and this got fixed, so I assume it can be a minor bug?

**Comment by tlongers** [comment]
This is still an issue.

**Comment by jeancochrane** [comment]
Related to the bug in #185.
