### ISSUE TITLE
Can differentiate unit/person with same name?

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#190]
#188 makes me think we can't have two or more units or people with the same name exist as distinct entities. This is rare for units, but can happen with people. We spend a lot of time investigating whether a person with the same name (or very similar names) and different postings is actual the same person.

A separate issue for us is how does our methodology handle this. We have added text to a name to help users and ourselves quickly distinguish between two different records - which in effect means they do not actually share the same name. For instance there are multiple "Central Police Station" units which we have taken to adding the city or even the city and state in the name. Example: [Central Police Station (Umuahia, Abia State)](https://back.securityforcemonitor.org/en/organization/detail/162/).  While this may work for units I'm not sure how we would handle it for People...

**Comment by jeancochrane** [comment]
Great question. Maybe we should think about redirecting to a "merge entities" page in case we detect likely duplicates (in sources/units/personnel)? AFAIK merging functionality already exists, it would just be a matter of integrating it with the form.

**Comment by jeancochrane** [comment]
We also may want to show more context (like related geographical information) for search results in forms where you're searching for places, which seem to have a high likelihood of duplicates.

**Comment by tonysecurityforcemonitor** [comment]
@jeancochrane - this all sounds great as far as integrating the form. Quick question about time/resources, would this be a serious task that we should punt to Chunk 2?

Also that's a good point as far as what addition information would help flag cases to merge which would be:
**Units**
Geography (Site or AOO)
Parent/Child relationships
Memberships

**People**
Organization Membership with related Role(s) and/or Rank(s) and dates of service

I'll also flag here that we do have non-contiguous service, membership, or parent/child relationships as a concept.

For units this means the 1 Battalion can be a child of Third Brigade between 2010-2011 and then again 2014-2015.

For people this means Major General John Smith can be the commander of the 4 Division between 2009-2011 and again 2016-2017.

**Comment by tlongers** [comment]
Pre-population of the data entry form goes some way to making this problem easier to deal with, as it indicates which units the existing record is tied to. It doesn't make it easier in the event that someone with the same name is in the same unit (...at the same times), which is not improbable. With regard to Chunk 1 work, I think this is more of a method issue: we have to ensure that duplicates are weeded out before entry.

**Comment by tonysecurityforcemonitor** [comment]
>  I think this is more of a method issue

@tlongers  - agreed - I think we'll just have to put some differentiating information in ( ) like I've done for units - for instance the multiple organizations that have the name `Central Police Station` in Nigeria I've differentiated by adding geography into their name - for example - `Central Police Station (Umuahia, Abia State)`

**Comment by tlongers** [comment]
In the cms, entities are now indexed by a UUID  not the value in `org:name`. Methodologically, we've also adopted the practice of differentiating orgs that have the same name by adding a clarifier in parenthesis. Closing.
