### ISSUE TITLE
CMS / Question on "Real Context?"

### ISSUE THREAD

**Issue by MichelManzur** [security-force-monitor/sfm-cms#192]
I am not sure what does "Real Context?" stands for and not sure if we should click on it and when.

![image](https://user-images.githubusercontent.com/26383493/29941877-f74d0be0-8e61-11e7-8cb5-64e240748e30.png)

**Comment by jeancochrane** [comment]
I actually don't know, and @evz also reports confusion. My current guess is that it's referring to "real" start and end dates (as opposed to just citations), sort of related to the open-ended fields that we're adding to a couple different data types in #141. In this case, perhaps it's poorly labelled -- it's not the context that's real, it's the date. Does that sound right @tonysecurityforcemonitor?

I'm also a little confused on what "context" is in general, but judging by the values in the database it seems to be a string explaining the events surrounding the person's start/end in this position. Correct me if that's substantially off-base.

**Comment by tlongers** [comment]
Closing as direct issue has been adressed and "context" fields are no longer present in the platform. Other stuff outlined by @tonysecurityforcemonitor  to do with data model changes to be debugged if issues arise.
