### ISSUE TITLE
No "Informal" option for Parent/Child relationships

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#193]
On the "Unit Relationships" page there is no option for Informal Parent/Child relationships.

![image](https://user-images.githubusercontent.com/18744855/29941972-3fd60f74-8e62-11e7-8fd0-d76bee478243.png)

**Comment by jeancochrane** [comment]
Right now we just pull this from a [list of all the existing classification types](https://github.com/security-force-monitor/sfm-cms/blob/master/composition/views.py#L41) in the database. Is there a better way for us to do this? Do we want the user to be able to define new relationship classifications, or should it always be a choice between `Command/Administrative/Informal`?

**Comment by tonysecurityforcemonitor** [comment]
@jeancochrane - good question - let's keep it to Command/Administrative/Informal for now. I can see a future where we have additional classifications, but adding them would need to be the result of a major methodological conversation, not "on the fly" so to speak. Perhaps a happy medium is to attach the creation of new Relationship classifications to a high level admin role?

**Comment by tlongers** [comment]
@jeancochrane This was fixed, but now ```administrative``` is missing from the options used to classify relatioships.

**Comment by tlongers** [comment]
We'll check on a controlled vocab for this classification field, but this refers to older versions; closing.
