### ISSUE TITLE
Are classifications a required field for units?

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#194]
Question for @tonysecurityforcemonitor:

@reginafcompton and I are running into issues with a test that grabs a random unit from the database. According to the database, unit classifications are not required; according to the form, however, they are. This sometimes causes failures in our test for creating organizations, since we occasionally grab a unit that doesn't have a classification and the form gets mad.

Clearly either the form or the database should be updated; which one is correct?

**Comment by tonysecurityforcemonitor** [comment]
Hi @jeancochrane - classifications should be required for a unit

**Comment by jeancochrane** [comment]
Great, thanks for the speedy reply @tonysecurityforcemonitor!
