### ISSUE TITLE
CMS / Creating a new source with a time conflict

### ISSUE THREAD

**Issue by MichelManzur** [security-force-monitor/sfm-cms#197]
**What I am trying to do:**

I am trying to create a new source for a person, putting it in charge of 2 different units at the same time using the same source to see how the CMS shows this.

I uploaded "Gerardo Rubén Serrano Herrera" from a source of "El Universal" http://www.eluniversal.com.mx/articulo/nacion/seguridad/2016/12/6/osorio-chong-encabeza-reunion-de-seguridad-en-chihuahua

First date cited: 12/6/2016 
Last date cited: 9/1/2017

First I flagged him as the commander of the IX Región Militar

Then as the commander of the XI Región Militar, using the same source and the same dates. 

**What happened:**

The CMS allowed this but there is no reference to the XI Región Militar. Instead the name was duplicated without any further information:

![image](https://user-images.githubusercontent.com/26383493/29976820-636003da-8f09-11e7-969d-39f407e9c699.png)

Also the classification was duplicated as stated in #188

**Comment by tlongers** [comment]
@jeancochrane any idea why this would happen?

**Comment by tlongers** [comment]
Issue no longer relevant. Closing.
