### ISSUE TITLE
CMS / Results not shown

### ISSUE THREAD

**Issue by MichelManzur** [security-force-monitor/sfm-cms#199]
There are some cases, when the results are not displayed.

Like when you search for XI and there are only 2 Results, but they are not shown:

![image](https://user-images.githubusercontent.com/26383493/29978907-3f1419fa-8f11-11e7-9243-a27c9ba7d433.png)

Same searching for the XI Región Militar

![image](https://user-images.githubusercontent.com/26383493/29984529-d9325bac-8f28-11e7-8283-8a1f295a55ac.png)

**Comment by tlongers** [comment]
This breaks our testing. Can we have a priority fix on it? @jeancochrane

**Comment by jeancochrane** [comment]
Absolutely. I'll take a look this morning @tlongers @MichelManzur.

**Comment by jeancochrane** [comment]
Both of these searches are now back up. Thanks for your patience on that @tlongers @MichelManzur! It was a bug in the template code that was failing ever so silently.

Let me know if you notice anything else that's missing and I'd be glad to take a look at it.
