### ISSUE TITLE
No results found - Let us know! - link not working

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#200]
When a search returns no results there is a message:

![image](https://user-images.githubusercontent.com/18744855/29984629-40650d88-8f29-11e7-984f-1bdfc32d411c.png)

Clicking on "Let us Know!" does not produce any action. Is the thought that is would autogenerate a response with the relevant information that a user could add additional text to?

**Comment by reginafcompton** [comment]
This is currently an empty <a> tag....would we like it to link to an email address?

**Comment by tonysecurityforcemonitor** [comment]
@reginafcompton - it would be great if there was some way to automatically generate some information that would be helpful for us to know what page the user was looking at, what they were trying to search, etc. and give the user the option to add any additional comments on top of it. @tlongers - any thoughts here? Also which email would be best, the techical@sfm?

**Comment by tlongers** [comment]
Duplicate of #134.

**Comment by jeancochrane** [comment]
Unfortunately Django doesn't have any built-in commenting features, so I've added a mailto link in https://github.com/security-force-monitor/sfm-cms/commit/deb73f37451368f107141213ae3fad595661a992. The fastest and highest-payoff thing we could do, in my opinion, is track searches that show no results, either through Sentry (our error logging platform) or through analytics. Is that something that might help?
