### ISSUE TITLE
Adding Source - Unit Relationships - everything cleared on "go back"

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#203]
**what I was doing**
I got to the "unit relationships" page and came to the default selections.

![image](https://user-images.githubusercontent.com/18744855/29985796-843ec094-8f2e-11e7-9dab-2f1320453350.png)

I changed some categories around changing the relationship types, the related organization, the relationship classification and added some start/end dates. 

![image](https://user-images.githubusercontent.com/18744855/29985755-4d491968-8f2e-11e7-8c55-e8b95988f046.png)

Then I hit "Next". When on the next page "unit memberships" I hit "Go back" and returned to the "Unit relationships" page - however - all of my selections had been reset to the default and the start/end dates had been cleared.

![image](https://user-images.githubusercontent.com/18744855/29985796-843ec094-8f2e-11e7-9dab-2f1320453350.png)

**What I expected**
I though the pages saved automatically so that any time I hit "Go Back" I would be taken to the previous page where all of my entries would have been saved, allowing me to edit any mistakes or add something that I forgot.

**Comment by tlongers** [comment]
Closing. Refers to older version.
