### ISSUE TITLE
Adding Source - Unit memberships allow parent and membership

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#205]
**what I was doing**

In the "Unit relationships" page all of the units I entered data on the command relationship between two units and gave associated dates for those command relationships.

![image](https://user-images.githubusercontent.com/18744855/29986095-e6ff033c-8f2f-11e7-8fd8-6b00b980b232.png)

On the next page "unit memberships" I was able make those same units members of their children at the same time. 

![image](https://user-images.githubusercontent.com/18744855/29986634-4e51fc54-8f32-11e7-87a2-e581606680a3.png)

**what I expected**
This should not be allowed - the parent/child hierarchy trumps membership. Basically, the parent/child relationship is saying that 12 Brigade is above the 2 Battalion in a hierarchy - while the membership is saying some people from 12 Brigade went and became part of the 2 Battalion for some period of time, when they were there they were under the control of 2 Battalion --- there is no implied relationship between the two organizations.

Of course that being said this would mean the system would have to take into account the start/end dates of parent/child and membership to make sure they didn't overlap. In theory you have a relationship where 2 Battalion had a membership with 12 Brigade from 2010 to 2011 and then was a child of 12 Brigade from 2012 to 2015. That would be fine and should be allowed by the system. Not sure if this should be pushed to Chunk 2.

**Comment by tlongers** [comment]
I can't access this part of the data entry process.

**Comment by tonysecurityforcemonitor** [comment]
@tlongers - it only appears if you enter more than one organization

**Comment by tlongers** [comment]
Got it, thanks.

**Comment by tlongers** [comment]
This if fixed. Data entry wizard redesigned around relations, not by unit. Data validation of parent child input ensures parent and child must be different organizations.
