### ISSUE TITLE
Adding Source - Personnel, allows division_id not to match org

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#206]
A researcher is able to independently assign a division_id to a Person even if it does not match the division_id of the Organization that they are a member of. Perhaps a solution would be to have this auto-populate based on whatever Organization the person is a member of.

**Comment by tlongers** [comment]
@tonysecurityforcemonitor What about peacekeeping/foreign deployment scenarios? Person is an ```ng``` officer but ```organization``` is based in ```sdn```? Our method documentation on this is missing too.

**Comment by tonysecurityforcemonitor** [comment]
@tlongers - this is something I raised in #207 - in my mind it made sense for a person to be able to have multiple division_ids - so they would have `ng` based on their membership in `ng` organizations - but also `sdn` based on their membership in peacekeeping units based in `sdn`.

**Comment by tlongers** [comment]
@tonysecurityforcemonitor Old issue but you can find examples where we implemented this?

**Comment by tonysecurityforcemonitor** [comment]
> @tlongers - this is something I raised in #207 - in my mind it made sense for a person to be able to have multiple division_ids - so they would have ng based on their membership in ng organizations - but also sdn based on their membership in peacekeeping units based in sdn.

Agreed - this approach makes sense to me as well.

@tlongers - I don't see a situation where we implemented this however - I'm not seeing people attached to peacekeeping roles in the most recent version of the dataset...

**Comment by tlongers** [comment]
Closing!
