### ISSUE TITLE
Can a person have multiple division_ids?

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#207]
Question - can a person have two or more different division_ids? I'd like it so the a single Person was able to have multiple division_ids and would show up in search results for the countries they have a division_id for. For example - let's say Major William Black serves in a battalion in Iceland (giving him a division_id of Iceland via his organizational membership) and then goes to serve in a peacekeeping unit in Finland (giving him a division_id of Finland via his organizational membership). I'd like it so that if a user was doing a search with a filter to only show people in Iceland Major Black would come up in the results -- and conversely -- if a user was doing a search with a filter for Finland Major Black would also come up.

Does it break anything do have that be an option?

**Comment by jeancochrane** [comment]
On a table level, personnel can only have one `division_id` at a time. Since units also have a `division_id` attribute, however, we could pretty quickly set this up for the search index by checking a person's command history and adding any extra `division_ids` for units that they've been a member of.

A slightly more involved approach would be to adjust the data models for personnel and units so that entities can have multiple `division_id`s at one time. This would take more time to implement, but it sounds like it's closer to the way you all are thinking about geographies?

**Comment by tonysecurityforcemonitor** [comment]
@jeancochrane 

> On a table level, personnel can only have one division_id at a time. Since units also have a division_id attribute, however, we could pretty quickly set this up for the search index by checking a person's command history and adding any extra division_ids for units that they've been a member of.

If this means person can appear in search results with different division_ids then that's great. Would this also work for a Person's profile page - ie showing their memberships in units with different division_ids?

> A slightly more involved approach would be to adjust the data models for personnel and units so that entities can have multiple division_ids at one time. This would take more time to implement, but it sounds like it's closer to the way you all are thinking about geographies?

What I'm raising is very much an edge case so I don't want it to distract too much from other more pressing concerns. It does seem like the second option is more comprehensive since it would allow for a single person to be represented in searches of different division_ids and also have a clear career history in their profile view of being a member of units with different division_ids.  But then I'm not sure if the first option is giving us the same result whether we need to do this or not.

**Comment by jeancochrane** [comment]
Yep, we could certainly update the profile pages to show country codes for the different memberships! Seems like the first approach is the most feasible for now, then.

**Comment by tlongers** [comment]
It's still a good edge case, but we unlikely to need to resolve this. To find the countries in which a person has been posted, check the units they have been posted in.
