### ISSUE TITLE
Extend range of fields included in search index

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#208]
When searching, what fields are searched? Would it be possible to include textual geographical fields e.g ```organization site name```?

(updated title to reflect the issue better)

**Comment by jeancochrane** [comment]
Absolutely. Right now the fields we index are:

| Entity type | fields |
| -------- | ----- |
| Personnel | `name`, `aliases` |
| Units | `name`, `aliases` |
| Incidents | `description`, `perpetrator`, `perpetrator_organization`, `perpetrator.aliases`, `perpetrator_organization.aliases` |
| Sources | `title` (although we haven't wired up search to search sources yet) |

These are for the global index, which is what gets searched when you enter text in the search bar; adding a date range and facets are handled slightly differently.

Seems like we could improve this very easily. What other fields seem relevant? Textual geographical fields seem like an excellent addition, including `site.name`, `admin_level_1`, and `division_id` (mapped to the country name) where applicable.

**Comment by tlongers** [comment]
@jeancochrane Here's an update to your table with candidates for inclusion in the search index:

| Entity type | fields |
| -------- | ----- |
| Personnel | `name`, `aliases`,`role`,`rank`,`title`,`division`|
| Units | `name`, `aliases`,`organization:classification`, `division`,`parent.id`,`headquarters`,`site:exact_location`,`Site:geonames_name`,`Site:admin_level_1_geonames_name`,`Area of Operations Geoname`|
| Incidents | `description`, `perpetrator`, `perpetrator_organization`, `perpetrator.aliases`, `perpetrator_organization.aliases`,`violation_type`,`perpetrator.classification`,`location`,`City or smallest administrative unit GeoName`,`ADMIN1 Geoname`,`division id` |

**Comment by jeancochrane** [comment]
@tlongers fantastic, thank you!

**Comment by jeancochrane** [comment]
What's the thinking behind indexing units on `parent.id` instead of `parent.name`? Do we anticipate people will be searching by ID?

**Comment by tlongers** [comment]
Sorry, by ```parent.id``` I mean ```parent.name``` - the text value.

**Comment by jeancochrane** [comment]
Done in https://github.com/security-force-monitor/sfm-cms/commit/fe6abebc263a6215d0f1ad754110f09382730dc3. This won't be super helpful until I liberalize the query parser (#272), but that's coming soon.
