### ISSUE TITLE
Automatically determine Archive URL?

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#21]
The Wayback machine has an API which will return archived snapshots of arbitrary URLs. So, for instance: 

http://archive.org/wayback/available?url=example.com

Returns the closest archived snapshot of example.com. In the case where there is no snapshot, there is a URL that you can hit that will force the wayback machine to create a snapshot: 

https://web.archive.org/save/http://example.com

The one snafu is that the actual archive URL contains a timestamp from when it was actually snapshotted which means that you'd have to wait a couple seconds and then hit the API again to get the actual archive URL. 

Anyways, something to stew on...

**Comment by tonysecurityforcemonitor** [comment]
> The Wayback machine has an API which will return archived snapshots of arbitrary URLs. So, for instance:

> http://archive.org/wayback/available?url=example.com

> Returns the closest archived snapshot of example.com. In the case where there is no snapshot, there is a URL that you can hit that will force the wayback machine to create a snapshot:

> https://web.archive.org/save/http://example.com

> The one snafu is that the actual archive URL contains a timestamp from when it was actually snapshotted which means that you'd have to wait a couple seconds and then hit the API again to get the actual archive URL.

> Anyways, something to stew on...

Making it easier to archive things would be very helpful. Yes let's definitely stew on this some more.

**Comment by tlongers** [comment]
+1 to making this part easier. Thinking aloud -- could the process of retrieving the snapshotted URL be booted out to a helper process to perform whilst the user continued data entry? When the URL is retrieved, let the user know with a little popup ("Hey! It's done. Be happy.")

**Comment by evz** [comment]
@tlongers This is a technical possibility to be sure. It might be a bit beyond what we're able to put together for this version. But since we're all on board with this as a generally good idea, I'll add it into "the future" milestone.
