### ISSUE TITLE
Remove unit option not working as expected

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#210]
Steps:
* in ```en/organization/create/``` click "add another unit" so we get two unit fieldsets
* Fill in the first of the unit fieldsets properly but leave the other empty
* Click "Next"
* Alerts will appear in the second fieldset indicating that mandatory fields have not been filled in
* Select "remove this unit", and okay the warning
* Click "Next" - the second fieldset returns, along with the warnings about mandatory things

**Comment by jeancochrane** [comment]
I noticed this too, it was a small JS bug. Will be fixed when #196 comes in.

**Comment by jeancochrane** [comment]
Fixed in #196. Let me know if this pops up again.
