### ISSUE TITLE
Classification tag - import error, or display error?

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#212]
Uh oh:

```~/en/organization/detail/1265/``` has duplicate entries in ```organization:classification```:

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/30103394-7147a48c-92ea-11e7-91a3-7e59682b98b3.png)

**Comment by jeancochrane** [comment]
I think this is the same problem as #188. The error is most likely in the validation for the data entry wizard.

**Comment by tlongers** [comment]
Ah sorry, should have searched better.

**Comment by jeancochrane** [comment]
Closing, c.f. #188.
