### ISSUE TITLE
Change geography search to use OSM ID

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#216]
>The current approach of searching on the OSM object name gives too many results, and we can’t differentiate between them. It’s a “good enough” solution, and we can use OSM Nominatim in a separate window to find the ID number we want to search on.

**Comment by tlongers** [comment]
This works nicely but in the OSM ID field, it should display the OSM ID number as entered (e.g. ```5999595 ```) rather than the OSM object name (e.g. ```Juárez```).

**Comment by jeancochrane** [comment]
Can do! While we're on the topic of finessing the geo-search, is the map thumbnail helpful for you all? Sometimes I wonder if it's too zoomed-in to really be informative.

**Comment by tlongers** [comment]
Thanks. I think the map thumbnail is a useful cue, and good to have. Perhaps pan it out one notch? What would be the alternative?

**Comment by jeancochrane** [comment]
How's this look @tlongers? Zoomed out one level and emphasizes the OSM ID over the name.

![osm-search](https://user-images.githubusercontent.com/14170650/30714140-65143542-9ed7-11e7-8c66-ed0f159b1ab8.png)

**Comment by tlongers** [comment]
Ahhh right. Sorry, I thought you were talking about the map on the right-hand side, which confirms a value selection, as I've never actually seen the in-selector thumbnails working as the links have been broken (Chrome, OSX) yet:

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/30730820-a8106228-9f61-11e7-8902-49f0a58bcb47.png)

What do you need from me to debug?

**Comment by tlongers** [comment]
For consistency, this method of querying OSM should also be placed into the General Filters in search results. Presently, the Location widget there works on OSM object name.

**Comment by jeancochrane** [comment]
Can do on the general filters. In terms of the map images not showing up, I'll take a look on the staging site; we thought it was an API key issue that we fixed, but maybe that wasn't the root of the error. I'll let you know if we need anything else!
