### ISSUE TITLE
Error in Nigeria data

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#220]
Check Start and End Date against source data - they are reversed:
![sfm_dashboard](https://user-images.githubusercontent.com/2115933/30283300-9c5979f6-970f-11e7-909b-03482ce3d964.png)

~en/person/detail/508/#memberships

**Comment by jeancochrane** [comment]
Do you think this is an error in the import script @tlongers, or in the source sheet?

**Comment by jeancochrane** [comment]
Vindicated!

**Comment by tlongers** [comment]
We'll take it from here (/me nods at @tonysecurityforcemonitor )
