### ISSUE TITLE
Person chart inconsistencies

### ISSUE THREAD

**Issue by reginafcompton** [security-force-monitor/sfm-cms#223]
I noticed one of the charts does not render correctly. Let's keep an eye out for other such cases. 

<img width="787" alt="screen shot 2017-09-11 at 1 19 25 pm" src="https://user-images.githubusercontent.com/13078679/30290161-07f2cea4-96f4-11e7-9709-69fb2b44dc70.png">

**Comment by tlongers** [comment]
Yeah, we've found a few too and have some feedback queued for you (pending the data model migration etc)

**Comment by tlongers** [comment]
Just quickly, this one jumped out for me just now: ~en/person/detail/671/ Note the difference in behaviour between the view at 4 August 2004 and subsequent views.

**Comment by reginafcompton** [comment]
Ah, yes. Seems to be a similar problem to the detail view for Abubakar (above).

**Comment by jeancochrane** [comment]
I'm having trouble reproducing this with the current data. Feel free to reopen with specific issues.

**Comment by tlongers** [comment]
Found some oddness at `~/en/organization/detail/240/`
<img width="886" alt="sfm_dashboard" src="https://user-images.githubusercontent.com/2115933/31603475-3952bd40-b258-11e7-937c-a27f978242f2.png">

**Comment by jeancochrane** [comment]
Thanks for flagging this @tlongers, I'll take a look. Might be related to #254.

**Comment by jeancochrane** [comment]
These errors are most likely coming from compositions that have neither start nor end dates, which can wind up returning command structures that don't make sense. What do we want to do in those cases? Easy fix is filtering out cases where we don't have start/end dates, but then we might wind up losing some chains that we care about.

**Comment by tlongers** [comment]
Thanks Jean. I'd rather make a call on this after an import of the full dataset, once we we can get a better sense of the prevalence of the problem and exactly what we might be losing out on by filtering out relations with missing start/end values. Leaving open until we get around to that.

**Comment by jeancochrane** [comment]
Moving this out of the Chunk 1.5 Milestone, unless there are any objections. I think it makes sense to keep thinking about this as we use the site more but it seems like it's outside the scope of this launch.

**Comment by tlongers** [comment]
Agreed. We will need to look quite closely at the behaviour of the chart, but not at this point. I think we need to get a sense of whether as a basic offering to users it hits the spot.

**Comment by tlongers** [comment]
Stale; this can still be an issue, but tends to be down to the underlying data and ambiguity around start/end dates. There may not be that much we can do about within this current component.
