### ISSUE TITLE
Check sidebar nav links against respective  anchors in unit pages

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#225]
In the main body```Memberships``` is wired up to a ```#parent-units``` anchor so the page jumps to wrong place. In main body```Parent units``` is anchored to ```#chain-of-command```, which doesn't yet have a sidebar link.

**Comment by jeancochrane** [comment]
Fixed this in https://github.com/security-force-monitor/sfm-cms/commit/a381a652ea0effaaf54d5eb173c82039529c7468.
