### ISSUE TITLE
Missing OSM ID numbers in Organizations search listing

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#226]
Links in ```Last site name``` in search listings at ```~en/search/?entity_type=Organization``` all point to ```https://www.openstreetmap.org/node/``` rather than full OSM ID numbers.

**Comment by jeancochrane** [comment]
Great catch @tlongers. This was a matter of a misnamed variable, so I went ahead and closed it quickly in [d16a2de](https://github.com/security-force-monitor/sfm-cms/commit/d16a2de4da97b5b4f985fb942b28b53339f54702).
