### ISSUE TITLE
CMS Translation to Spanish

### ISSUE THREAD

**Issue by MichelManzur** [security-force-monitor/sfm-cms#227]
Hi @jeancochrane and @reginafcompton ! Translation to Spanish is looking amazing on the CMS. I´ll keep posting miss-translations or lack of them.

![image](https://user-images.githubusercontent.com/26383493/30387991-4b98918c-987c-11e7-81f4-f2871230081b.png)

**Comment by reginafcompton** [comment]
Thanks, @MichelManzur! (Love seeing the internationalization of the site, too.) I'll get to these missing ones, shortly. I'll also walk through the site myself and add tags for anything that I see as untranslated.

**Comment by MichelManzur** [comment]
@reginafcompton one last issue with translations:

The numbers in Spanish will change as well for the dates:
Ie. from 27th February 2009 to 27 febrero 2009 without the "th"

![image](https://user-images.githubusercontent.com/26383493/30399321-44dd520e-98a1-11e7-9141-f8fd28a74ce3.png)

**Comment by jeancochrane** [comment]
First issue (facet labels) was closed in https://github.com/security-force-monitor/sfm-cms/commit/9c5083438f1884e02565fa2ad768948d7648fb65.

As to the second issue, I decided to standardize all dates to e.g. "27 February 2009" (dropping the English suffix on the number) in https://github.com/security-force-monitor/sfm-cms/commit/b0a2888b6954c8a8337d8493af6e5bcc640d0691. The suffixes were annoying me anyway. For posterity, we can customize dates for different languages (like Arabic) by defining [a different format](https://docs.djangoproject.com/en/1.9/ref/templates/builtins/#date) in a [custom locale file](https://docs.djangoproject.com/en/1.9/topics/i18n/formatting/#creating-custom-format-files).
