### ISSUE TITLE
Quotation marks appearing in incident title area

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#228]
For example, in  ```~en/violation/detail/10/```: 

<img width="502" alt="sfm_dashboard_" src="https://user-images.githubusercontent.com/2115933/30491730-22f6d1a6-9a36-11e7-98d7-f581a74a50a4.png">

**Comment by jeancochrane** [comment]
Fixed in [2e80519](https://github.com/security-force-monitor/sfm-cms/commit/2e80519a20b237e9e35d2b536fffa404838db505).
