### ISSUE TITLE
Behaviour/styling issues with the "I'm Looking for" filter (Safari only)

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#229]
Some behaviour/styling issues with ```select2-selection__rendered``` on "I'm looking for" sidebar on Safari (v 10.1.2). The issue is not present where ```select2-selection__rendered``` is used in ```~en/organization/create/```:
![sfm_dashboard](https://user-images.githubusercontent.com/2115933/30640794-553b6c7a-9dfc-11e7-8380-baca3954c303.png)

**Comment by tlongers** [comment]
Similarly, the dropdown and the date picker in General Filters are not functioning in Safari.

**Comment by tlongers** [comment]
Nor the facets!

**Comment by jeancochrane** [comment]
Woof, browser differences. I can take a look in BrowserStack.
