### ISSUE TITLE
Violation perps

### ISSUE THREAD

**Issue by achtor** [security-force-monitor/sfm-cms#23]
Should violations be allowed to have arbitrary combinations of perpetrators/perpetrator organizations? i.e. could we list people A, B, C, and organizations X, Y, Z as perpetrators, with none of A, B, C belonging to any of X, Y, Z? @tonysecurityforcemonitor

**Comment by tonysecurityforcemonitor** [comment]
> Should violations be allowed to have arbitrary combinations of perpetrators/perpetrator organizations? i.e. could we list people A, B, C, and organizations X, Y, Z as perpetrators, with none of A, B, C belonging to any of X, Y, Z? @tonysecurityforcemonitor

@achtor Yes lets allow arbitrary combinations. There have been cases where that has been the case - ie a person who belongs to the Army (exact unit unclear so their organizational affiliation is to the "top level" army organization) and a specific, low level organization is also involved

**Comment by evz** [comment]
This has been working for a while (can't find the specific commit)
