### ISSUE TITLE
Show which records have been created at the end of the data entry wizard

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#230]
The "skip" button on ```~en/violation/create/``` points to ```~/en/set-confidence```, which is a page that should be removed now the setting of confidence levels is done throughout the data entry wizard. But where should it point to? Skipping incident creation implies there is a following step, but it is the same as selecting "Finish", which is confusing. What should be done here?

**Comment by jeancochrane** [comment]
Excellent point, thanks for catching this! We should factor out the logic that updates search index and materialized views, and have the "Skip" button point to that. As I interpret it, we want "Skip" in this context to mean "I don't want to define an incident from this source, but I still want to save everything and update the search."

**Comment by tlongers** [comment]
I wonder if, following the incidents entry step we need an end page for the wizard. In this scenario, "skip" would carry out the search update operation, as well as:
- confirming to the user that the data entry has been successfully created
- alerts the user to which records that have been created, providing links to them so the user can navigate directly to them. 
This would be more elegant than returning to the home page, I think.

**Comment by jeancochrane** [comment]
That's an interesting idea @tlongers. We could also use that page as an opportunity to prevent timeouts by making the search index update into a delayed task, showing a spinner while it's working and then displaying the results once it's done.

**Comment by tlongers** [comment]
Yes, that's very neat. It could also be a page to weave in other useful, general efficiencies like "Add another source", or include "edit" links to each of the records.

**Comment by jeancochrane** [comment]
Changed the title of this and bumped it up to "high priority." Lengthening timeouts in #240 should stop the errors that prevent the search index from updating, but it still seems like a landing page is an important feature for helping you all test the integrity of the form. Sound OK? Feel free to bump down if you're not that concerned about it.

**Comment by tlongers** [comment]
@jeancochrane Fine to bump it. However, let's take a look over the Omnibus Feedback so we can ensure we're on the Same Big Page about priorities and remaining works.

**Comment by jeancochrane** [comment]
Sounds good to me @tlongers!

**Comment by jeancochrane** [comment]
Implemented basic mitigation for the issue in [4e31bae](https://github.com/security-force-monitor/sfm-cms/commit/4e31bae4ebb81d0166923a19e3520d3520d05b59). The skip button works now on the Incidents page, and submitting the last step (either by filling out the form or skipping it) will show a spinner while the database and search index churn away:

![submit-form](https://user-images.githubusercontent.com/14170650/30883204-0db29548-a2d1-11e7-9684-0bd08b0f70e5.png)

We'll talk bigger picture priorities for this issue on Thursday. Deescalating the priority for now.

**Comment by tlongers** [comment]
Stale issue; closing.
