### ISSUE TITLE
Restrict unit classifications to preset options

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#233]
This gives me 500 error:

In ```~/en/membershipperson/create/```, open the typeahead for ```Role```:

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/30694653-cb282a92-9ecc-11e7-95e8-f091661daf2a.png)

Enter an arbitrary value:

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/30694675-f0b9aea2-9ecc-11e7-8ee4-189067b81697.png)

Confirm it:

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/30694664-de4e3120-9ecc-11e7-9204-1aacaf4f0791.png)

Hit ```Next``` after completing the mandatory fields in the form. 

Suggested fix: users should not be able to put arbitrary values in this field, new values should only be editable via the backend.

**Comment by jeancochrane** [comment]
Options have been restricted to existing values:

![rolerank](https://user-images.githubusercontent.com/14170650/30790127-b30ff2f0-a16f-11e7-8879-075664782bfd.png)

Let me know if you notice any other search-based inputs that allow you to use arbitrary data. (I noticed that division IDs had this property while I was implementing the autofill feature for people/units, so I went ahead and fixed it.) One that I just saw while confirming this fix: should users be able to define arbitrary unit classifications?

**Comment by tlongers** [comment]
> should users be able to define arbitrary unit classifications?

No. Selection should be restricted to existing values, and new values added by admin users through ```~/admin```.

**Comment by jeancochrane** [comment]
Great. Updated the title to reflect the remaining work.

**Comment by jeancochrane** [comment]
Fixed in [5fcafbb](https://github.com/security-force-monitor/sfm-cms/commit/5fcafbb399470a81d6b6d98629c06c521127485f).
