### ISSUE TITLE
Interaction question re: memberships

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#236]
@jeancochrane At the stage of entering memberships, if I don't want to add any I can see two options:
 * Remove both relationships and hit "next"
 * Hit skip

Do they both have the same effect of committing nothing to the dataset?

<img width="816" alt="sfm_dashboard" src="https://user-images.githubusercontent.com/2115933/30736979-c59cdaae-9f7c-11e7-89df-2b81c558e958.png">

**Comment by jeancochrane** [comment]
We wrote the form such that both of those strategies should accomplish the same thing, but I'm curious whether the form validation interferes at all in the case where you remove both memberships. I'll give it a try to confirm.

**Comment by jeancochrane** [comment]
Worked fine when I tested it! "Skip" is definitely the safer route to take, since it bypasses all of the form submission logic entirely, but "Next" with both forms deleted won't add bogus values to the database.
