### ISSUE TITLE
Recursive queries take way too long for detail views

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#239]
Detail views like `en/organization/detail/7` retrieve some pretty huge recursive queries from the database in the two functions that generate the org chart (`get_command_edges` and `get_command_nodes`), resulting in a request/response cycle that can take >30s. IMO, this is unacceptably slow.

Taking that endpoint as an example, the debug toolbar shows that all SQL took 25 seconds to complete; each query took 12 seconds to complete, for a total of 24/25 of the SQL time.

We need to 1) deliver the org chart through an async AJAX request, not a view, and 2) figure out if there's a way to easily improve performance. I suspect that `get_command_edges` and `get_command_nodes` don't both need to run the recursive hierarchy query, for example, and refactoring could save us half the query time.

**Comment by tlongers** [comment]
@jeancochrane is this issue largely about the chart?

**Comment by jeancochrane** [comment]
@tlongers yep, the chart is the main sticking point. If I can't quickly switch to loading it via AJAX, I can disable it temporarily to help you guys continue working.

**Comment by jeancochrane** [comment]
Made some progress refactoring this. The AJAX definitely helps, and it should prevent the bulk of the 502 errors for now, but pages still take way too long to load. @evz, let's talk tomorrow and put together a strategy for minimizing response time.

**Comment by tlongers** [comment]
@jeancochrane did you disable charts for the meantime?

**Comment by jeancochrane** [comment]
@tlongers effectively, I did: we switched to dynamically loading them via AJAX but I forgot to add the new scripts to version control... just pushed them up so the charts are live on the staging site again. Apologies for the mistake!

**Comment by jeancochrane** [comment]
Closing for now, as the main issue we identified here has been addressed. If we decide we want to spend more time further improving loading time, I'll open up a new issue with a different set of diagnostics.
