### ISSUE TITLE
Omnibus Chunk 1 feedback overview

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#242]
# Overview of current issues and feedback, by theme

@jeancochrane this summarises all our feedback so far. I'm dumping it here basically to move all the stuff from our internal feedback over to the main issue tracker more efficiently.  I've grouped it by theme, which I think will make it easier to discuss and make decisions about. 

SHED  indicates issue number raised in internal SFM tracker. CMS #indicates issue in public CMS issue list) 

## Application performance

* Some timeouts due to large queries and a mysterious timeout setting (CMS #240)

### Overall movement through data entry wizard

* Fields should pre-populate with existing data if a person, unit or incident is known to the system (SHED 225, SHED 223, CMS #211)
* Cancel and clear option in data entry wizard: When returning to a data entry form, after hitting back, the data that has been entered but not saved returns (aggressive caching?). There be an option to clear a specific form, or cancel the process completely if the user wants to start afresh.
* When entering and then deleting a value, if the field is empty when "next" or "skip" are hit, the system currently repopulates the field with the deleted entry. It shouldn't do this, but should throw an error?
* Re-order wizard to place geographies after Units (SHED 227, CMS #209) (Question: should entering location for incidents be done through the geo entry page as well?)
* If the user just keeps hitting skip without entering either an organization or a person, the data entry wizard should show the user a message like "Enter a person, organization or incident or press cancel to stop entering data."
* Mandatory fields should be flagged with a red star, and not only flagged on submit if the user fails to enter data in then (SHED 280)
* To complete the data entry process, create an end page that confirms which records were created, provides links to them, and gives the user something to look at whilst the search index is update (CMS #230)

### Design, apperance, interaction

* Darken the placeholder value in all date fields. Currently it is too light to be visible against a white background.
* Values in confidence fields are clipped off on the right hand side when the drop-down is selected. 
* In select boxes like ```rank``` and ```role``` in the ```create person``` dialogue, make it possible to just start typing when the field is focussed, rather than click to have the input field appear. Solution would be make it a multi-value selection box with a restriction to 1 selection. (SHED issue 231)
* Some browser differences in how select2 looks (CMS #229)

#### Data modelling 

* Dealing with discontinuous memberships (CMS #238)
* Linking of sources to only the values that they provide evidence for (CMS #241)

#### General data entry

* Dates should be fuzzy (CMS #114, SHED 234)
* In any ```open-ended``` field change the label ```exact``` to ```exact end``` (SHED 259, CMS #

#### Adding Sources

* When entering a source, the wizard allows you to enter a duplicate Publication if you type a new value that is the same as the old value (see SHED 261). A question for the developers is whether sources are unique objects and to what extent the system can deduplicate them at the current time (SHED 240)
* When adding a source ```Publication country``` should also be mandatory fields (SHED 275)
* Internet archive link is missing from the add source page

#### Adding Persons

* Role and rank controlled vocabularies should not be user editable (see SHED 231, CMS #233)

#### Adding Organizations/units

* Organization classification should be a controlled vocabulary and not user editable (SHED 252)
* When adding a unit, should the "Headquarters" field be moved to Geographies or is there a compelling reason to keep it in the fieldset for adding units? (Shed 251, Shed 250, Shed 253) (also see https://github.com/security-force-monitor/sfm-cms/issues/141#issuecomment-326425246)
* When creating a relationship between units, the "last citation" label needs to be changed to "Last citation date" (SHED 279)
* When creating a relationship between units, the "relationship type" controlled vocabulary should have an option for "administrative" (SHED 258, CMS #193)
* Start date and open ended flags need to be added to the unit memberships dialogue (SHED 281, SHED 206, CMS #141)
* If the user removes the add relationship fieldset in error, they can't get it back without selecting "Go back" (to the add Unit page) and then hitting "Next". The solution is to have an "add relationship button" in this situation (SHED 282)

#### Adding locational information

* Remove confidence fields for Geography type and Unit (SHED 254)
* When entering geography, Division ID is missing, or is this assumed from OSM ID (see SHED 254).
* When entering geography, there is no need to enter confidence values for Unit or Geography type (SHED 254)    
* What is the "Name" field for in the Add Geography step? When entering geography, does OSM ID field grab both the ID and the object Name, or is the name field intended for that purpose? (See SHED 250)
* Site and Exact location should be able to take any type of OSM object (SHED 255)
* Should be able to use latitude and longitude as the basis of a location. Some territories are well covered by OSM and OSM objects are adequate to describe a location; however, many are not and we need to put a pin in a map (SHED 297)
* Optimise the geography page to add multiple geographies quickly to one unit (SHED 228). Question for the developers about the extent of an overhaul that this would represent.

#### Adding Incidents

* An incident should be able to be added without entering data into any of the preceding steps of the data entry wizard
* When adding an incident, we should be able to add a perpetrator classification? (SHED 256)
* We should be able to enter an incident without specifying a perpetrator unit, perpetrator personnel (or perpetrator classifcation, but this field needs to be added). This presently is not possible.
* When adding an incident, we do not need to add confidence scores (SHED 256)

### General
 * In both person and unit records, include a clear indication of the country/division-id that a record is referring to 
 * Tooltips are no longer showing data up on sites in records with maps (SHED 260)
 * If a date is a start or end date (rather than a first or last citation) then this needs to be displayed (SHED 294)
 * Numerous cases of duplicate entries inside record views (CMS #212)
 *  Include some labelling for location that is a bit more clear than current  (SHED 288)
 * Include a minimap in views where a map is present (SHED 213, CMS #170)
 * Wire in sorting to all tables in the site (SHED 214, CMS #132) 
 * Check sidebar content link against page-jump achors in unit and person records (CMS #225)
 * Edit functionality is primitive and needs improvement (CMS #138, SHED 236)
 * Include explanatory text where the Parent Units and Chain of Command charts appear
 * The charts render too small above 4 levels of hierarchy. Solutions to this would be to increase the height of the chart viewport dymamically
 
### Unit/organization records
 
 * In the unit title box add "This unit is classified as:" prior to the list of classifications. Make the list of classifcation look less clickable (or perhaps wire up to a search view for all units sharing that classification) (SHED 287, also affects Person views)
 * In an organization record include a top line indicating the most recent commander for that unit, per the "last seen as" code in person records (SHED 246)
 * In an organziation record, include a table showing the start and end dates of AOOs and sites. A complementary/alternative solution may be to incoude start and end dates of AOOs and sites in map tooltips (SHED 266)
 * In
 * Start and end date are not showing in subsidiaries table in the organization record view (SHED 291)
 * Cut "classifications" from subsidiary table to give some more space (SHED 267)
 * In subsidiary tables, include type of relationship (command, information, administrative) (SHED 212)
 * As non-command position are included in the Command Personnel table, this content section should be renamed Personnel and the following text included as an explanation: "Table showing personnel linked to this unit in command, administrative and other roles" (SHED 289)
 * Where start and end dates of an incident are the same, the text used to indicate the date should state that the incident on that date: "Incident occurred on 12 October 2018" (SHED 283)
* Incidents are missing from the contents sidebar in the Unit record page (SHED 212)

### Persons
 
 * Include a table outlining superior commanders (SHED 245)
 * Where a chart is displayed, the box displaying the present unit should be darkened
 * In the command chart, when a user clicks on the box signifying the current record, nothing should happen. Currently, it links out to an "undefined" page, and throws an error (SHED 285)
 * Introduce some explanatory text below in between the "Chain of command" and the chart itself: "This chart displays the chain of command saying that this is a "line of sight" upwards, calculated at the end point of a posting (SHED 285)
 * Clarify that only relationship tagged as "command" will be used to generate a table or chart (SHED 245)

### Search index contents
 * The index should include any text values that exist in a record, including site name, AOO name, incident description, type of incident (SHED 220, SHED 214, CMS #208)

#### Facets

 * Behaviour of date filters in general facets is not in line with requirements outlined in CMS #140 
 * Add in Country/division-ID as a general facets
 * Location search in general facet should be by OSM object ID not OSM object name, same as how we choose locations in the data entry wizard (adapting SHED 232)
 * In Units facets, add a facet for states or relevant  Admin Level 1 (OSM AL4) for units and incidents (Shed 242) 
 * For Units, add facets for unit Memberships (shed 242)
 * Empty values in any results set should have facets appear for them (CMS #169)

### Results table

 * Wire in suggested searches and guidance on searching when a search results no results (CMS #200, CMS 134)
 * Exact matches should appear at the top of the search results. This is tweak to search relevance.  (SHED 214, 237)
 * What are the options for default sorting, and how can they be made as user friendly as possible? (SHED 214)    
 * Duplicate values displayed in Classification column of search results (and also in record views) (see CMS #212)

## Internationalization

* Date picker is not currently responding to switches in language (CMS #235)
 * Tag the "th" date suffix string in incident pages as translatable  (CMS #227)

**Comment by jeancochrane** [comment]
This is really awesome, thanks for putting everything together @tlongers. Excited to prioritize and jump into it.

**Comment by tlongers** [comment]
Updated to add note about use of lat/lon as a basis of locations.

**Comment by tlongers** [comment]
Updated to add old issue with start/end dates on filters (see #140)

**Comment by tlongers** [comment]
Updated to add requirement to show if date is start/end rather than first/last.

**Comment by jeancochrane** [comment]
@tlongers May I do the honors of closing this?

**Comment by tlongers** [comment]
3... 2... 1... [     ]

**Comment by jeancochrane** [comment]
Closed!
