### ISSUE TITLE
Roll back to previous versions

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#25]
If a user really messes something up, we ought to leverage the versioning stuff that we have built in to allow an admin to roll it back.

**Comment by tlongers** [comment]
Same with deleted entries (when the function is implemented). Is delete really delete or is there a restore/recovery step in case of error? Related: is there a role/permissions admin in the spec for this? (possibly a dumb qn).

**Comment by evz** [comment]
We get an admin interface for free with the web framework that the site is built on. There is a rudimentary rollback and recovery abilities built into it that should make this possible at least for the initial version of the site.

@tlongers Using the same admin interface, we can recover deleted things and there are some role and permissions type features that we can leverage (although depending on how extensively we want to leverage them throughout the site, it could require some work).

**Comment by tlongers** [comment]
Versioning implemented in Aug 2018. Closing.
