### ISSUE TITLE
Implement consistent labelling on any tables with dates

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#251]
Where dates are included in tables anywhere in the platform, the labels "First cited" and "Last cited" should be consistent. Currently, a mix of labels are in use.

From a person record:

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/31009422-480a9fda-a4ff-11e7-9655-ee913c124512.png)

From a unit record:

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/31009447-64d8a99a-a4ff-11e7-9243-9f2354df62cb.png)

**Comment by jeancochrane** [comment]
Done in https://github.com/security-force-monitor/sfm-cms/commit/f32cb74db4fe7af4a7aef5b9b8f8cb2f4fd1abac.
