### ISSUE TITLE
In incidents clarify the labelling for location information

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#252]
Text beneath the map is a bit orphaned -  needs some explanation/labelling/styling: 

<img width="439" alt="sfm_dashboard" src="https://user-images.githubusercontent.com/2115933/30743541-feee06de-9f95-11e7-9fad-1b17809f01d9.png">

**Comment by jeancochrane** [comment]
I'm going with "This location took place in {{ location }}".
