### ISSUE TITLE
Chain of Command chart size

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#254]
The charts render too small above 4 levels of hierarchy. Solutions to this?

-  increase the height of the chart viewport dynamically?
- introduce zoom controls?
- slippy map?

**Comment by jeancochrane** [comment]
Went with the simplest out-of-the-box solution and added zoom/slippy to the charts in https://github.com/security-force-monitor/sfm-cms/commit/42fe3a13d2a117c82cc97dcc5d2603b3f84ae0b1. I think we'll want to revisit this as we start to get more and more complicated hierarchies, however.

**Comment by tlongers** [comment]
Good call. We'll see how people respond to it.
