### ISSUE TITLE
Accented characters shouldn't restrict search results / ASCII folding implementation

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#256]
Accented characters are treated exactly in search terms. Searching for ```Juárez``` should show records that include ```Juarez```.  [SOLR's ASCII Folding Filter](https://lucene.apache.org/solr/guide/6_6/filter-descriptions.html#FilterDescriptions-ASCIIFoldingFilter) seems to deal with this.

**Comment by jeancochrane** [comment]
Pulled this in via https://github.com/security-force-monitor/sfm-cms/commit/288ecddd67f0131614b9a8efa138cdb94c860090! Encoding issues are tricky, so let me know if you notice anything else suspicious.
