### ISSUE TITLE
Unit record view - display current or most recent commander

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#257]
Would be useful to have a "Last known commander" topline containing info about the most recent commander, similar to the one atop  person records:

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/30239005-e019b636-954a-11e7-9aea-792512ee6dc9.png)

**Comment by jeancochrane** [comment]
Pushing this off from Chunk 1, in accordance with our convo last Thursday.

**Comment by tlongers** [comment]
No need, I think.
