### ISSUE TITLE
Org records  - add site and AOO table including first/last cited dates

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#258]
Areas of Operation and Sites have no data tables like Memberships and other fields do in the User View.

Right now the AOOs and Sites look like they are "forever" there is no indication of any change - and the user has to click on the maps to have a tooltip pop up and understand what they are looking at. 

I think having a table below with the information would be great. 

Even better would be a flickity chart showing AOOs and sites at different points in time, but that can wait :)

**Comment by tlongers** [comment]
This is nice feature, thanks. A niggle:
- duplicated site results:` ~/organization/detail/183/`

**Comment by jeancochrane** [comment]
This was an importer error that I fixed in https://github.com/security-force-monitor/sfm-cms/commit/564726401f5c12958bdcd493c3f7aa09e4295073. It'll stay incorrect until I redo the import on the servers.

Mind if I go ahead with that this morning @tlongers?

**Comment by tlongers** [comment]
@jeancochrane sorry I didn't act on this quickly enough. I think TW needs until Thurs with the dataset. @tonysecurityforcemonitor ?

**Comment by jeancochrane** [comment]
No worries at all. I can wait until the next batch of data is ready to do another import. Closing this for now then, to reflect the current status of the code.
