### ISSUE TITLE
unit record - updates to subsidiaries table

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#259]
(Edited)

First/last citations  are not showing in subsidiaries table in the unit record view:

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/31011004-b2ff577c-a504-11e7-9c7a-5ea64ba1d447.png)

Also replace ```classifications``` with ```type of relationship``` in this table.

**Comment by tonysecurityforcemonitor** [comment]
@tlongers - I was thinking about suggesting removing aliases - what do you think?

**Comment by tlongers** [comment]
@tonysecurityforcemonitor it can get rather busy in the ```aliases``` field for sure, but the range of names may catch  someone's eye in a way that our normalised name might now. Suggest leaving it.

**Comment by tonysecurityforcemonitor** [comment]
@tlongers - ok sounds good :)

**Comment by jeancochrane** [comment]
I fixed this in https://github.com/security-force-monitor/sfm-cms/commit/a381a652ea0effaaf54d5eb173c82039529c7468.
