### ISSUE TITLE
Add facet on states or relevant Admin Level 1 (OSM AL4) for units and incidents

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#269]
In Units facets, add a facet for states or relevant Admin Level 1 (OSM AL4) for units and incidents. At root this is the text contained in ```ADMIN1 Geoname``` anywhere in the dataset. 

For extra points: the labelling of the facet may need to change depending on the country, however, as ADMIN1 will have a different name in different countries.

**Comment by jeancochrane** [comment]
Admin level 1 facet added in https://github.com/security-force-monitor/sfm-cms/commit/98dabcff1d85263a3aec67d3e9066b133339f95d.

How does "Place" sound as a generic title for ADMIN1, for now? Could be a nice opportunity for a callout to the docs.

**Comment by tlongers** [comment]
I'm fine with place and a callout to docs.We've got quite a lot of geo terms floating around( `location`, `site`, `area of operation`, `headquarters`) we don't have much wiggle room without adopting a more formal terminology (like `admin1`, which I don't want to do).  This facet looks like it may get lengthy (and hence present a usability problem).  Short of adding a filter, truncating it or tying its appearance to the setting of `country` I don't know how to deal with it.

**Comment by jeancochrane** [comment]
Let's revisit this when the big chunk of data comes in and see if it's hard to use. Closing for now, since there's not a clear direction to take at this point.
