### ISSUE TITLE
Search results - add facets for unit Memberships 

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#271]
For Units, add facets for unit Memberships.

**Comment by jeancochrane** [comment]
Do we want to facet on parent units, too?

**Comment by jeancochrane** [comment]
Membership facets added in https://github.com/security-force-monitor/sfm-cms/commit/96751b2ee42a34762692d07c346adee576ec26d3.

**Comment by tlongers** [comment]
Yes, facet on `parent` too.
