### ISSUE TITLE
Search results - improve relevance and ordering

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#272]
Exact matches should appear at the top of the search results. What are the most user friendly default sorts to include too?

**Comment by jeancochrane** [comment]
Here's a quick sketch of a way we might rank fields to improve recall:

### Personnel

Name > Aliases > (Rank = Role = Title) > Member unit > Location

####  Units

Name > Aliases > Parent > Classification > Location

#### Incidents

Description > Violation type > Perpetrators > Perpetrator classification

Thoughts? We also might want to think about what the default "search" should be when the user enters the search via a tab (Personnel, Unit, Violation, or just searching for a blank term). Right now we're grabbing everything with a wildcard (*) but that's a nice and easy opportunity to show am especially dynamic view.

We also haven't updated the tables in a while, and they don't show all the data that we facet on (e.g. Role is missing from the Personnel table). Should I open up a separate issue to update those tables?

**Comment by tlongers** [comment]
>rank fields to improve recall:

Ranking inside the SOLR magic box?

> what the default "search" should be when the user enters the search via a tab

Grab everything, show everything :)

>Should I open up a separate issue to update those tables?

Quick refinement to that question: should facets mirror table columns? I lean towards "no",  as I think have a search results table column for all  the different dimensions of our content would clutter it.  What's your take on it, and conceptually how to decide what goes in a column heading and what goes in a facet?

**Comment by jeancochrane** [comment]
> Ranking inside the SOLR magic box?

Yup! One of the main strategies for improving recall/relevance in Solr is adjusting the weights for the different fields that are searched. Right now all fields are weighted the same, so e.g. when you search "XI Region Militar" Solr will assign an equivalent score to the entity named "XI Region Militar" as well as an entity whose parent is "XI Region Militar". While in this case both entities are definitely relevant, my assumption is that the user will find it more natural to see the entity where `Name` matches first, before seeing the entity where `Parent` matches.

> Grab everything, show everything :)

Sounds good to me!

> Should facets mirror table columns?

This is a good question. I think including all facets would definitely clutter things. What I'm wondering about is whether users will be confused by faceted elements that don't correspond to information in the table. E.g. right now when you facet on "Role" for personnel, you get a table in response that doesn't contain that information anywhere:

![screenshot from 2017-10-03 09-28-27](https://user-images.githubusercontent.com/14170650/31130538-4dc361a2-a81d-11e7-8747-f8837276828f.png)

I could see a simple fix in cases like these (location/country is similar) where we merge rank/role/title into one table cell, kind of like we do in "Last seen as" on the person detail page:

![rank-role](https://user-images.githubusercontent.com/14170650/31130699-bcb2d976-a81d-11e7-8da3-09ce5bdb99c8.png)

But also maybe users won't be confused by this at all, and it's a question we should punt to the next round of testing?

**Comment by tlongers** [comment]
### Weighting

I like your suggestions, I'd add location to the `incident` weighting.

Description > Violation type > __location__ > Perpetrators > Perpetrator classification 

Wire it in and we'll test it out.

### Faceting

We haven't asked this question specifically in round 1 research - only a few interviewees found a prominently-placed facets that controlled the map display, but most were happy when we pointed it out! My best guess is that users will expect the table and the facets to the same and will take their ideas about what they facet on from the table headings. I've seen interfaces where there is no overlap between the results and the facet options (eg. [BBC Recipe search](http://www.bbc.co.uk/food/recipes/)) but that's a more familiar domain and content set than ours is. We have some more facets to add  ( #169 #271 #269) so I wonder how we can balance this nicely?  So for now we must _at least_ ensure all table columns have corresponding facets, but let's not worry about adding in additional ones. Sound reasonable?

Not for this chunk, but if we overhauled the facets to place them atop the results (per [OpenGazettes](http://opengazettes.com/search#) we'd get some more space to play with. We could also consider a card layout for the results, which allows a bit more flexibility in how we display results (per [360 GrantNav](http://grantnav.threesixtygiving.org/)).

**Comment by tlongers** [comment]
To clarify:

> but let's not worry about adding in additional ones. Sound reasonable?

I mean, we can add in the additional ones without having a matching column heading.

**Comment by jeancochrane** [comment]
Sounds great to me @tlongers, thanks for the clarification!

**Comment by tlongers** [comment]
This seems done:
- re wiring in `incident:location` into SOLR: it's suggesting entries from `location` so I guess it's in there (correct?)
- re: facets - the range of geographical ones added
- Search relevance: it's passing the "XI" test nicely.
Ready to close?

**Comment by jeancochrane** [comment]
Ready as I'll ever be! Closing.
