### ISSUE TITLE
Refinements to search/confidence citations

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#273]
@jeancochrane based on yesterday's chat, here's some thoughts about seeing if the popover can carry the confidence rating as well as the details of the sources. Not attached to these ideas, but throwing them out there. 

How it looks in a table...

![whowasincommand_mockups_-_in-table_ _moqups_](https://user-images.githubusercontent.com/2115933/31016765-e5a88d74-a51d-11e7-9548-ea9909d917db.png)

For added refinement, the markers could be hidden until mouseover.

What pop-over might look like...

![tooltips_source_conf](https://user-images.githubusercontent.com/2115933/31016516-efb2eb3a-a51c-11e7-8806-409dbfe623ff.png)

Behaviour-wise I'd expect the pop-over to have the following features:
- show the complete first citation
- live urls, wrapped
- include a link to the help page
- have a selectable content 
- disappear when clicking anywhere else (for accessibility they should also have a "X" button to close)

What's your thoughts on it Jean?

**Comment by jeancochrane** [comment]
Looks lovely to me. Thanks for the great sketches @tlongers! I think this should be a fast change that will dramatically improve the citations.

**Comment by jeancochrane** [comment]
These changes are all in as of https://github.com/security-force-monitor/sfm-cms/commit/c56b9b69c51db1bad2950fdf01b5cafe943a4f5c with the exception of the help widget, which is waiting on #278. I decided to go with the hide-until-hover strategy, and I think it's a lot easier to use! If you notice bugs, feel free to reopen this.

**Comment by tlongers** [comment]
Gotta say that this rocks.
