### ISSUE TITLE
Search results page pagination + number of search results to show

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#275]
Another straggler from #132. Wire in pagination + number of results to display on search results pages.

**Comment by jeancochrane** [comment]
Better pagination is in as of https://github.com/security-force-monitor/sfm-cms/commit/219d735c527d7d89433455e4852c66101529b636:

![pagination](https://user-images.githubusercontent.com/14170650/31236575-14e456e0-a9ba-11e7-9e06-22db82fe3480.png)

 Give it a whirl and let me know how it feels.

**Comment by tlongers** [comment]
Neat; works as expected. The current default of `5` works well in the case where there are results from more than one entity set. I suspect where someone is searching in only a single  entity type, the first click they will make is to display more results. We'll see if people want more or fewer results by default though.
