### ISSUE TITLE
Make sure fuzzy dates work for general date search

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#277]
We need to:

1) Make sure the search is capable of working with fuzzy dates
2) Make it clear to users how they should search for fuzzy dates

**Comment by tlongers** [comment]
1's in your court; 2 we can deal with in FAQ.

**Comment by jeancochrane** [comment]
Fuzzy dates are in in https://github.com/security-force-monitor/sfm-cms/commit/af033910ec8ece955a911174868eedd0b608888e! They won't really be usable until #140 comes in, however.

For now, we'll accept dates in any of these formats:

```
2015
2015-01
2015-01-01
1/2015
1/1/2015
```

There are definitely ways we could improve parsing to make the datepicker more friendly, but I'm curious to see how people use it first.

Leaving this open until the FAQ is done and we've added a link to it to the datepicker.

**Comment by jeancochrane** [comment]
Actually, I'm closing; the remaining work on my end is encapsulated in #278.
