### ISSUE TITLE
basic download option

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#279]
Initial simple "take data home" options to solicit initial feedback:
- CSV for search results
- printable view of record views including sources/confidence levels

**Comment by jeancochrane** [comment]
Merged in a basic download option for searches and detail views in https://github.com/security-force-monitor/sfm-cms/commit/8d865d1701201ef462ffb227f81bbbb89e204ade.

After reading over https://github.com/security-force-monitor/sfm-ui/issues/44 and thinking about it for a while, I decided to go with a download format that might be a little confusing initially, but that maximizes utility for advanced users. Downloading a search (or an individual record) will net you a zip archive with a bunch of spreadsheets, one for each sourced attribute of the entities you want to see. Users with some spreadsheet skills who are familiar with the relational way of doing things should be able to join on the unique ID columns to answer a whole bunch of questions.

Curious to hear what you all think!

**Comment by tlongers** [comment]
Excited to see it _but_ getting 500 errors when using the download button: 
~en/download/?entity_type=Organization&download_etype=Organization
~en/download/?download_etype=Organization&entity_id=396f0a0f-ccf9-4c29-86b3-5723a0a90b06

**Comment by jeancochrane** [comment]
Oops, totally forgot to queue up the migration that makes this possible. Give it a try now @tlongers.

**Comment by tlongers** [comment]
This is a good start, and I think a practical compromise that sets us up for a productive to-and-fro with advanced users about what they actually need in this function.  

## CSV download of person data

This is what I get from `~en/download/?download_etype=Person&entity_id=dc026d76-6d38-444a-b7ec-a59424891858` which is the current record of `Gerardo Rubén Serrano Herrera`:

person_alias.csv
  1: person_id
  2: alias
  3: alias_confidence
  4: source_id

person_firstciteddate.csv
  1: person_id
  2: membership_id
  3: first_cited_date
  4: real_start_date
  5: first_cited_date_confidence
  6: source_id

person_lastciteddate.csv
  1: person_id
  2: membership_id
  3: last_cited_date
  4: real_end_date
  5: last_cited_date_confidence
  6: source_id

person_membership.csv
  1: membership_id
  2: person_id
  3: organization_id
  4: organization_id_confidence
  5: source_id

person_name.csv
  1: person_id
  2: name
  3: name_confidence
  4: source_id

person_rank.csv
  1: person_id
  2: membership_id
  3: rank
  4: rank_confidence
  5: source_id

person_role.csv
  1: person_id
  2: membership_id
  3: role
  4: role_confidence
  5: source_id

person_title.csv
  1: person_id
  2: membership_id
  3: title
  4: title_confidence
  5: source_id

sources.csv
  1: id
  2: title
  3: archive_url
  4: published_on
  5: source_url
  6: publication_id
  7: user_id
  8: date_added
  9: date_updated
 10: accessed_on
 11: page_number

# CSV download of organization data

This is what I get from `~en/download/?download_etype=Organization&entity_id=be3b419d-8008-4826-880f-bfd90f916a8b` , the current record for `XI Región Militar`:

organization_alias.csv
  1: organization_id
  2: alias
  3: alias_confidence
  4: source_id

organization_classification.csv
  1: organization_id
  2: classification
  3: classification_confidence
  4: source_id

organization_firstciteddate.csv
  1: organization_id
  2: first_cited_date
  3: real_start_date
  4: first_cited_date_confidence
  5: source_id

organization_lastciteddate.csv
  1: organization_id
  2: last_cited_date
  3: assume_end_date
  4: last_cited_date_confidence
  5: source_id

organization_membership.csv
  1: membership_id
  2: member_organization_id
  3: organization_id
  4: membership_confidence
  5: source_id

organization_name.csv
  1: organization_id
  2: name
  3: name_confidence
  4: source_id

organization_parent.csv
  1: composition_id
  2: organization_id
  3: parent_id
  4: composition_confidence
  5: source_id

organization_site_name.csv
  1: organization_id
  2: emplacement_id
  3: site_name
  4: site_name_confidence
  5: source_id

sources.csv
  1: id
  2: title
  3: archive_url
  4: published_on
  5: source_url
  6: publication_id
  7: user_id
  8: date_added
  9: date_updated
 10: accessed_on
 11: page_number

## Refinements

I think it will be a little tricky for a user to stitch this all together, but that's something we can help with. There are some bits of essential content missing:

- when downloading data from a person, include an `organization_name.csv` with the same structure as `person_name.csv`.
- reciprocally, when downloading information about an organisation include a 'person_memberships.csv' which includes the list of persons connected to that organisations
- create an `organization_aoo.csv` listing out an organization's `Areas of Operation`, including OSM object names and ID numbers
- in `organization_site_name.csv` includes the OSM object name but should include ID number as well.

Here are the refinements that I think would be helpful to user regarding longer term use of the downloaded information. Let's discuss what's possible in this this time round:

- include the person or organization name, and increase the granularity of the UTC timestamp in the archive filename. I expect people will make multiple downloads daily and it will aid in keep tabs on downloads! (eg. `Gerardo_Rubén_Serrano_Herrera_wwic_download_20171016105502.zip`)
- for each csv add a first column  labelled `download_timestamp`, including the same timestamp, and a column called `wwic_url` including the URL from which they downloaded it.
- `sources.csv` contains all sources in the dataset. Ideally, it should only be those sources that are referenced within the context of this record.
- in `sources.csv` remove fields that are tied to the not-yet-activated data entry wizard (`date_added`, `accessed_on`, `page_number`) or that are system admin information (`date_updated`,  `user_id`). 
- definitely not for this release but  offering an option to dump it into a single spreadsheet rather than a collection of CSVs might give people a headstart.

**Comment by tlongers** [comment]
In testing the download on the search results page that has no search terms or facets I'm getting a 500 at:
~en/download/?q=&entity_type=Person&download_etype=Person 
~en/download/?q=&entity_type=Organization&download_etype=Organization

The download button on the `incidents` search results isn't pointing at the download function yet.

**Comment by jeancochrane** [comment]
Fixed the bug where downloads weren't showing up. Pushing Tom's detailed feedback off from Chunk 1, in accordance with our convo last Thursday.

**Comment by tlongers** [comment]
Yep, we'll refine the download process later - what we have is a great start!

**Comment by tlongers** [comment]
Retaining issue.

**Comment by tlongers** [comment]
Closing issue.
