### ISSUE TITLE
Add translation tags in citation pop-overs

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#281]
The following strings in the citation pop-over need tagging for translation:

- "Published on"
- "Archive URL"
- "Date added"
- "Date updated"

**Comment by jeancochrane** [comment]
The [code for the citation tag](https://github.com/security-force-monitor/sfm-cms/blob/master/sfm_pc/templatetags/citations.py#L28-L31) indicates that these have been tagged for translation, so I think you guys should be able to translate the strings. If I'm wrong and for some reason they're not showing up in the Rosetta interface, feel free to reopen and I'll take a closer look.
