### ISSUE TITLE
Translation tags on download buttons

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#287]
On search results view, unit record and person records.
![sfm_dashboard](https://user-images.githubusercontent.com/2115933/31168237-8bcb8e46-a8ec-11e7-9628-9fd06d7e0022.png)

**Comment by jeancochrane** [comment]
Ugh, and here I thought I had gotten good at tagging interface elements. Thanks for catching this.

**Comment by jeancochrane** [comment]
Looks like I did tag these ([units](https://github.com/security-force-monitor/sfm-cms/blob/master/templates/organization/detail.html#L19), [personnel](https://github.com/security-force-monitor/sfm-cms/blob/master/templates/person/detail.html#L14)). Are they not visible in the translation interface?

**Comment by tlongers** [comment]
Uff -  sorry. My bad Jean. We just hadn't translated them :/

**Comment by jeancochrane** [comment]
No worries @tlongers! Closing for now, then.
