### ISSUE TITLE
Collapse filter boxes by default

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#289]
On small screens, the search results page gets overwhelmed by the filter boxes. You have to scroll for more than a page to get to the results:

![small-screens-search](https://user-images.githubusercontent.com/14170650/31259071-9c9bc5ce-aa09-11e7-860d-926a2a0a0992.png)

I'd like to make these collapsible elements (like the facets) and collapse most of them by default. (We do this on Chicago Councilmatic, for example: https://chicago.councilmatic.org/search/) It might make sense to leave "I'm looking for..." open and collapse the rest, unless the user has selected a facet. Seem reasonable to you @tlongers?

**Comment by tlongers** [comment]
Agreed, leave "I'm looking for" and collapse the remaining filters per councilmatic. One extra step might be useful, but it's optional - which is to collapse the complete filterset into a "Add more filters"  thing.

**Comment by tlongers** [comment]
This works nicely I think. Per the Councilmatic design pattern, though, when a filter value is selected, it should be visible to the user even though the filters are collapsed:
![search_legislation_-_chicago_councilmatic](https://user-images.githubusercontent.com/2115933/31372504-eca3a4ce-ad8d-11e7-83da-ea7dbf05558c.png)

**Comment by jeancochrane** [comment]
Yup, that's pretty important functionality. Added it in https://github.com/security-force-monitor/sfm-cms/commit/ba6545091b4104f5d394d8af18d841fdd6f19fab.
