### ISSUE TITLE
Server errors with some punctuation characters

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#293]
I'm getting 500 errors when searching with any of these individual characters:`!{["~-+()^:`

**Comment by tlongers** [comment]
`/` still causes an error if entered alone or as part of a query.

**Comment by jeancochrane** [comment]
Went ahead and did what I should have done last week, which was [look up the list of special characters in the Solr standard parser.](http://lucene.apache.org/core/6_5_1/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#Escaping_Special_Characters) Done in https://github.com/security-force-monitor/sfm-cms/commit/9705387fb824271847edc7ed6cfd603c0c66a41b.
