### ISSUE TITLE
Excessive writes to changelog 

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#294]
The changelog on `alias` for `~/en/organization/detail/2/#changelog` has been written to well over 100 times. Seems... excessive.

**Comment by tlongers** [comment]
A friendly tester also noticed this after exploring the mysterious accordions in the Changelog.

**Comment by jeancochrane** [comment]
Similar to #258, I fixed this in the importer but it'll remain an issue until the next import. I'll close it once the servers reflect the new import.

**Comment by jeancochrane** [comment]
Closing per my decision in #258.
