### ISSUE TITLE
csrftoken cookie question

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#301]
For users that are not logged in, will a csrf token be set?

**Comment by jeancochrane** [comment]
Looking at the code, I'm fairly confident we only set a CSRF token for logged in users. @evz should confirm this, however.

**Comment by jeancochrane** [comment]
@tlongers I confirmed this with @evz:

We only set a CSRF token when a user interacts with a form, either through the data entry wizard or through the login page. So we won't set a token for anonymous users.
