### ISSUE TITLE
No record data in staging site

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#303]
To check fixes, we'll need some data in there :)

**Comment by jeancochrane** [comment]
Oops, looks like my import job died last night! We'll give it more memory to work with, but it'll still take a couple hours to finish the import. Maybe I should set the production site to deploy off of the master branch till it finishes, so that you can check fixes?

**Comment by jeancochrane** [comment]
Either way, I'm taking a break for lunch now, so I'll deploy all of the fixes I made this morning to production.

**Comment by jeancochrane** [comment]
Production site has the latest commits as of https://github.com/security-force-monitor/sfm-cms/commit/b78b2bbbfef42e393a6716b1739dd61e7152f118, and I'm running the import again on the staging server. Will close this once the staging server is back up and running.

**Comment by jeancochrane** [comment]
Import is finally done! The staging server has data again. Closing.
