### ISSUE TITLE
No geodata displaying for Egypt records

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#309]
On the production site, we'd noticed that geodata on Egypt records was displaying erraticly - some correct, some with `areas` in the Atlantic. In both staging and production no geodata is not displaying for these records.

**Comment by jeancochrane** [comment]
Huh, this is really weird. Thanks for flagging it! Can you drop a link to a page or two where you're seeing missing information?

For debugging, here's a spot I found that showed up in the Atlantic:

`~/en/organization/detail/77/`

**Comment by tlongers** [comment]
~en/organization/detail/2/
Actually, wondering if it had geodata in the first place?

**Comment by jeancochrane** [comment]
Seems from the sheet that we only have `admin level 1` data for that organization, along with a lot of the other locations in Egypt. Looking at the importer code, it seems like we skip making emplacements/associations if we don't have `GeonamesName` or `GeonamesID`, even if admin level 1/2 data exists.

Do we want to update the importer code, or update the data in the sheets?

**Comment by tlongers** [comment]
@tonysecurityforcemonitor is better placed to answer that.

**Comment by tonysecurityforcemonitor** [comment]
@jeancochrane I don't think we can update the sheets without some digging there... in general I'd like the system to be able to display a Site when all we have is the `admin level 1` as sometimes that's all we'll have, but it's not a "must have now" issue. So if it's easier to punt to Chunk 2 that's fine by me!

**Comment by jeancochrane** [comment]
Cool! Removing this from the "Chunk 1" milestone then.

**Comment by jeancochrane** [comment]
I suspect many of the geo problems related to Sites will be fixed when we do the next import following https://github.com/security-force-monitor/sfm-cms/issues/318#issuecomment-337709193.

**Comment by tlongers** [comment]
Ok, I guess with #318 it's time for the importer to do its magic :)

**Comment by tlongers** [comment]
Resolved. Closing.
