### ISSUE TITLE
Qn about fields that expect URL input

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#31]
On /create-source there are two fields for URL and Archive URL. Does the input expect protocol (e.g. https://[...]) or will it populate it automatically on submit?

**Comment by evz** [comment]
Looks like that is the case. The only issue that might generate is if the site in question only supports https since when you don't put the protocol into the form field, it assumes http. If you're OK with that, go ahead and close this issue.

**Comment by tlongers** [comment]
Still not clear if it does expect you to put protocol in.

**Comment by evz** [comment]
Sorry, it does not expect you to put in the protocol. But, if you do not, it assumes that you want `http://` as opposed to `https://`. This should only be a problem if a website is only configured to respond to requests for pages using HTTPS. If a user does put in the protocol, it also does the right thing and just stores the URL as it was typed into the form field. So, to be safe, I'd say that you should have users just put in the entire URL (including protocol).

**Comment by evz** [comment]
Closing since this seems resolved.
