### ISSUE TITLE
Citation popovers should persist until cancelled

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#310]
On desktop views, citation popovers disappear when clicked on. They should persist until user clicks away (or, better for accessibility, include a "x" in top right corner)

**Comment by jeancochrane** [comment]
Related to #273.

**Comment by jeancochrane** [comment]
Done as part of https://github.com/security-force-monitor/sfm-cms/commit/c56b9b69c51db1bad2950fdf01b5cafe943a4f5c.
