### ISSUE TITLE
Remove citation popovers from all but one value for fields with multiple values

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#313]
Things are getting a little busy on some tables:

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/31576029-d4427ec2-b0ea-11e7-912f-1794876247d5.png)

We can do something simple to unclutter these views. Where `alias` and `classification` fields are displayed, it is not necessary to have a citation popover on every value. For these fields, sources do not refer to individual values in the field but to the whole group of values. A single citation popover will suffice - this could be positioned before the first or after the last value in the series.

**Comment by tlongers** [comment]
Related to #273

**Comment by jeancochrane** [comment]
After adding hide-until-hover functionality in https://github.com/security-force-monitor/sfm-cms/commit/c56b9b69c51db1bad2950fdf01b5cafe943a4f5c I'm of the opinion that this is no longer a problem. We still see lots of citations when you hover over these fields, but it doesn't seem so intrusive to me now that they're hidden by default. Plus, given that we'll be creating editing functionality for alias/classification fields in Chunk 2 such that individual alias/classification values for a given entity might have multiple sources, it seems like in the long term this is the correct behavior.

@tlongers if you disagree, feel free to reopen! This wouldn't be a huge change to make.

**Comment by tlongers** [comment]
Agreed, the hide-until-hover along with the refinement of the popover to include confidence makes this much less of an issue.
