### ISSUE TITLE
OSM map coordinate reference system question EPSG:3857

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#316]
We using  `EPSG:3857`?

**Comment by jeancochrane** [comment]
We're using `4326`, since it's the default for lat/lng in `osm2pgsql` (which is the conversion tool we use to pull in OSM data) and the general web mapping default. Should we be using `3857` instead?

**Comment by tlongers** [comment]
No, that's fine. Needed it for documention.
