### ISSUE TITLE
Navigating through the data entry process

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#32]
I see ```skip``` and ```continue``` options to move the data entry workflow forward.  I'd expect a ```Go back a step``` or ```Previous step``` button. Prefer this to using the browser's back button. Guess the question is "why would I go back a page?" Likely because I've messed something up, or want to double-check.

**Comment by tlongers** [comment]
See #19 too.

**Comment by tonysecurityforcemonitor** [comment]
+1 on this - when I was entering a new source I realized that I messed something up - but there wasn't a way to go back a screen

**Comment by evz** [comment]
Closed with a5086d19c9ca1095e5bf9ff8f1c1725fcd246ec4
