### ISSUE TITLE
Start date and end date facets throwing interal server error

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#320]
Issue is on all entity types; examples below from `incidents`. 

Incident / Start date:
`~search/?Violation_sort=start_date_dt_desc&entity_type=Violation&selected_facets=violation_start_date_dt_exact%3A2007-01-01T00%3A00%3A00Z`

Incident / End date:
`~search/?Violation_sort=start_date_dt_desc&entity_type=Violation&selected_facets=violation_end_date_dt_exact%3A2010-01-01T00%3A00%3A00Z`

**Comment by jeancochrane** [comment]
One of many reasons that `start` is a terrible name for a variable: you'll probably wind up using it more than once in any given code block. Fixed the conflict in https://github.com/security-force-monitor/sfm-cms/commits/master.

**Comment by tlongers** [comment]
Ah the naming of things challenge :( Thanks Jean.
