### ISSUE TITLE
Downward recursion in calculations of subordinates

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#325]
@jeancochrane Is the subordinates section of a person record for person A calculated on the basis of units one step down from any unit commanded by person A at any time?

**Comment by jeancochrane** [comment]
Yup! For that table, we only look at units one step down in the command chain. I think this is what you were saying, but to be sure: we also do some filtering to make sure that the subordinate commander's posting dates line up with the dates of the superior commander.

**Comment by tlongers** [comment]
Got it; thanks Jean.
