### ISSUE TITLE
Remove organisation button does not remove field grouping

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#33]
1. On ```/create-orgs``` there is a blue button called ```Add organization+```, which magics a new field group onto the page.
2. After doing so, there is an orange button called ```Remove organization-```. Nothing happens when I click on this. 

Expected behaviour would be that ```Remove organization``` removes the field group if all fields in it are empty. If any field is populated I would expect to be asked to confirm the removal of the field group.

**Comment by evz** [comment]
Closed with 58bd7c123034b9a10391ede03afc07fde9dcc932
