### ISSUE TITLE
First/Last Cited for Sites not displaying any data

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#333]
@jeancochrane - for example in this org page: https://back.securityforcemonitor.org/en/organization/detail/979/

**Comment by jeancochrane** [comment]
@tonysecurityforcemonitor I must be accessing the attribute incorrectly. This org definitely has first/last cited dates for its emplacements, right?

**Comment by tonysecurityforcemonitor** [comment]
@jeancochrane - yep it does have first/last cited dates.  It seems like it is affecting every unit - I haven't seen one yet with dates in first/last cited.

**Comment by jeancochrane** [comment]
Oh, the difference that one extra indentation can make... Fixed the importer bug that was causing us to skip emplacement data in https://github.com/security-force-monitor/sfm-cms/commit/134d5d85473670661dd1405d7378aa2266809635, so we'll start seeing start/end dates for sites once the next import goes in.
