### ISSUE TITLE
Rewire links in Countries page after the new import

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#334]
As @tonysecurityforcemonitor points out, some links from the Countries page have broken during the latest import processes. Let's make sure to update those.

**Comment by tonysecurityforcemonitor** [comment]
Operación Conjunta Chihuahua
https://whowasincommand.com/en/organization/detail/212/

Operation BOYONA
https://whowasincommand.com/en/organization/detail/948/

**Comment by jeancochrane** [comment]
Thanks @tonysecurityforcemonitor!

Checking on the other links, it seems like personnel/incidents return no results for Egypt, meaning the `Browse personnel` and `Browse incidents` links both point to `No results found` pages. Should we remove those links for now?

**Comment by tonysecurityforcemonitor** [comment]
good call on removing those links for Egypt @jeancochrane - yes please do!
