### ISSUE TITLE
Area not displaying properly.. 

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#337]
@jeancochrane 

The data has the correct area - https://www.openstreetmap.org/relation/2455086

But the polygon is not loading properly on the unit page: https://back.securityforcemonitor.org/en/organization/detail/242/

This is the only instance I've seen of this after going through numerous Mexico pages...

**Comment by jeancochrane** [comment]
Unfortunately, I'm pretty confident this is a problem with the OSM data that we imported, so we don't have direct control over it right now. I'll talk it over with @evz and see what our options are, but I think we should remove it from the milestone for this launch.

**Comment by tonysecurityforcemonitor** [comment]
@jeancochrane - that's fine - it's just this one entry - there's always one bad apple! ;)

**Comment by tlongers** [comment]
We can submit a correction - all the admin data on Mexico is built on  top of official shapes from INEGI. If there's been an  import error, it may be easily corrected on OSM itself.

**Comment by tlongers** [comment]
Closing.
