### ISSUE TITLE
Missing help section on unit pages

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#338]
In Unit records, the section called `Member Units`, where it appears, is not wired into translations yet. 

Example: `~en/organization/detail/2/#org-members` (United Nations Missiong in Liberia)

**Comment by jeancochrane** [comment]
Oops, good catch! I'll add it in.

**Comment by tlongers** [comment]
It was my bad; I hadn't actually written the guidance :)
