### ISSUE TITLE
Incident section misaligned

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#339]
Something awry here: `~es/organization/detail/212/`

Content area is pushed right:

<img width="949" alt="whowasincommand" src="https://user-images.githubusercontent.com/2115933/32113934-ceaddd22-bb39-11e7-8516-467ee2e99bff.png">

**Comment by jeancochrane** [comment]
Whoops! Good catch, I was missing a closing tag here.

Not going to push changes up since the importer is still running, but I'll close this once the importer is done.
