### ISSUE TITLE
Updating Person Membership fails 

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#34]
1. On ```/``` choose an existing entry.
2. Expand it using the ```+``` widget and choose any of the ```MembershipPerson``` values listed to navigate to a page which enables you to edit the data (e.g. ```/membershipperson/edit/1/```)
3. Edit the data. Neither the ```Cancel``` nor ```Save``` buttons do anything.

**Comment by tlongers** [comment]
Related to #24 obviously :)

**Comment by evz** [comment]
@tlongers I'm going to close this in favor of #24. I put together a list of Entities that ought to be editable over there which you're welcome to inspect and give feedback on.
