### ISSUE TITLE
Adding facets removes language choice

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#340]
Some issue with the interplay between facets and Il8n here

1. Head to https://whowasincommand.com/es/search/?q=
2. Change the language choice from English to Spanish, which successfully switches the language
3. In General filters, select "Mexico" in from the Country facets 

Outcome is that the Language switches back to English, when it should remain in Spanish.

**Comment by jeancochrane** [comment]
Closed in https://github.com/security-force-monitor/sfm-cms/commit/58bff2a49794bbabe7fb97bf8e1f3e8316c4b763.

**Comment by tlongers** [comment]
Fixed. Nice one.
