### ISSUE TITLE
Piwik on staging?

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#344]
@jeancochrane is Piwik code deployed on the staging site? I'm seeing back.~ results in our analytics.

**Comment by jeancochrane** [comment]
Yep, it is -- my mistake. Classifying this as a bug until I take it off.

**Comment by jeancochrane** [comment]
Changed up the way we deploy the analytics script so that it's encrypted, and only decrypted + moved to the right place when deploying to production. Confirmed that it's off the staging server, so I'm closing this.
