### ISSUE TITLE
Changelog "accordions" not expanding on iOS devices

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#345]
On Chrome in iOS 10.2.1 on iPhone 5, accordions do no expand when the value label is tapped.

**Comment by jeancochrane** [comment]
Strange... They're expanding for me on Chrome in iOS 11.0.3 on iPhone SE. I'll see if we can replicate this in BrowserStack.

**Comment by tlongers** [comment]
Interestingly, Change Log is now missing from `person` records.

**Comment by tlongers** [comment]
We are removing the changelog in its present form. Closing.
