### ISSUE TITLE
Users with browser languages other than en/es raise errors

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#346]
Not sure if this is getting raised in the UI at all, but we're seeing [errors](https://sentry.io/datamade/security-force-monitor/issues/396038286/events/8675768352/) from French users who visit the site with `accept-language` headers of `fr`. We should modify the `language_url` templatetag to handle requests for languages we don't support.

**Comment by tlongers** [comment]
No direct feedback about it yet. What's the common pattern here? If `accept-langauge` matches a language we serve, serve it; if not, default to `en`?
