### ISSUE TITLE
Missing space in source ~/es/~  citation popover title

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#347]
Missing space when popover title displays in cases where there is more than one source:
<img width="306" alt="whowasincommand" src="https://user-images.githubusercontent.com/2115933/32542032-53921cb4-c469-11e7-8ee1-7857c91c5864.png">
Pedantic, moi? :)

**Comment by jeancochrane** [comment]
I wonder if this is my fault, or the friendly translator's fault...

**Comment by tlongers** [comment]
Checked it out. I don't see an error In Rosetta. The `en` string doesn't indicate the need for a leading space ("sources for this datapoint"), and the `es` translation doesn't have one ("fuentes para esta información").

**Comment by jeancochrane** [comment]
Does it show up in all citation boxes, or just some of them?

**Comment by jeancochrane** [comment]
Sorry, I should have read closer. I see now you're finding it for all cases where there's >1 source.

**Comment by jeancochrane** [comment]
It looks like there actually is supposed to be a space in front of the translated string; it looks like Rosetta strips that space. I'm going to refactor it so that it doesn't depend on leading/trailing whitespace.

**Comment by jeancochrane** [comment]
Fixed in https://github.com/security-force-monitor/sfm-cms/commit/e9e9fb011bf3331cf9032bbf0db4ef6fed69216a. Translations look good on the live site now:

![spanish-translated-citation](https://user-images.githubusercontent.com/14170650/32577793-b0e9e180-c4a0-11e7-91ad-38f0efa89a92.png)

**Comment by tlongers** [comment]
Nice, thanks.
