### ISSUE TITLE
Errors in display of hard start dates of memberships

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#348]
Possible importer error regarding hard start dates:

Url: https://whowasincommand.com/en/organization/detail/212/

`Date first cited` of membership in `OCCH` of `1 Regimiento Mecanizado` is correctly shown as `27 June 2008`, however it is not a hard start date as shown on WWIC, and should not be underlined:

![whowasincommand](https://user-images.githubusercontent.com/2115933/32564083-fbff07ae-c4aa-11e7-80e7-ec8a1bbd8be5.png)

**Comment by jeancochrane** [comment]
Investigating now!

**Comment by tlongers** [comment]
Similar issue [here](https://whowasincommand.com/en/person/detail/648/), with end dates. 
<img width="956" alt="whowasincommand" src="https://user-images.githubusercontent.com/2115933/32670989-99fd0e18-c63d-11e7-86e5-5a41d2f1d554.png">


`Muhammadu Buhari` remains `President of the Federal Republic of Nigeria`. The last citation is correctly shown as `1 November 2016` but it's not a hard end date. In the raw data, the value for `End date? (Y/N)` of his membership of this role is flagged as `N` so the date should not be underlined on WWIC. Same with his membership of the `Armed Forces Council`.

**Comment by jeancochrane** [comment]
Took a closer look at this and realized that the logic we were using to import first/last cited dates was incorrect in many places in the importer :\ I'm working on a more standard way of doing things, changes coming soon.

**Comment by tlongers** [comment]
Great thanks.

**Comment by jeancochrane** [comment]
Fixed this in https://github.com/security-force-monitor/sfm-cms/commit/9277f627bf929bf75c7e4b13a30c7e0eba49769d. The next import should solve the issue. I'll keep this open until the import goes through, so that the issue reflects the current status of the app.

**Comment by jeancochrane** [comment]
Alright, import is finally done! I've confirmed that the two examples you listed above are fixed, so I'm closing. Feel free to reopen if you notice any funny business.

**Comment by tlongers** [comment]
Looks good. We'll do a dip sample from our raw data and let you know if anything odd emerges.
