### ISSUE TITLE
When entity removed from search results, should  entity-specific facets be removed?

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#349]
Trying to untangle something. What impact on `incident` results does leaving `organization` filters live have, if any?

Compare these two searches:

`https://whowasincommand.com/en/search/?selected_facets=organization_adminlevel1_ss_fct_exact%3AAnambra&selected_facets=country_ss_fct_exact%3ANigeria&q=Nkpor&entity_type=Violation&start_date=&end_date=`

0 results

`https://whowasincommand.com/en/search/?selected_facets=selected_facets=country_ss_fct_exact%3ANigeria&q=Nkpor&entity_type=Violation&start_date=&end_date=`

17 results, but oddly including `Mexico` rather than `Nigeria`.

**Comment by jeancochrane** [comment]
Filters for one entity type shouldn't have any effect on other entity types. If they do, it's a bug! I'll take a look at this -- I'm wondering if maybe there's a weird interaction happening with the "global facets" (country, in this case).

**Comment by tlongers** [comment]
Yeah, sorry for the vagueness with this Jean - I didn't have time to explore more today, but thought to get in on the list.

**Comment by tlongers** [comment]
The differences in the query string are outlined below. The query with `17` results seems to have an additional `selected_facets`. The `0` results query contains a `place` facet from `unit` records (`organization_adminlevel1_ss_fct_exact`)

`0` results| `17` results
-|-
-|selected_facets=
selected_facets=organization_adminlevel1_ss_fct_exact%3AAnambra|-
selected_facets=country_ss_fct_exact%3ANigeria|selected_facets=country_ss_fct_exact%3ANigeria
q=Nkpor|q=Nkpor
entity_type=Violation|entity_type=Violation
start_date=|start_date=
end_date=|end_date=

**Comment by tlongers** [comment]
I think this is still an issue.

**Comment by tlongers** [comment]
Stale; closing.
