### ISSUE TITLE
Can't cancel edit to Organization

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#35]
1. Go to ```/organization/edit/3/``` and click ```Cancel```.
2. Fields labelled ```Source for your changes``` and ```classification``` move to an error state (red boxed).

Expected behaviour on ```cancel``` is that if there are no changes, I'm returned to  ```/``` and the expanded list item I was attempting to edit.

**Comment by tlongers** [comment]
Also see #24

**Comment by evz** [comment]
Closed with 6f757ae4098530ba5572926cec7bfbebda83c892
