### ISSUE TITLE
Entries in subsidiary table should have start/end dates for parent/child relationships and not 

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#353]
<img width="769" alt="whowasincommand" src="https://user-images.githubusercontent.com/2115933/32670465-c7e6d950-c63b-11e7-9851-618d307f7dad.png">

Currently, the `first cited` and `last cited` dates displayed in the subsidiary table are those representing the overall date range of sources used to create data about the unit rather than for the dates of parent/child relationships between units. From the source data, this means that the dates displayed are from `Organization:date_first_cited` rather than `OrganizationOrganization:date_first_cited` and so on.  We expect that dates relevant to the parent/child relationship should be displayed in this section.

**Comment by tlongers** [comment]
Relating to #352 - they feel connected.

**Comment by jeancochrane** [comment]
Looks like we're indeed displaying the first cited date for the unit, and not for the composition.

**Comment by jeancochrane** [comment]
https://github.com/security-force-monitor/sfm-cms/commit/7596a8ea3bbac93c40466abb7bb9235ad88fd4be should fix this. Mind dropping a link to the unit you were looking at so we can confirm?

**Comment by tlongers** [comment]
Sure! I snipped the image from the record of [President of the Federal Republic of Nigeria](https://whowasincommand.com/en/organization/detail/1120/#subsidiaries)

On this record on staging (`~/en/organization/detail/1120/`) I can see the changes you've introduced resolve this issue:

<img width="767" alt="whowasincommand" src="https://user-images.githubusercontent.com/2115933/32830353-c91dc220-c9ec-11e7-8136-6656b9bc2693.png">

Your fix on #348 should resolve the issues with the incorrect display of exact end/start start dates in this table, when the importer is next run (per set up of db clone to run update ops on as discussed in #343)

Source data:

Organization:Name | OrganizationOrganization:parent_id | OrganizationOrganization:classification | OrganizationOrganization:date_first_cited | Start date of OrganizationOrganization Y/N? | OrganizationOrganization:date_last_cited | OrganizationOrganization:open_ended
-- | -- | -- | -- | -- | -- | --
Armed Forces Council | President of the Federal Republic of Nigeria | Command | 7/6/1994 | N |   | Y
Guards Brigade | President of the Federal Republic of Nigeria | Command | 12/22/2004 | N | 3/1/2010 | Y
Nigeria Police Force | President of the Federal Republic of Nigeria | Command | 1990 | N | 2010 | Y
State Security Service | President of the Federal Republic of Nigeria | Command | 1986 | Y |   | Y

**Comment by jeancochrane** [comment]
Alright, this has finally been deployed to production!

**Comment by tlongers** [comment]
Nice! Cheers.
