### ISSUE TITLE
OSM updates on geofabrik and mapzen

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#354]
At what intervals does it make sense to update WWIC's cached version of with OSM for the areas in our dataset?

**Comment by jeancochrane** [comment]
Good Q! @evz says monthly should be fine. Once we get a secondary database up and running with the capacity to quickly switch (#343) this should be a snap.

**Comment by tlongers** [comment]
Ok, it's not high priority at the moment so let's leave it open but inactive for now.

**Comment by tlongers** [comment]
Overhauled how we acquire OSM data. Closing.
