### ISSUE TITLE
Empty last cited date in person membership produces wrong "Most recent unit" in results views

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#356]
Query:
https://whowasincommand.com/en/search/?selected_facets=country_ss_fct_exact%3AMexico 

This gives us the below record at the top of the `personnel` section:

<img width="643" alt="whowasincommand" src="https://user-images.githubusercontent.com/2115933/32831747-39623102-c9f1-11e7-9695-48a1184a75fb.png">

Heading there:
https://whowasincommand.com/en/person/detail/1/

<img width="785" alt="whowasincommand" src="https://user-images.githubusercontent.com/2115933/32831799-6142c844-c9f1-11e7-96d0-5258d5c6f1ef.png">

For this person, there is a difference between the value for `Most recent unit` (`1 Batallón de Operaciones Especiales`) in the search results and that displayed in `Last seen as` section of the person dossier (`IX Región Militar `). The culprit seems to be this entry in the person's command history:

<img width="764" alt="whowasincommand" src="https://user-images.githubusercontent.com/2115933/32831893-b6855c5e-c9f1-11e7-8ac1-b246a5c701c0.png">

Seems that the display of search results views an empty `last cited` value as being more recent than a stated value for `last cited`. To me, looks like the fix here is to check for empty values in `person:membership:is open ended?`: if empty, exclude the row when creating the `Most recent unit` value for search results.

**Comment by jeancochrane** [comment]
This was a refreshingly dumb mistake! We were just accessing the wrong end of the sorted array in the table display template. Very simple fix, pushed in https://github.com/security-force-monitor/sfm-cms/commit/d637ba4cd9bdc366f372e6d5832cf3a63acb4188.

**Comment by tlongers** [comment]
Thanks!
