### ISSUE TITLE
Data source for "perpetrator type" facet in Incident search

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#358]
Are we getting the data shown in the "Perpetrator type" facet from `incident:perpetrator:classification` or `organization:classification`?

**Comment by jeancochrane** [comment]
We're pulling data from `incident:perpetrator:classification` both for the facet and for the display value in the table. Are you seeing some results that look fishy?

**Comment by tlongers** [comment]
Thanks Jean. I thought I did, but then I didn't :) So, all is fine. Closing.
