### ISSUE TITLE
Keys for persons and organizations

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#362]
In our master dataset we need to be able to be able to update `person:name` and `organization:name` without running the risk of changing an entity's permalink on WhoWasInCommand. What is the most pragmatic way of achieving this?

**Comment by jeancochrane** [comment]
Is the `id` column doing anything right now? I would recommend exporting the IDs from the database to that column, and then slightly refactoring the importer to prefer that ID over a name to get a hold on an entity.

**Comment by tlongers** [comment]
Yep, the `id` column could be repurposed for that. We presently use it for tracking the status of each row, but that business can be shifted to another location (or simply chopped out prior to the importer). What's the rough time/effort to refactor?

**Comment by tlongers** [comment]
There's a good example of the need to resolve this here. WWIC has these two entries, which are the same:

- [Zamfara State Command (State Security Service)](https://whowasincommand.com/en/organization/detail/1708/)
- [Zamfara State Command of the State Security Service](https://whowasincommand.com/en/organization/detail/2210/)

**Comment by jeancochrane** [comment]
Apologies for not getting a response to you sooner @tlongers! I think 7-10 hours of work would give us a comfortable cushion for wrestling with the importer. Happy to get moving on it if you're interested.

**Comment by tlongers** [comment]
Possibly this is dealt with now? @beamalsky ?

**Comment by tlongers** [comment]
Resolved with the introduction of UUIDs for all entities in the dataset.
