### ISSUE TITLE
Mapzen is dead :(

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#363]
Mapzen is shutting down February 1st. We currently use their polygons for OSM data.

This won't break the site, but it will prevent us from getting OSM data in the future. We should figure out a replacement.

**Comment by tlongers** [comment]
:( ... Geofabrik? Overpass API?

I use Wambacher's boundary services API to get polygons of various administrative levels: https://osm.wno-edv-service.de/boundaries/

**Comment by tlongers** [comment]
Long live Wambacher and OSM Overpass API! Closing.
