### ISSUE TITLE
Duplicate rows  in person records

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#365]
https://whowasincommand.com/en/person/detail/99/

<img width="876" alt="screen shot 2018-02-01 at 09 17 31" src="https://user-images.githubusercontent.com/2115933/35670543-c62798d0-0730-11e8-8b43-c4f929107332.png">

Note the that `first cited` value in the bottom row is not identified as a hard start like in the duplicate row above.

**Comment by jeancochrane** [comment]
Good catch on this @tlongers, sorry for the delay! I'll take a look and see what's up.

**Comment by tlongers** [comment]
Closing. There are some other issues with duplicates though.
