### ISSUE TITLE
Performance improvements to detail pages

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#368]
Right now, big detail pages like https://whowasincommand.com/en/person/detail/30/ can take a really long time to load. Seems like this is mostly due to Python processing time: The debug toolbar reports that of the 250 seconds it took to load on my machine, 12 seconds were spent in queries, and the rest were spent processing the page. Some ideas for cutting this time down:

- [Prefetch attributes](https://docs.djangoproject.com/en/2.0/ref/models/querysets/#prefetch-related-objects) that will be displayed in tables
- Retrieve source info in the source widget via an AJAX call so that we don't have to load (potentially) hundreds of sources for each attribute ahead of time
- Paginate tables on the page

**Comment by tlongers** [comment]
This is done and deployed to production (Sept 2018), with a 10,000x performance increase :)
