### ISSUE TITLE
Sometimes source URLs are excluded from wayback machine

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#378]
So, as I go through and improve the source capturing capabilities of the SFM research team, I found that content publishers can actually exclude URLs from the wayback machine. For instance this one: 

https://web.archive.org/save/https://web.archive.org/web/20160804170638/http://allafrica.com/stories/200106270283.html

The page exists on the internet still it just can't be accessed by the Wayback machine. This seems like maybe am edge case? Any idea how we'd like to proceed in these cases @tlongers or @tonysecurityforcemonitor ?

**Comment by tlongers** [comment]
Articles are first published by AllAfrica.com in full for everyone and can be saved to the Internet Archive.  After a period of time after the initial publication, a truncated version is served publicly and a subscription is needed to access the full content. The truncated version can still be archived though. Although sometimes it fails; hard to know what stories will archive, and which won't.

In this case, however, there's a rare double error:
- it's actually the url used to commit a link to the Internet Archive (via `~/save/~`); and,
- it seems to be archiving an already archived link, which the Archive won't allow.

Just to check I re-saved the source URL just now, and it worked ok:

`http://web.archive.org/web/20180605215057/http://allafrica.com/stories/200106270283.html`

We have actually cleaned up our sources and errors like this shouldn't be there. However, there will be numerous cases where the original source URL will have disappeared completely, so we should look at how WhoWasInCommand deals with these cases.  We still need to publish the source URL even if it's a 404. In these cases, the *ideal* would be:
- WhoWasInCommand periodically checks source URLS and archive URLs for their current status; and,
- Alerts admins if links are dead; and,
- Alerts the guest if links are dead.

I reckon that'd be a scope creep though. What's your take?

**Comment by tlongers** [comment]
We are also close to confirming whether or not we can use a third party API to handle archiving. For a given URL, it will return a range of different archive service links and a downloadable, notarised package with the source content in it.

**Comment by tlongers** [comment]
Resolving; we wont' auto-capture/auto-archive.
