### ISSUE TITLE
Wishlist: Grab local copy of content at URL of source 

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#38]
On my wishlist (Related to #21): could the tool also grab the full html and render a PDF of the webpage of a source?

**Comment by evz** [comment]
@tlongers I went ahead and stuck this into a milestone for "the future". I like this idea and it's certainly possible but I'm not sure if we can stick it into the current version.

**Comment by evz** [comment]
With that in mind, please do let us know the additional contents of your wishlist ;)

**Comment by tlongers** [comment]
How do you want to track wishlist stuff? Here, or in a wikipage somewhere? @tonysecurityforcemonitor

**Comment by evz** [comment]
For me, tracking them as discreet chunks of functionality described in issues would be nice. That way we could just lump them into a milestone for the time being and then triage them from there as necessary.

**Comment by tonysecurityforcemonitor** [comment]
> How do you want to track wishlist stuff? Here, or in a wikipage somewhere? @tonysecurityforcemonitor

> For me, tracking them as discreet chunks of functionality described in issues would be nice. That way we could just lump them into a milestone for the time being and then triage them from there as necessary.

Ok lets stick with putting them via issues right now @evz @tlongers  - would it be good practice to create a master wishlist issue where we can plug stuff in from other issues as everything (minus the wishlist ask) gets closed out?

**Comment by tlongers** [comment]
Stale; closing.
