### ISSUE TITLE
Fix the way polygons render in the "Evidences" table

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#380]
When a source evidences an Area, things are kinda messed up: 

![evidence](https://user-images.githubusercontent.com/551491/41060200-808d7b2a-6994-11e8-84d4-7de60bdf8b21.png)

@tlongers @tonysecurityforcemonitor It seems like the ideal for geographies like this would be to just render a map. Does that work? Do you think we should try something else?

**Comment by tlongers** [comment]
I appreciate the thoroughness of referencing every coordinate :) 

I think rendering a map would also be messy. How about including the OSM object type and ID number?

**Comment by tlongers** [comment]
Stale issue; closing.
