### ISSUE TITLE
Options for adding confidence scores to values

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#381]
In the Wireframes, I didn't define how we could assign confidence scores to a value. Here's some options - any thoughts @evz ?

## 1. Use the source picker to display and assign the confidence score

![screen shot 2018-06-07 at 10 30 45](https://user-images.githubusercontent.com/2115933/41091177-e221b35c-6a3d-11e8-91db-879a27823e50.png)

## 2. Include an extra dropdown for each field

![screen shot 2018-06-07 at 10 33 11](https://user-images.githubusercontent.com/2115933/41091361-46c382ae-6a3e-11e8-9269-258b6f4f5c48.png)

## 3. Star system on each field

![screen shot 2018-06-07 at 10 38 42](https://user-images.githubusercontent.com/2115933/41091666-0074fb1a-6a3f-11e8-84d7-3f1875c6bc96.png)

With colours...

![screen shot 2018-06-07 at 10 41 29](https://user-images.githubusercontent.com/2115933/41091820-607f7ad0-6a3f-11e8-995f-8de4b8fe1053.png)

**Comment by tlongers** [comment]
> I think probably the most straightforward way would be to add it to the source picker widget. 
Yeah, I agree. 

>This is mainly because I'm assuming that you'll want to have separate confidences and sources for each of the values in the multiple choice fields (eg. Other Names, Classification, etc).
Our multi-choice fields are not (currently) done this way. All the sources for all the values in, for example, `person:other_names` are in `sources:person:other_names`. We don't need to change that at this point.

**Comment by evz** [comment]
Well, anyways, I think adding it to the source picker widget still seems to be the most straightforward approach.

**Comment by tlongers** [comment]
Agreed. Makes sense to group these two tasks.

**Comment by tlongers** [comment]
Evz added a dropdown into the source picker, enabling the user to assign a confidence rating to the datapoint.
