### ISSUE TITLE
Add source: publication names are not deduplicated

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#388]
When we upload clean, deduplicated sources and publication names, this may be an issue. For now, the dropdown does not treat publication names as distinct.

Where? `~/en/source/create/`

What?

![image](https://user-images.githubusercontent.com/2115933/41284661-d664d470-6e31-11e8-9c96-53b688f4db15.png)

**Comment by evz** [comment]
@tlongers I added some logic to make sure to only select distinct publication names (I was, for some reason, thinking that selecting distinct sources would work previously, d'oh). Anyways, it looks like there's some work to be done cleaning up the publication titles:

![publication-titles](https://user-images.githubusercontent.com/551491/41305993-5089ab6a-6e3a-11e8-83ca-5c371dc82fe7.png)

**Comment by tlongers** [comment]
Yeah we've sorted all that out and have a clean, distinct list now. Closing this.
