### ISSUE TITLE
Resuming a data entry workflow 

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#39]
In `/` on the the staging site, see the source called "Source Title Test 2" - expanding it shows there are no other entities related to this source. It's possible to just add a source, skipping the steps where the user extracts content from the source. There should never be a source that has no info derived from it, but I wonder whether there are situations when a workflow to resume data extraction from a source would be useful.

**Comment by evz** [comment]
@tlongers Thinking about this a bit, it would seem like making things a bit easier to resume would make sense given that a number of things could interrupt extracting all the content out of a source. This is a bit tricky given that a "complete" entry does not always consist of the same kinds of content. I suppose if we tackle #32 and allow a user to seamlessly go forwards and backwards through the data entry process, this may be as simple as just making it possible to click a source title on the home page and getting dropped into the wizard right at the beginning (just with the forms pre-populated where appropriate). Does that make sense?

**Comment by tlongers** [comment]
Ok, let's see what resolving #32 does for the data entry process and circle back to this if needed.

**Comment by tlongers** [comment]
Related to earlier work on data entry process. Closing.
