### ISSUE TITLE
Add/update source: warn user where changes have not been saved

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#390]
When editing Source `basics`, if I make a change, then flick to `Access Points` and back again, the change is lost. Is there a quick way to alert the user about the unsaved changes?

**Comment by evz** [comment]
This one is kinda tricky since it's hard to know if a user has filled anything out in the form unless they actually hit the "save" button. I'll mull it over a bit. Perhaps there's a non-obvious solution.

**Comment by tlongers** [comment]
Ok. It's low priority at this stage.

**Comment by tlongers** [comment]
Closing.
