### ISSUE TITLE
Sources, read view: list access points in dropdown; use to view evidence table

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#392]
The layout of the source page needs some work to accommodate access points...

A distinct source is a combination of basic data and an access points. The evidence table should reflect this, showing the relationship between a specific basic/access point combination, and the records it is linked to. Where there is more than 1 access point, list them in a  single choice dropdown. When the user select one, update the evidence table.  This also addresses the situation where the number of access points is high, which will create a big mess in the "Archive URL" table. I've [drawn it out on Moqups](https://app.moqups.com/tom@securityforcemonitor.org/4YZ80oJfVK/edit/page/af48e5b5d), but here's a clip:

![image](https://user-images.githubusercontent.com/2115933/41287389-7c76fd9a-6e3a-11e8-9b4a-6156da0c76aa.png)

We can tinker with how access points are displayed in the dropdown. Perhaps a format like the below would be more accessible:

`[archive_timestamp](page range)(Access date)`
`20180612101920 (12 June 2018)`
`20180612101920 (pp. 20-22) (12 June 2018)`

I wonder if a panel might be better than a dropdown:

![image](https://user-images.githubusercontent.com/2115933/41287333-4f4d20f6-6e3a-11e8-9e94-89b53cdcbea5.png)

This needs some refinement ensure that the user always know what they area seeing though.

**Comment by evz** [comment]
I have a path forward on this but it might be a bit squirrelly so I might do it in another pull request.

**Comment by tlongers** [comment]
This isn't implemented on staging yet. Are there changes on this front in a PR somewhere?

**Comment by jeancochrane** [comment]
This isn't quite working as I expect it to. In particular, if you add a new source to a field and then navigate to another field, it seems to persist that source in the UI.

Pulling this back into "In progress" while I investigate.

**Comment by tlongers** [comment]
The way that access point are listed out is dramatically improved by this PR so I think we can close this one and carry forward on #567. @jeancochrane concur?

**Comment by jeancochrane** [comment]
Makes sense to me!
