### ISSUE TITLE
Source, read view: simplify evidencing table by displaying composite structure and labelling, not table views

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#393]
Currently, the evidence table exposes results in the form they are found in WhoWasInCommand's table structure:

![image](https://user-images.githubusercontent.com/2115933/41287581-18609dce-6e3b-11e8-8583-488ba1be7588.png)

This is overly complex. It would be more helpful to display the results to display in the form they appear in the composite views on WhoWasinCommand:

![image](https://user-images.githubusercontent.com/2115933/41287859-13975ab6-6e3c-11e8-9eee-f9815dd1a1bf.png)

It would be great to provide a link that goes directly to the field position in the linked record.

**Comment by evz** [comment]
ok so the "record name" in this case is whatever the name of the first class entity is? So, person name, organization name, incident description?

**Comment by tlongers** [comment]
>ok so the "record name" in this case is whatever the name of the first class entity is? So, person name, organization name, incident description

Yep, that's right.

**Comment by tlongers** [comment]
However `incident description` is often massive and not a quick differentiator. Better to use the formulation like the one in the  incident heading, with a location designation:

`Incident: 15 October 2008-9 December 2009 (Nigeria)`
`Incident: 26 January 2012 (Gidan-Yashi neighborhood, Nigeria)`

**Comment by tlongers** [comment]
Closing; nothing actionable at this point.
