### ISSUE TITLE
Approach to sources when standardizing a name

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#395]
Sometimes we'll find a name of an organization that is obviously abbreviated:

>  Riruta Pol.Station

We'll standardize it  in line with common naming schemes in policy and law for that security force:

>Riruta Police Station

In these cases, we don't have a specific source so would put:

>Name standardized based on Security Force Monitor's research

How should we handle this? A hack would be to have a specific source called "Name standardized based on Security Force Monitor's research". More elegant would be to indicate when we have standardized a name and that there isn't a source for. 

@evz What's your sense of the best approach, given that we've made sourcing more complicated already with the addition of access points?

**Comment by evz** [comment]
@tlongers Could we just add a "notes" field to the source or something that would allow you to add that kind of context? So, to take your example, the note could say something like "The name in the source is Riruta Pol.Station and we standardized it to Riruta Police Station based upon our research". I guess it really depends on how you want to communicate that to users and if you want to be able to segment all the places where you've standardized things. Adding the notes field seems like the simplest thing and would allow you to add other kinds of content there too that gives more context either for other researchers or for users of the site. Maybe you can talk a little bit about what the use cases might be for that info and we could come up with an approach based upon that.

**Comment by tlongers** [comment]
Resolved. We actually have a source called "Name standardized based on Security Force Monitor's research".
