### ISSUE TITLE
Adding a new source 1-Create Source Q's and notes

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#40]
Date published - will a researcher be able to just enter month and year and/or just year and/or no date?

No date sources are often webpages where the date we use is the date crawled or date accessed -- currently the citations look like this:

"BERRIOZÁBAL.". Enciclopedia de Los Municipios y Delegaciones de México. Instituto para el Federalismo y el Desarrollo Municipal, Secretaría de Gobernación. http://www.inafed.gob.mx/work/enciclopedia/EMM07chiapas/municipios/07012a.html (accessed 28 August 2015) Internet Archive link: https://web.archive.org/web/20150829011338/http://www.inafed.gob.mx/work/enciclopedia/EMM07chiapas/municipios/07012a.html

"Zonas Militares". Secretaría de la Defensa Nacional (SEDENA). https://web.archive.org/web/20060821201706/http://www.sedena.gob.mx/ejercito/comandancias/zon_mil.htm (captured 21 August 2006)

This isn't the date published per se... I'm not sure if the url and archive url entries would allow this none url text to be entered at the end (and if that would mess up the url or not)

@evz 
Also --- @tlongers - some method examples here

**Comment by tonysecurityforcemonitor** [comment]
![image](https://cloud.githubusercontent.com/assets/18744855/16387838/8d5d58fc-3c64-11e6-9afd-fc6f47807c80.png)

2 questions on this screen

1) I've entered a publication title - The Nation (Nigeria) --- this is our current formulation to differentiate the Nigerian publication The Nation from the US based publication The Nation. However, the drop-down menu below makes this redundant now, right? Meaning we can just put in The Nation and then select Nigeria as the country (or the United States) depending on the source, right? If so, how will this display to the end user so that they will know which publication we are using as source?

2) Can we add a label for that country selection drop down menu below Publication? Perhaps Country of Publication? Right now it wasn't immediately clear what the function of the drop down menu was.

**Comment by evz** [comment]
@tonysecurityforcemonitor 
* **Publication title** I added a separate country field mainly because I think like a database sometimes and actually normalized out the info about the publication into a separate table thinking that there might be other info you wanted to track eventually (author, maybe some attributes about the publisher that might give you a measure of how reliable the source is, etc). Separating out the country also makes it simpler to search for all things that were published in a particular country (without having to figure out how to split out the country from the other field). That said, I'm also pretty into simplifying things so if your current system of just storing the country with the title of the publication is good enough, we can continue with that approach.

* **Country label** Forthcoming dependent on how we decide to resolve the above point.

* **Notes** It would be relatively easy to add a "Notes" field that just accepts any arbitrary text. It seems like that might be a useful way to capture things about the source that don't quite fit into the other buckets.

**Comment by evz** [comment]
Oh, and, we have another issue (#14) that lists out all the dates that seem to need to be non-specific.

**Comment by tonysecurityforcemonitor** [comment]
> Publication title I added a separate country field mainly because I think like a database sometimes and actually normalized out the info about the publication into a separate table thinking that there might be other info you wanted to track eventually (author, maybe some attributes about the publisher that might give you a measure of how reliable the source is, etc). Separating out the country also makes it simpler to search for all things that were published in a particular country (without having to figure out how to split out the country from the other field). That said, I'm also pretty into simplifying things so if your current system of just storing the country with the title of the publication is good enough, we can continue with that approach.

> Country label Forthcoming dependent on how we decide to resolve the above point.

Thinking like a database is great ;) !   Let's keep it as you're right I could see it being a very useful way for us to explore the data. Its also a good reminder to the researcher as well.


> Notes It would be relatively easy to add a "Notes" field that just accepts any arbitrary text. It seems like that might be a useful way to capture things about the source that don't quite fit into the other buckets.

Ok sounds good!

**Comment by tonysecurityforcemonitor** [comment]
@tlongers @tonysecurityforcemonitor --- entering a source currently forces researcher to input an Internet Archive url as well - I like that from a process side of things --- but what do we do when things can't be put in the archive due to robot.txt? Should we keep system as currently is (forcing researcher to put something - and we can come up with some sort of standard note)? I'm leaning in that direction - but unsure.

**Comment by tlongers** [comment]
@tonysecurityforcemonitor we should keep a separate copy of each source anyhow (preferably full webpage grab, timestamped/hashed), and store that for archive purposes. If robots.txt prevents Internet Archive from working, should we self-archive a page (e.g. sources.securityforcemonitor.org/linky/link and include that with a caveat like "This is hosted here for research purposes. Fair use applies etc If you've got a beef contact us"?

**Comment by tonysecurityforcemonitor** [comment]
@tlongers let's discuss further --- that reminds me there is another avenue utilizing ArchiveIt which I need to follow up on. Would be good to discuss all with you.

**Comment by tlongers** [comment]
All either resolved, or not relevant to current and forward development regarding the management of sources. Closing.
