### ISSUE TITLE
Source: when viewed, a source record has not updated after values changed

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#401]
`~en/source/view/c75321f4-898e-4cc8-9f5a-a1abea4f3166/`

Displays the publication date as `July 13, 2018`:
![image](https://user-images.githubusercontent.com/2115933/42689676-3be979c0-8699-11e8-836e-17a54349c769.png)

Click `edit` and you can see the publication date is `2018-07-12`:

![image](https://user-images.githubusercontent.com/2115933/42689690-53f4f85a-8699-11e8-82a2-896490ef480c.png)

**Comment by tlongers** [comment]
This is also happening when an access point is added. This source, for example:
`~en/source/view/d32fd8b9-ad9f-4d76-843a-459ae598ff76/`
Added an access point, saved that, went to `basics` and saved that. No update to the record.

**Comment by tlongers** [comment]
It does seem to update after a bit though - I returned to the record in the issue description, and the read only had updated to July 12, 2018 (which is correct)

**Comment by evz** [comment]
For the detail pages, we were pretty aggressively caching them in an attempt to make them a bit more performant. Now that I've merged #414, we can probably turn that off.

**Comment by tlongers** [comment]
This is fixed.
