### ISSUE TITLE
Source picker: error thrown when no changes made to aliases field

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#409]
Didn't touch the field, hit save, and got this error ; but then added `Larry` as an alias along with a test source. The error threw again:

`en/person/edit/ab966b67-7b24-4da7-b68f-44ef4893b0c3/`

![image](https://user-images.githubusercontent.com/2115933/43544885-38d5f49c-95cc-11e8-84b6-64d0706d1b02.png)

**Comment by evz** [comment]
You basically put your finger directly into the "wonky interactions" I was referring to in the email. I'm working on another approach to this currently which will close this issue.

**Comment by tlongers** [comment]
Duplicate of #434, where we're carrying the issue forward. Closing.
