### ISSUE TITLE
Adding a new source 2-Organizations Qs and Notes

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#41]
@evz 
@tlongers

![image](https://cloud.githubusercontent.com/assets/18744855/16390255/df95e674-3c6f-11e6-97c4-7a66584f31cd.png)

It appears that the dropdown is the same if an organization already exists in the database or if its being entered for the first time. There is a question in my mind of how the workflow will look when adding to an existing organization.

**Comment by tonysecurityforcemonitor** [comment]
@evz 

![image](https://cloud.githubusercontent.com/assets/18744855/16390327/3bcd4086-3c70-11e6-8863-adbc24238700.png)


Classification needs to be fixed here. It should be Organization:classification (classification of the organization), not OrganizationOrganization:classification (classification of the parent/child relationship) as it appears to be.

**Comment by tonysecurityforcemonitor** [comment]
@evz 

It makes sense to have the entries related to the parent/child relationships on this screen - currently there isn't a place to enter them.

**Comment by evz** [comment]
* **Organization name dropdown** The way that works is that, while a user is typing, we're searching the organization table for a organization with a name containing the text that is being typed. If we find something, the user can select it and if not, the only choice that is left is that they are typing and it tells us that we'll need to create that organization. The assumption here is that users are following the data entry guide and "Whenever possible ... [using] the most complex version of the organization’s name" that should give them and other users the ability to figure out the correct choice if it exists and if not create a new entry. If this is not a safe assumption, let's talk about how this might work.

* **Classification** This is not the way things seem to be modeled under the hood but it certainly does make sense. We can update what's happening here (See #46)

* **Parent/child** See #45
