### ISSUE TITLE
Source picker: archive URL is sometimes the edit page url 

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#410]
On the `name` field here:

`~/en/person/edit/ab966b67-7b24-4da7-b68f-44ef4893b0c3/`

The Archive URL values are a mixed bag of the url of the person record currently being edited, and the correct archive URL:

<img width="473" alt="screen shot 2018-08-01 at 20 50 48" src="https://user-images.githubusercontent.com/2115933/43545065-bfa92034-95cc-11e8-928c-6f72e7ddce2f.png">

**Comment by evz** [comment]
yes, hmm, that must mean there is no archive URL. That's an easy fix. Thanks!
