### ISSUE TITLE
Source picker: activate on focus, not only click

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#411]
The source picker does not change field when tabbing between input fields, but it does when clicking between fields. It should change in both types of interaction

**Comment by tlongers** [comment]
OK, closing for now.

**Comment by tlongers** [comment]
Tabbing though the data entry field now actually working for me (Chrome 68.0.3440.106)

![tabbing_20180920](https://user-images.githubusercontent.com/2115933/45818473-becf9380-bcd9-11e8-9828-abb8061abb66.gif)

**Comment by evz** [comment]
@tlongers Yeah, the fields that mess it up are the ones that have the select2 stuff attached to them (so in your animation, the "country" field. Everything else should work as expected without any additional work.

**Comment by tlongers** [comment]
Stale; no longer needed.
