### ISSUE TITLE
Adding a new source 3- People Qs and Notes

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#42]
@evz 

Data model doesn't have death date in it anymore...

**Comment by tonysecurityforcemonitor** [comment]
Also having the ability to go back struck me as very helpful - I had actually gotten to this screen before I realized that I had forgotten to enter an organization

**Comment by tonysecurityforcemonitor** [comment]
@tlongers - This screen pushes the research workflow in a different (and helpful) direction as compared to working off a spreadsheet. It strikes me its now critical to really build out a robust picture of the security forces - and especially creating "generic" army and police units (ie Mexican Army) - so that a person can always have an organization to be attached to.

**Comment by tlongers** [comment]
Two issues here for @evz 
- correction to the data model 
- duplicate of #19 and #32 

@evz  let us know when  method reflections are helpful or not helpful  - would you prefer to keep them off the issue queue?

**Comment by evz** [comment]
* **Death date** See #47

@tlongers @tonysecurityforcemonitor I don't mind that kind of discussion taking place here if it's useful for you. It's always nice to get a higher level perspective when you're thinking about how something might actually be used.

**Comment by tonysecurityforcemonitor** [comment]
@evz - new issue with entering a person - entering a Title is currently required - it shouldn't be (most People do not have Titles). Same with Rank or Role - we might just have a person that we know is a member of an Organization but not know anything else about them.

**Comment by tlongers** [comment]
All resolved. Closing.
