### ISSUE TITLE
Source count appearing where table values are blank

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#422]
Noticed this at `en/person/view/19cfa251-2df7-49b7-88ff-df187e584b92/`

![image](https://user-images.githubusercontent.com/2115933/44674426-5ae0e480-aa25-11e8-9df4-9fa21c246930.png)

And then hover the mouse over the the cells in `Title`:

![image](https://user-images.githubusercontent.com/2115933/44674439-67653d00-aa25-11e8-9eb2-79edd541afac.png)

Clicking on the red circle activates the source popover, but it hangs (as there is nothing for it to load):

![image](https://user-images.githubusercontent.com/2115933/44674570-d80c5980-aa25-11e8-8702-49771e2d955f.png)

Where a cell is empty, we expect that a hovering the mouse should not activate the source popover mechanism.

**Comment by tlongers** [comment]
Possibly related to #433

**Comment by evz** [comment]
This should have been fixed by 71f5aa4f9e85ca48f2846795bfe9a117904ee5ff

**Comment by tlongers** [comment]
Will verify when https://github.com/security-force-monitor/sfm-cms/commit/71f5aa4f9e85ca48f2846795bfe9a117904ee5ff is merged and deployed to staging.

**Comment by tlongers** [comment]
Confirm fix.
