### ISSUE TITLE
Adding a new source 4- Relations 

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#43]
@evz - From a workflow perspective I think it might be better to have this screen merged with 3-People. That way a researcher is entering everything about a person on one screen. 

I think re-arranging the first and last citations and renaming the real context buttons would improve workflow.

Perhaps having First Citation and then a Start Date? button - then the start context field - then the Last Citation and then an End Date? button

**Comment by tonysecurityforcemonitor** [comment]
And as noted the People workflow isn't yet complete - but just to note I couldn't enter a Role or Rank.

**Comment by evz** [comment]
@tonysecurityforcemonitor 
* We'll work down some of the other more nuts and bolts issues that we have piled up and then swing back around to this if we have time (if that's OK). 

* The lack of choices for Role and Rank is somewhat related to #26. I guess I was unsure how to handle that but I think it's clear now.

**Comment by tlongers** [comment]
Issue refers to earlier version of the data creation workflow. Issues regarding defining relationships, at late 2018, handled differently. Closing.
