### ISSUE TITLE
On areas of operation table, source popover numbering got freaky

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#433]
This happened just the once. Adjacent values with `8` and then suddenly `220`:

`~/en/organization/view/e003c909-41d9-4ae3-aaff-3294593805c1/`

![image](https://user-images.githubusercontent.com/2115933/45748726-7c3a8800-bc01-11e8-88e1-574c3df8190a.png)

![image](https://user-images.githubusercontent.com/2115933/45748748-83619600-bc01-11e8-8733-ffe0c4b24a87.png)

**Comment by evz** [comment]
As weird as it sounds, I'm pretty sure this was related to the way that the javascript was misbehaving in #432. Let's keep an eye on it, though.

**Comment by tlongers** [comment]
We don't show numbers anymore, so the issue is resolved.
