### ISSUE TITLE
When editing a person record, removing an alias does not remove it

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#434]
On staging: `~/en/person/edit/22c32543-4371-4a2a-a192-7ffe6b544536/`

1. Select `edit`.
2. Remove `Mr. A.A. Abu` from the aliases. 
3. Select `save`, and the read view of the record reloads.
4. `Mr. A.A. Abu` is still recorded as an alias. It should have been removed.
5. Select `edit` again.
6. `Mr A.A. Abu` is still recorded as an alias, which is what we don't want.

**Comment by evz** [comment]
Someone smart once said there are two hard problems in computer programming: cache invalidation and naming things. This particular problem was the result of the former. Jean setup some very aggressive caching on this site when things were much slower in an attempt to speed things up a bit. I went ahead and just turned it off since it seems like the things that were causing that slowness have been sorted out. I just double checked and it looks like this thing is working as expected.

**Comment by evz** [comment]
@tlongers If you could verify that the above seems to be the case and then close the issue if you are satisfied, that'd be great.

**Comment by tlongers** [comment]
Thanks Eric. Sticking with the same record. Adding a new alias seems to work, and it displays immediately on the read view. However, removing an existing alias does not. It's removed in the UI, but still displays; if the record is re-opened for editing, the alias is still there.

**Comment by evz** [comment]
Hmmm ..... When I look at that record, it looks like there are no sources associated with the aliases field. No matter what I do I can't get it to leave that page unless I add a source. If I remove an alias and add a source, then I am able to save. What are you doing with regards to adding sources?

**Comment by tlongers** [comment]
Hrm, very tricky to get to the root of this.  The issues with the `Other Names` field appear to be as follows:

- It is possible to add multiple values without adding a source. This should be impossible.
- In order to  remove a single value, a number of values, or all values the researcher needs to associate a new source. This is not necessary. Methodologically, if a value  is removed from `Other Names` then the researcher will likely disassociate one, a few or all sources from the field.
- There are inconsistencies in how the edit view UI and the read view UI display the sources associated with values in the `Other Names` field. For example, if a source is removed in the edit view UI, it may still display in the read view UI.

The following changes address these issues:

- Force the user to associate a source when any new value is added to the `Other Names` field.
- Do not force the user to associate a new source with `Other Names` if one, a few, or all existing values are removed from the field.
- If the `Other Names` field is emptied by the researcher then do not force them to associate a new source. Instead, force them to remove all existing sources by hand before allowing the record to be saved.
- Ensure consistency between the read view UI and edit view UI.

Here's a step by step work-through that shows how the issues above show themselves. Try the below steps on a person record that has no existing values in the `Other Names` field:

1. Browse to record and select `Edit`.
2. Click on the `Other Names` field.
3. Enter `A` in `Other Names` field, but do not add a source.
4. Click `Save`, and the read view of the record will display.
5. `A` will be displayed in the `Other Names` part of the record. 
6. Click on the circle next to the value `A`. The source widget will not display a source, and will just grind away.

This shouldn't work. At step 4, the system should have prompted the user to associate a new source before committing the update to `Other Names`.  Let's keep going though:

7. On the same record, select `Edit`.
8. Click on the `Other Names` field.
9. Remove  `A` from the list of values in `Other Names. The field should now be empty.
10. Click `Save`, and the read view of the record will display.
11. Despite having been removed, the value `A` will be still displayed in the `Other Names` part of the record. 
12. Click on the circle next to the value `A`. The source widget will not display a source, and will just grind away.
13. On the same record, Select `Edit` again. 
14. Click on `Other Names` and the value `A` is still there, absent any source, despite having been removed.

Because it should not have been possible to add a value without a source, we end up with an impossible situation: the value can't be deleted. However, continuing on:

15.  In the source picker for `Other Names`, add the source `Trump: soft Brexit will 'kill' UK's chances of US trade deal`.
16. Click `Save`, and the read view of the record will display.
17. The value `A` will still be present in the `Other Names` portion of the record.
18. Click on the circle next to the value `A`. The source widget will display the source `Trump: soft Brexit will 'kill' UK's chances of US trade deal`.

This is correct behaviour. I was able to associate a new source with an existing value. Continuing on:

19. On the same record, select `Edit`.
20. Click on the `Other Names` field.
21. In the source picked for the value `Other Names`, remove the source `Trump: soft Brexit will 'kill' UK's chances of US trade deal`.
22. Click `Save`, and the read view of the record will display.
23 The value `A` will still be present in the `Other Names` portion of the record.
24. Click on the circle next to the value `A`. The source widget will display the source `Trump: soft Brexit will 'kill' UK's chances of US trade deal`, even though I removed it.
25. On the same record, select `Edit`.
26. Click on the `Other Names` field.
27. The source picker for the field `Other Names` will not display the source `Trump: soft Brexit will 'kill' UK's chances of US trade deal`.

There's a few issues here. At step 22 above, I should not have been able to save the record as it writes a populated field with no sources associated with it. Further, there is an inconsistency between the read view UI and edit view UI. Although the operation should be impossible, the edit view UI is correct; yet the read view UI does not recognise that the source has been removed from the `Other Names` field. I would have expected the read view UI to revert to the situation in step 12 (where the source widget just grinds away).  Moving forward again ...

28. On the same record, select `Edit`.
29. Click on the `Other Names` field.
30. Add the value `B` to the `Other Names` field.
31. Click `Save`, and the read view of the record will display.
32. The values `A` and `B` are displayed in the `Other Names` portion of the record. 
33. Click on the circle next to the values `A` and `B`. The source widget will not display a source, and will just grind away.
34. On the same record, select `Edit`.
35. Click on the `Other Names` field.
36. In the source picker for the `Other Names` field there are no entries.

Adding an additional value to `Other Names` seems to clear out the ghost of the source `Trump: soft Brexit will 'kill' UK's chances of US trade deal` bringing the read view UI and edit view UI back into harmony. The situation is still wrong though, as we now have two values that are absent sources. 

37. From the field `Other Names` remove the value `B`.
38. Click `Save`. The record will not save. Instead the system will display a validation warning: ` "aliases" requires a new source`. It will also correctly restore the value `B` to the field `Other Names`.

This is logically correct: because a change as been made to the field, the system asks the researcher to provide a source. However, it is methodologically incorrect because they want to remove a value completely. Let's try to move forward with the logic with the workaround of  adding a source we will immediately then remove.

39. In the source picker for the field `Other Names` associate the source `Police kill robber as another escape with bullet`.
40. Click `Save`, and the read view of the record will display.
41. The value `A` is displayed in the `Other Names` portion of the record. 
42. Click on the circle next to the value `A`.The source widget will display the source `Police kill robber as another escape with bullet`.
43. On the same record, select `Edit`.
44. Click on the `Other Names` field.
45. In the source picker for the `Other Names` field, remove the source `Police kill robber as another escape with bullet`.
46. Click `Save`, and the read view of the record will display.
47. The value `A` is displayed in the `Other Names` portion of the record. 
48. Click on the circle next to the value `A`. The source widget will still display the source `Police kill robber as another escape with bullet`, even though the researcher has removed it.

Here, we used a source as a workaround but may be  stuck with it. The UI inconsistency appears between the edit view UI (in which the source is removed) and the read view UI (where the source is still visible). Closing it out...

49. On the same record, select `Edit`.
50. Click on the `Other Names` field. There are no sources associated with this field in the source picker.
51. Remove the value `A` from the `Other Names` field.
52. In the source picker for the `Other Names` field, add the source `Amnesty Takes Off`.
53. Click `Save`, and the read view of the record will display.
54.  The `Other Names` portion of the record does not display.
55. On the same record, select `Edit`.
56. Click on the `Other Names` field. There are no values or sources associated with this field in the source picker.

To empty the `Other Names` field completely and save the record, we had to associate a source. When editing the record again, this source was nowhere to be seen. The process can begin again from step 1 now.

**Comment by evz** [comment]
A lot of what's going on here has to do with a peculiarly within Django that is proven somewhat difficult to reconcile. When an empty value is submitted by a form, that field is missing from the `POST`ed data and checking for missing values plus knowing what it means when they are missing is kinda one of those Big Problems in working with data in general. 

Anyways, I've managed to write a couple test cases that are failing in the way I'd expect them to as a result of following through with your super helpful step-by-step walkthrough. Now I just need to get them to pass ......

**Comment by tlongers** [comment]
If that fails, two options come to mind:
- Modify `Other Names` to make it a simple, repeating field rather than a single multi-select one. So if we have 5 aliases, we create five `Other Names` fields. Sources are then added to each value, reducing the complexity considerably.
- Introduce a way that the researcher can specify that a field is empty, which gives Django something to POST.

**Comment by evz** [comment]
@tlongers I think I was able to finally suss out what was going on with this stuff. One thing that I did turn up was that it appears that some of the data points that we have currently in the database don't actually have sources attached to them. Which seems like it shouldn't be capable of happening (and, if we're using this system going forward, won't happen). At any rate, I wrote some code that stops an entity from being saved until the attributes with missing sources have sources attached to them as well. Going forward, this shouldn't happen but I was able to find a few things pretty easily where that was the case and it would have made them unsaveable otherwise since there are parts of the code downstream from the validation that rely on certain things being true (like everything that is being recorded should have a source).

**Comment by tlongers** [comment]
Ok, so the fix here is as you outline in response to #453 ([in this comment](https://github.com/security-force-monitor/sfm-cms/issues/453#issuecomment-424858298).  I'm glad we're at the root of it. Bit of a lesson for our side really in finding ways to flag method inconsistencies that mess with the technical.

**Comment by tlongers** [comment]
Not fixed yet. It's removing sources okay, but not not yet associating new sources with the `Other Names` field or any other field. Here's a quick demo on `~en/person/edit/bc4e88d8-2685-407b-b1d6-631f94d140f8/`

I added a new alias, then added a new source:

![image](https://user-images.githubusercontent.com/2115933/46202148-ed6af100-c30d-11e8-845f-a54449bf8bec.png)

Selecting `save` gives a validation message:

![image](https://user-images.githubusercontent.com/2115933/46202163-fa87e000-c30d-11e8-8e64-5237897f6355.png)

**Comment by tlongers** [comment]
This /seems/ fixed, at least by the last test I outlined https://github.com/security-force-monitor/sfm-cms/issues/434#issuecomment-425388473
