### ISSUE TITLE
Cancel changes action should be available on all edit pages

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#436]
per wireframes

**Comment by evz** [comment]
The wireframes navigate to the homepage when you hit cancel. Should we just have it navigate to the read only view?

**Comment by tlongers** [comment]
Yes, that's the best and simplest approach: return the user to the read view of the record they were editing.

**Comment by tlongers** [comment]
To add to this. There needs to be a "Save and continue editing" option on all records. For example, if a researcher has to update a person with 10 postings, having only a "Save" button means:
- returning to the read view
- clicking edit again-
- selecting postings, 
- selecting the next posting you want to review
For postings, then, "Save and continue editing" would simply commit the data and the return the researcher to the posting they were last editing.

**Comment by tlongers** [comment]
Fixed. Re-loads read view of record.
