### ISSUE TITLE
Changes made to person:division are shown to guests in read-only view, but not logged in users

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#437]
I updated this record, changing `person:division` from `Nigeria` to `Afghanistan`. On saving, the change was not displayed to me, but it was displayed to a user who was not logged in. However, it was not quite right: instead of the label `Afghanistan`, it displayed `ocd-division/country-af`.

`~/en/person/view/22c32543-4371-4a2a-a192-7ffe6b544536/`

Logged in view, after updating `person:division`:

![image](https://user-images.githubusercontent.com/2115933/45751431-36ce8880-bc0a-11e8-8ed2-b49cc5624e76.png)

Guest view of the same record, after updating `person:division`

![image](https://user-images.githubusercontent.com/2115933/45751453-4352e100-bc0a-11e8-91de-f676c89d9945.png)

**Comment by tlongers** [comment]
Conversely, if I add a new source to `person:name` and save it, the change IS shown to the logged in user, but doesn't load for the guest user.

**Comment by evz** [comment]
This was probably halfway due to what was going on in #434. I am, however, noticing, that these don't seem to be displaying as expected so I can look into that.

**Comment by evz** [comment]
This was a rather silly problem in the template that meant that the division identifiers were not being formatted correctly. This was actually effecting every place where we were using division identifiers. At least I'm consistent!
