### ISSUE TITLE
In source picker, use field label not field name

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#439]
The source picker is taking the field name (`aliases`) rather than the field label (`other names`). It should use the field label (as this will also mean it can be translated):

![image](https://user-images.githubusercontent.com/2115933/45764500-bcfac700-bc2a-11e8-9e5c-d72a150224a0.png)

**Comment by evz** [comment]
Related commit: fdd87f8fc0f29b0a9696224d2400e3339e855007

**Comment by tlongers** [comment]
Fixed.
