### ISSUE TITLE
Adding a new source 5- Geographies

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#44]
@evz 

Right now it's a question in my mind if we are better off combining this into the 2-Organizations page. It makes sense in my mind to have all the data related to an organization in one screen. Either way there is a “break” in data entry to go from Organization to Person to Person’s Relationships, back to Organization's site/area of operations...

For the Geography Type drop down can rename Area to Area of Operations? It would be clearer for the researcher.

Is Name Site:Name (The site's name)? I should try and think of something that is more immediately descriptive for the researcher (perhaps Base Name or Facility Name). Just a note for the future - but don't let me forget!

The start date and end date placeholder text could be darker/more prominent - I had a hard time seeing it.

**Comment by tonysecurityforcemonitor** [comment]
@evz @tlongers - workflow/CMS issue - Entering an organization source requires you to input a geography --- however - sources won't always have a geography attached for an organization.

1) Is this happening simply because I am entering in an organization for the first time? Or is it always required?
2) Thinking like a database - organizations must at least it be attached to the "top level" geography of the country - otherwise it cannot be plotted.
3) Requiring the researcher to put in at least the "top level" geography of the country everytime seems sub-optimal, but so does allowing researcher to enter organization with no attached geography.
4) May just be workflow workaround - when enterting organization for first time - researcher should attach to the country

**Comment by tonysecurityforcemonitor** [comment]
@evz Currently it looks like entering geography covers:

- OrganizationSite:organization_id
- OrganizationSite:site_id (less sure if this is covered)
- Site:Name (The site's name)
- Site:geonames_name (The site's smallest unit GeoNames name)
- OrganizationSite:date_first_cited
- OrganizationSite:date_last_cited

**and/or**

- OrganizationArea:organization_id
- OrganizationArea:area_id
- Area:geonames_name
- OrganizationArea:date_first_cited
- OrganizationArea:date_last_cited


**Currently it seems to be missing:**

- Site:division_id
- Site:geonames_id (The site's smallest unit GeoNames identifier) - not necessary for researcher to enter - but useful for them to be able to see it in some way
- Site:admin_level_1_geonames_name (The site's Admin 1 GeoNames name)
- Site:admin_level_1_geonames_id (The site's Admin 1 GeoNames identifier) - not necessary for researcher to enter - but useful for them to be able to see it in some way 
- Site:geo (The site's coordinates) - not necessary for researcher to enter - but useful for them to be able to see it in some way 
- Site:id (The site's unique identifier)
- Area:id (The area's unique identifier)
- Area:division_id
- Area:geonames_id
- Area:centroid
- Area:geo
- OrganizationSite:open_ended
- OrganizationArea:open_ended

**Comment by tlongers** [comment]
Geographies have been re-jigged. This issue is a useful reminder that during testing (and acceptance) we have to validate that the fields are in the right place and doing what they need to. Closing.
