### ISSUE TITLE
Refinements to how  data on a source is displayed in the source picker

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#443]
Just some first thoughts on how to increase the density of information about sources in the Source Picker widget.

The data we have available about sources is structured this way:

|field|value|
|-|-|
|title| Strange Helicopter Hovered Over Giwa Barracks Before Attack|
|published_on| 2014-03-23|
|accessed_on| 2018-08-21|
|source_url|http://www.thisdaylive.com/articles/strange-helicopter-hovered-over-giwa-barracks-before-attack-/174366/|
|archive_url|https://web.archive.org/web/20140324063728/http://www.thisdaylive.com/articles/strange-helicopter-hovered-over-giwa-barracks-before-attack-/174366/|
|archive_timestamp|2014-03-24T06:37:28|
|country|Nigeria|
|publication_title|This Day|

We need to bring more of this into play inside the Source Picker to help researchers quickly differentiate between sources and access points:

![image](https://user-images.githubusercontent.com/2115933/45821172-75cf0d80-bce0-11e8-8201-f654347f9104.png)

Imagining there were three access points for the same source, it might look like this in the source picker. The Internet Archive timestamp is the differentiator:

![image](https://user-images.githubusercontent.com/2115933/45821359-e8d88400-bce0-11e8-95fd-4dcdf7ad173e.png)

@evz I know you had some ideas on this issue, particularly on how to display different access points.

**Comment by tlongers** [comment]
Refining this further to address three issues:

### 1. Need to add in Confidence Score widget

We've discussed this before in #381, where we agreed that a dropdown in the source picker area would be the best solution. Taking it a little further, the functionality should be clearly signposted for the researcher. 

### 2. Increase in density of information about sources and access points

In the graphic below, I've included a range of sources that have different metadata and access points. most access points are differentiated by archival snapshots; some by page numbers. Where a source has a `source_url` it should be hyperlinked in `title`; `archive_url`  should be included in the archive timestamp. 

### 3. improving the process of adding and removing sources

A few colour-scheme changes help here: green for already added, amber for added but not saved, red for removed but not yet deleted. This latter bit is the key change, I think: when removing a source from the list of source already associated with a datapoint, it would be useful for the researcher to see and have the option to undo the action in case they have made a mistake. I've included that as a function in the graphic below - with a "restore" icon that once clicked just re-adds the source to the green list.

## How it could look

![image](https://user-images.githubusercontent.com/2115933/45879414-539ac580-bd9c-11e8-9549-ff5f7e324a31.png)

**Comment by evz** [comment]
@tlongers I think I'm going to tackle this in a separate pull request and just stick to squashing bugs in the current one. As always, thanks for the detailed exposition.

**Comment by tlongers** [comment]
@evz Mustn't forget to add in that confidence score widget

**Comment by tlongers** [comment]
Adding this into the [CRUD improving project](https://github.com/security-force-monitor/sfm-cms/projects/4) -  it's critical that the source picker functions are as clear as possible. It's nearly there I think, but verify what is there against the outline I've given in this issue.

**Comment by jeancochrane** [comment]
This isn't quite working as I expect it to. In particular, if you add a new source to a field and then navigate to another field, it seems to persist that source in the UI.

Pulling this back into "In progress" while I investigate.

**Comment by tlongers** [comment]
These are really effective updates to this feature Jean and I think they complete the functionality that is needed to use this on a daily basis. 

There are improvements that can be made to it, but I'll record those in a separate issue.

**Comment by jeancochrane** [comment]
Great, thanks @tlongers 👍 Closing this so that we can supercede it by the improvement issues.
