### ISSUE TITLE
Sinaloa doesn't look like that

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#444]
It looks like the way we imported relations in the past was maybe not working that well: 

![sinaloa](https://user-images.githubusercontent.com/551491/45829339-5627ed00-bcc0-11e8-8bf3-3e6f9869b342.png)

https://whowasincommand.com/en/organization/view/242/

This is probably something to keep an eye on when we are moving ahead with the locations app.

**Comment by tlongers** [comment]
I have a feeling this this issue has been raised before re: Sinaloa. See #337 I should have taken a screenshot :)

**Comment by tlongers** [comment]
Could it be that the polygon simplification has a crazy effect on this particular shape?

**Comment by evz** [comment]
Well, it looks ok on the openstreetmap site: https://www.openstreetmap.org/relation/2455086. 

And on Wambacher:  

![wambacher](https://user-images.githubusercontent.com/551491/45844150-2a6c2d80-bce7-11e8-9294-45c49ab51fc7.png)

and in our forthcoming locations app:

![location-app](https://user-images.githubusercontent.com/551491/45844407-efb6c500-bce7-11e8-9532-4ceddd479f3f.png)

I'm not really sure what might have caused that. It looks like there was a polygon that didn't get closed or something. Anyways, I mostly opened this as a reminder to keep an eye on it.

**Comment by tlongers** [comment]
Long resolved.
