### ISSUE TITLE
Sort out active links in edit areas

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#446]
It's in dev, so I know these are placeholders:

![image](https://user-images.githubusercontent.com/2115933/45880719-d160d000-bda0-11e8-8226-509c1a7146a8.png)

Eventually,  highlight/ dim active/inactive edit groupings so the user knows where they are. Per wireframes:

![image](https://user-images.githubusercontent.com/2115933/45880741-e3427300-bda0-11e8-84b8-79b07d4d391e.png)

**Comment by tlongers** [comment]
This issue applies when person records, because `Basics` is not highlighted in red when clicked. When editing organization records, the active edit grouping is highlighted in red.

**Comment by tlongers** [comment]
It's a basic add/edit UX device to keep the user in context. Needs fixing.

**Comment by jmithani** [comment]
Proposal: Reformat the organization editing interface. 

1. Move all forms to templates/organization/forms.
2. Change the Relationships, Personnel, and Locations edit buttons link to the "create" page and associated form. This eliminates the logic in the edit buttons that tries to determine whether a "create" or "edit" page should be shown, and if "edit" which item to populate the form with.

Considerations:
- Why is the default view editing the first item? Is this necessary?
- Researchers can click the edit icon next to any record, which is a hyperlink to a newly-constructed URL. This confirms no functionality is lost with the proposed change.

Example of code organization here, focusing on editing composition. (Tests are failing as expected based on changes.): https://github.com/security-force-monitor/sfm-cms/pull/594/commits/3819b219158da5dd9aed3748aeb312fedcee08d3

**Comment by jeancochrane** [comment]
In general, sounds like a good plan! Some responses inline:

> 1. Move all forms to templates/organization/forms.

What's the advantage of this reorganization? Just for helping devs to understand what templates are for? This could be a useful reorganization but I'm inclined to scope it to a separate PR.

> Change the Relationships, Personnel, and Locations edit buttons link to the "create" page and associated form. This eliminates the logic in the edit buttons that tries to determine whether a "create" or "edit" page should be shown, and if "edit" which item to populate the form with.

I like this, makes sense to me.

> Why is the default view editing the first item? Is this necessary?

Not sure -- I agree with you that directing to "create" for foreign key fields makes a lot of sense.

**Comment by jmithani** [comment]
> 1. Move all forms to templates/organization/forms.
Definitely code legibility and ease of editing templates. When comparing the edit and create templates, I ended up using diffchecker.com to try to compare the two forms! The proposed reorg moves toward more component-like behavior. I can make this a separate PR, if useful...maybe part of a general template updating?

> Why is the default view editing the first item? Is this necessary?
A question for us to ask SFM.

**Comment by jeancochrane** [comment]
We had a quick convo out of band about the templating issue, and I opened up #597 in response so that we can track it in its own issue.

For now, I'm comfortable moving ahead with setting Create as the default view for these buttons. Tom and Tony can validate whether this is correct when they do QA, but it seems to me like a good call and it won't be too difficult to change later if it turns out we need to link to an Edit view instead.

**Comment by jeancochrane** [comment]
Just noticed that this is still buggy for personnel. The `Postings` button is sometimes active when you edit `Basics`, e.g. on https://back.securityforcemonitor.org/en/person/edit/7c35ab90-fe1e-4ec2-b27d-4764034f9822:

<img width="1085" alt="Screen Shot 2019-08-22 at 2 06 30 PM" src="https://user-images.githubusercontent.com/14170650/63542491-1841d300-c4e6-11e9-8744-4a7fec16b402.png">

We should propagate the same refactor for Organizations to Persons.

**Comment by jeancochrane** [comment]
Thanks @tlongers! Dropping this back in the hopper so we can make your recommended labelling changes -- will push it back onto your plate once it's ready.

**Comment by jeancochrane** [comment]
Text changes made! Let me know if anything looks off.
