### ISSUE TITLE
Person name fieldtype in organization personnel

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#450]
When editing a person's posting from within the organization personnel edit grouping, the name of the person should be greyed out, as it should not be possible to edit the name. Currently, it's displayed as a drop-down with only a single value:

`~/en/organization/edit/personnel/c3adbea4-73c0-4fb3-bc28-4cd1c135b424/847/`

![image](https://user-images.githubusercontent.com/2115933/45886466-2278c000-bdb1-11e8-94f5-16b6d5087e27.png)

**Comment by evz** [comment]
@tlongers Can you add sources to the name?

**Comment by tlongers** [comment]
Fixed, but raises a big new issue in #455.

**Comment by tlongers** [comment]
Concerns deprecated feature; closing.
