### ISSUE TITLE
Grey out "related organization" and "relationship type" when editing the details of a unit relationship

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#451]
When adding a new relationship from one unit to another, it is clearly necessary to specify the unit with which the relationship is being made and the fundamental nature of the relationship (`parent`, `child`, `member`). 

When editing the same relationship, however, it is not necessary: the only fields that can be edited should be `classification`, `date first cited` (and `start date?`), `date last cited` (and `open ended?`).  These are the values we're likely to want to change as our research progresses.

Although earlier I thought it might be useful, I now can't think of a situation where we would need to change `relationship type` from `child` to `parent`.  If we did, it's likely because we made a mistake entering the data in the first place. 

So: `related organization` and `relationship type` should be greyed out.

**Comment by evz** [comment]
@tlongers Bless you. This makes the logic on that page so much simpler.

**Comment by tlongers** [comment]
🙏

**Comment by tlongers** [comment]
See #455 though. The solution here creates a new problem.
