### ISSUE TITLE
Inconsistencies in how sources and clarifiers for date values are related

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#453]
I think there's an inconsistency in how sources are being handled with regards to clarifying values like `Start Date`.

When filling out date fields, we add a clarifier to them by selecting an option from the `start date` and `open ended` fields. Methodologically,  date fields and their clarifiers share the sources. So, technically their sources should be the same as the value they accompany. However, as we do not explicitly source the clarifying values, it could be logically represented in two ways: either no sources are associated with the clarifier, or the sources for the date value are associated with the clarifier.

There are some places we can look to try and figure this out. 

First, does `import_google_doc.py` link sources to clarifying values `RealStart` and `OpenEnded`

https://github.com/security-force-monitor/sfm-cms/blob/b007b2581e9168a72d3ff705b9f27518248749e6/sfm_pc/management/commands/import_google_doc.py#L340-L344
    
https://github.com/security-force-monitor/sfm-cms/blob/b007b2581e9168a72d3ff705b9f27518248749e6/sfm_pc/management/commands/import_google_doc.py#L388-L392

As far as I can tell from these snippets, no sources are associated with clarifying values. This indicates that the implementation is one of the two logically correct options.
 
Second, in the read view records the selection of a clarifying value on a date is represented by a dotted line beneath the date. The read view of the sources makes no differentiation between the date value and its clarifier:

![image](https://user-images.githubusercontent.com/2115933/45950936-8d1c3c80-bff9-11e8-8740-db2006192374.png)

This also indicates a correct implementation of our method too.

Third, the sources associated with the date fields do not show in the source picker for the clarifying fields. You can see this in the below image sequence of a date field and its clarifier, which is set to `Y` (indicating the date is a "hard start"):

Image 1: Date field and relevant sources

![image](https://user-images.githubusercontent.com/2115933/45951046-f734e180-bff9-11e8-881b-28a34e37cb83.png)

Image 2: Date clarifier and relevant sources

![image](https://user-images.githubusercontent.com/2115933/45951086-1c295480-bffa-11e8-9bcb-893cc5cedd89.png)

So far, this indicates a correct implementation: no sources have been associated with the clarifier. However, if we try to change the clarifier the system requires us to associate a source with the change. This is where the inconsistency is: is the system is storing sources  for clarifiers or not? Or is this a UI validation issue?

The simplest way to fix this is to keep the line that clarifiers like `start date` have no sources: currently we don't import them, nor do we display them, so the data entry UI shouldn't enable the researcher to add them

**Comment by evz** [comment]
@tlongers Aha! This explains [my comment over here](https://github.com/security-force-monitor/sfm-cms/issues/434#issuecomment-424822009). All of the values I was able to find that didn't have sources were the clarifiers. I can make the appropriate modifications to the form validation so that these fields do not require sources.

**Comment by evz** [comment]
Another relevant commit: fbfbe5c3359746ea39d3d184fd63fe1dff47c094

**Comment by tlongers** [comment]
Great! fixed.
