### ISSUE TITLE
Maybe come up with a data import format?

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#456]
Would it be worth it to keep some sort of remnant of the spreadsheet importer around to make it possible to ingest larger chunks of data that is already in some kind of machine readable format? I was thinking about what @tlongers was describing as the process for discovering information about Philippines and thought that perhaps if you have something that is in a machine readable format as a source that can be transformed into another format simply enough (changing a header row or whatever), would it be worth it to have some kind of mechanism that could, given a known format, bulk ingest data? Or would the act of transforming the data in the first place not really make it worthwhile?

**Comment by tonysecurityforcemonitor** [comment]
Yes! That would super helpful as there are mega sources that will make more sense to do via spreadsheet

**Comment by tlongers** [comment]
Agreed. Probably something that can quickly create a scaffolding of the organizational structural information that we can assemble fairly quickly in draft form a few ubersources. @tonysecurityforcemonitor would this cover it?

`org:name`
`sources:org:name`
`org:lastcited` (+is start?)
`org:firstcited` (+is open ended?)
`org:parent`
`sources:org:parent`
`org:parent:firstcited` (+is start?)
`org:parent:lastcited` (+is open ended?)

**Comment by tlongers** [comment]
Closing. I love our optimism here that we might escape an import process _one day_ :)
