### ISSUE TITLE
[Staging] org:classification values are munged together

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#461]
`~/en/organization/view/6d2a1260-7c0e-4d33-b7e8-c0231600fa7f/`

![image](https://user-images.githubusercontent.com/2115933/46490435-ebb69700-c7ff-11e8-9606-86e16711a213.png)

The values in `org:classification` should be distinct. Currently, they are in a single link.

**Comment by tonysecurityforcemonitor** [comment]
Fixed in Production server!
