### ISSUE TITLE
[Staging] Charts are displaying in reverse chronological

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#463]
`~en/organization/view/8795d849-88b1-481b-8510-c6c2ed54ab2c/`

![image](https://user-images.githubusercontent.com/2115933/46490750-bbbbc380-c800-11e8-8bb2-81778277a227.png)

They're in reverse order: on page load, the chart should focus on the most recent chart (2009), with the slider set to the right-most black rectangle thing (technical term, lol). Currently it loads the 1952 view first.

**Comment by evz** [comment]
@tlongers Since we did a re-import of the data, all the entities got new IDs so I'm not sure which unit this was. Do you happen to recall? I'm having trouble finding an example of something behaving in this way.

**Comment by tlongers** [comment]
No longer an issue; closing.
