### ISSUE TITLE
[Staging] Display of org:othernames is ... different

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#467]
New look at `~/en/organization/view/a7241099-150b-4423-a02e-84551079332b/#subsidiaries`

![image](https://user-images.githubusercontent.com/2115933/46491938-130f6300-c804-11e8-9d46-ac10301e2733.png)

Old  look at `https://whowasincommand.com/en/organization/view/223/#subsidiaries`)

![image](https://user-images.githubusercontent.com/2115933/46491970-2e7a6e00-c804-11e8-8cab-07f3686f202b.png)

The old look is more legible I think. There are other places where multi values are displayed as semi-colon separated where there should be a line break or a `|` separator.

**Comment by evz** [comment]
@tlongers I think this was related to the fact that we weren't splitting the aliases on semicolon when importing them (therefore that was just one big blob of text see #461). Does the current way these are displaying look OK?

**Comment by tlongers** [comment]
Yep. This is fixed. Thanks Eric.
