### ISSUE TITLE
[Staging] Person is own superior, incorrectly (and duplicated)

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#468]
`~/en/person/view/8ee7f723-5451-4932-b2a4-66383bd3b247/`

In the record for `Felipe de Jesús Espitia Hernández`, `Felipe de Jesús Espitia Hernández` is records as being his own superior for his reported stint with `5 Zona Militar`. It's also duplidated

![image](https://user-images.githubusercontent.com/2115933/46492346-2a9b1b80-c805-11e8-9299-772dab105536.png)

**Comment by evz** [comment]
Relevant commit: 12fea6662553cf6651d05446aa45abb54eb99094

**Comment by tlongers** [comment]
Is this staged or to-be-staged? I still see the issue is there on staging.
