### ISSUE TITLE
[Staging] Access data is missing from source records

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#470]
Many sources have `access date` values. These don't seem to have been imported.

**Comment by evz** [comment]
@tlongers Are you just talking about in the little popups? I fixed that in 73f5067a0140b797572d48a21e90a99ac580cd91

**Comment by tlongers** [comment]
Possibly some crossed wires here - let me try and clarify. An access point has three possible separate dates associated with it:

- `Publication date`: the date that the source was published
- `Archive timestamp`: the date that the source was archived (drawn from the archive timestamp)
- `Access date`: the date that we actually looked at the source

In the data entry widget, the value in Access Point is `Access Date` but it should be `Archive Timestamp`. 

All three dates should be included in the little pop-ups in read only view.

**Comment by evz** [comment]
Woops. Hmm, I'll need to write some code to get that timestamp out of there and saved into the access point table.

**Comment by tlongers** [comment]
Fixed.
