### ISSUE TITLE
[Staging] Area of operation and command chart not displaying 

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#471]
`~en/organization/view/60097f35-a340-4222-b24c-f62349cd1e23/`

The Area of Operation for `Negros Oriental Provincial Police Office` isn't displaying:

![image](https://user-images.githubusercontent.com/2115933/46535641-02aec500-c8a4-11e8-963c-ab3b480f9837.png)

The Parent Units chart is also empty:

![image](https://user-images.githubusercontent.com/2115933/46535772-4bff1480-c8a4-11e8-88a6-9b3a42415beb.png)

**Comment by evz** [comment]
Relevant commit 9d990fbf3d6d564d36232f6860de334e3bb9a3a0

**Comment by tlongers** [comment]
Not staged as yet?
