### ISSUE TITLE
[Staging] Font/UTF-8 issue in search results listing (related to Myanmar charset)

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#472]
`en/search/?Organization_rows=50&q=&start_date=&end_date=&selected_facets=country_ss_fct_exact:Myanmar&entity_type=Organization&selected_facets=organization_adminlevel1_ss_fct_exact%3AShan%20State`

This search gives us a display issue in the result table:

![image](https://user-images.githubusercontent.com/2115933/46535985-f9722800-c8a4-11e8-910d-01199b070adf.png)

Possibly reflects some issues in labelling of the OSM node itself ([here](https://www.openstreetmap.org/node/4163315595))

![image](https://user-images.githubusercontent.com/2115933/46536019-1149ac00-c8a5-11e8-83e1-2d0d5fcd045e.png)

**Comment by evz** [comment]
So ... yeah, i suspect that is an error in OSM. I did a bit of digging and it seems like there's a non-unicode font that's popular among various Burmese language websites (https://en.wikipedia.org/wiki/Zawgyi_font). While the code points sometimes overlap, there are also differences, so it's not strictly unicode compatible. This might be what's going on there. When I install that font on my machine, I get something that still looks garbled but more or less Burmese:

![screenshot_2018-11-12 node _namlan_ _4163315595_ openstreetmap](https://user-images.githubusercontent.com/551491/48371074-85cff180-e680-11e8-9ce4-d45fcd36f4a9.png)

**Comment by tlongers** [comment]
Thank you for digging into it. The options seem to be:
- do nothing, and assume that someone interested in reading Burmese will have the relevant fonts installed to cover this situation.
- flag the issue to the user on records where we know there may be Unicode issues
- draw down `name:en` as well as `name` and show values contingent on locale
- draw down `name:en` and only show that

What's your feel for it?

**Comment by evz** [comment]
@tlongers Lets dig into this on at our next checkin. I'm inclined to just leave it as is so as to not mess up the display for everything else.

**Comment by tlongers** [comment]
Context for the issue is relevant, but method of Location creation has changed fundamentally since we opened this. Closing for now, but antcipating more UTF-8 fun down the line.
