### ISSUE TITLE
[Staging] Location - on create new location, 403  error "413 Request Entity Too Large"

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#474]
Tried to add this relation:

https://www.openstreetmap.org/relation/151012

It ingested the metadata, but when moving to confirm adding it to staging:

`413 Request Entity Too Large`

(at `~en/location/create/?location_type=relation&location_id=151012`)

Not sure if "too large" refers to the geographical or  file-size of the OSM object itself.

**Comment by evz** [comment]
413 refers to the size of the response. That error gets generated by the web server so I can just tweak the settings there and we should be good.

**Comment by tlongers** [comment]
Relation `151012` is still too large to add.
