### ISSUE TITLE
[Staging] Locations - error if letters included in ID search

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#475]
`~/en/location/create/?location_type=node&location_id=23gegwfdwf` rightly fails, as there are no alphabetical characters in OSM object ID numbers.

Maybe validate the input into `Location ID` to ensure it's just numbers, rather than have it throw a server error?

**Comment by evz** [comment]
relevant commit f9b89cae226c9e6bbc12e09c535edc1dfb588a96
