### ISSUE TITLE
[Staging] Help page not wired in

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#480]
`/en/help/` and `/es/help/` are serving up errors.

**Comment by evz** [comment]
@tlongers This appears to be working. Can you confirm and close? Thanks!

**Comment by tlongers** [comment]
It's working on production, but I'm still getting an error on staging.

**Comment by evz** [comment]
OK, that's fixed. Rather mysteriously given that that template has not been touched in over a year.

**Comment by tlongers** [comment]
Dark magic abounds. Closing.
