### ISSUE TITLE
Country summaries - "conjunta.uuid"?

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#481]
@evz  Why these are specifically defined, and do we have to extend this practice if we reference specific records in the country overview page?

https://github.com/security-force-monitor/sfm-cms/blob/6c80c11aa055faab66fe070c16fb167cd904bec8/sfm_pc/views.py#L74-L75

They're included in the country summary:

https://github.com/security-force-monitor/sfm-cms/blob/6c80c11aa055faab66fe070c16fb167cd904bec8/templates/sfm/countries.html#L79

**Comment by evz** [comment]
For the moment, yes. This is less than optimal, I know, but the way that Django generates the URLs on this site (since we have various translated versions of the site), using that `url` template tag is the simplest way to make sure the links always point to the place that you want them to.

**Comment by tlongers** [comment]
Ah right, thanks for the explanation. Let's keep using it for now until there is time to do otherwise.

**Comment by evz** [comment]
@tlongers Can I go ahead and close this or do we want to keep it open until a better fix is in place?

**Comment by tlongers** [comment]
Close, it's not a biggie.
