### ISSUE TITLE
[production server] Myanmar not a Country filter?

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#485]
@evz - it doesn't appear as an option...

![image](https://user-images.githubusercontent.com/18744855/47449460-ac40f200-d790-11e8-97d6-51e261892d16.png)

**Comment by evz** [comment]
@tonysecurityforcemonitor This should be resolved now.

**Comment by tonysecurityforcemonitor** [comment]
It is!

**Comment by tonysecurityforcemonitor** [comment]
closing
