### ISSUE TITLE
Update Research Handbook root URL

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#487]
GitBooks has made some substantial changes to how it integrates with GitHub, causing a bit of a headache for us. I've rejigged the Handbook content, and just about got it to work the same as before. The only change, at this point, we need to make to the WWIC codebase is a tiny tweak to the Research Handbook base url:

https://github.com/security-force-monitor/sfm-cms/blob/7e3b3e7b4d3c4233e3b779a3421144f1b038a836/tests/test_settings.py#L217

And:

https://github.com/security-force-monitor/sfm-cms/blob/7e3b3e7b4d3c4233e3b779a3421144f1b038a836/sfm_pc/settings.py#L340-L341

Change `https://help.securityforcemonitor.org` to `https://help.securityforcemonitor.org/v`.

**Comment by evz** [comment]
So, just a `/v` on the end?

**Comment by tonysecurityforcemonitor** [comment]
I think so... because then the url structure is https://help.securityforcemonitor.org/v/en/ or https://help.securityforcemonitor.org/v/es/ depending

**Comment by tlongers** [comment]
Yes. With that change, people clicking on any of our help links will get to the right page. However, they will not get to the right section, because GitBook has changed how it generates urls from the documentation's filestructure. Long and short of it, if we also make the following substitutions in any code flagged with `{% help }`  all will be well:

Change `eventrec.html` to `eventrec`
Change `unitrec.html` to `unitrec`
Change `personrec.html` to `personrec`
Change `generalfunctions.html` to `generalfuntions`

(so just remove `.html` from those paths)

This fixes it the issue temporarily. Longer run, I'm doubting that GitBook is the right tool for us to manage our documentation and we should consider alternatives.

**Comment by tlongers** [comment]
Though, with the `.html` in there, the url is still successfully resolved by GitBook... with a little bit of a delay.

**Comment by evz** [comment]
@tonysecurityforcemonitor @tlongers I'm pretty sure this was resolved on Friday. Can you guys double check it and close this if so?

**Comment by tlongers** [comment]
Yep, this is resolved.
