### ISSUE TITLE
Add nofollow to the download links

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#489]
Looks like there are bots that are hitting the search results page and then following the download links to download all the results. This is causing the database to kinda just churn on that for a while and prevent other pages from really loading at all. If the bots follow the rules, we should only need to add `rel="nofollow"` to all the download links to make this work.

**Comment by tlongers** [comment]
Resolved in https://github.com/security-force-monitor/sfm-cms/pull/725
