### ISSUE TITLE
Make the edit pages do something

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#49]
- [x] Organization
- [x] Person
- [x] MembershipPerson
- [x] Event

**Comment by tonysecurityforcemonitor** [comment]
@evz The workflow for the edit functionality is a little unclear to me right now ---

1. Currently it only allows me to edit the Organization Name, Aliases, Classification or Division identifier --- I'd expect I'd be able to edit all fields related to an Organization.
2. I'm prompted to enter a source for my changes, but it seems to assume that the source already exists within the CMS.

**Comment by tonysecurityforcemonitor** [comment]
@evz Following up on this --- I see the edit function as allowing the user to correct a mistake in something they entered - it seems as it currently is functioning that it would allow the entry of entirely new data rather than go through the data entry process

**Comment by evz** [comment]
The reason why I assumed the source was already in the database is because of that: editing is mainly a correction function. I guess what we're missing there, though, is if the source itself is not correctly entered. 

It seems like what we need to do is to consolidate the edit pages into the three basic entity types: Organization, Person and Event. There are edit pages for all of the other kinds of things in the database (Sites, areas, memberships for organizations and people, etc) but, now that I took that screwy table off the home page, they are impossible to get to.

**Comment by tlongers** [comment]
:) Edit page does rather a lot now, two year on. Closing.
