### ISSUE TITLE
Workflow examples

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#5]
From Tony:

First is this article - https://web.archive.org/web/20141112091927/http://leadership.ng/news/389581/fire-guts-sokoto-military-barracks

This is a type of article that we would come across frequently. It's short, but has several important keywords (battalion, brigade, commander) that would pop up in a scrap of the website. The article names several people (including their ranks and affiliations) as well as gives information related to several organizations.

This article has the following elements:

```
Person:Name - Tasi’u Ibrahim, Adebowale Ajagbe
Organization:Name - 26 Battalion, 1 Brigade
Organization:Classification - Army, Military
PersonMembership:organization_id - 1 Brigade, 1 Brigade Garrison (this organization is not directly named, but implied by "garrison commander, 1 Brigade, Lt.Col. Adebowale Ajagbe")
PersonMembership:Role - Commander
PersonMembership:rank - Brigadier General (it is abbreviated to Brig-Gen), Lieutenant Colonel (it is abbreviated to Lt.Col.)
Organization:Site - Sokoto (for both the 26 Battalion and 1 Brigade)
OrganizationOrganization:child_id - 26 Battalion, 1 Brigade Garrison
OrganizationOrganization:parent_id - 1 Brigade
```

Depending on what else is in the database these other fields could be involved as well

```
Person:other_names - Tasi’u Ibrahim is actually a Person:other_names - the Person:Name for this person is Mohammed Tasiu Ibrahim (which only came about from cross referencing multiple articles)
PersonMembership:date_first_cited - if we didn't have any other data in the database about these people this citation would be used as the PersonMembership:date_first_cited
PersonMembership:date_last_cited - this article is actually the PersonMembership:date_last_cited for Mohammed Tasiu Ibrahim connection with the 1 Brigade (again only known because of other research)
OrganizationOrganization:date_first_cited
OrganizationOrganization:date_last_cited
OrganizationSite:date_first_cited
OrganizationSite:date_last_cited
```

Here is another article that is very common - short crime reporting that is helpful for mapping police forces: https://web.archive.org/web/20140906071324/http://www.vanguardngr.com/2014/03/gunmen-kill-tricycle-rider-aba/

```
Person:Name - Ibrahim Adamu
Organization:Name - Ndiegoro Police Division
Organization:other_names - Abia Police Command
Organization:Classification - Police
PersonMembership:organization_id - 
PersonMembership:Role - Commander
PersonMembership:title - Commissioner of Police
PersonMembership:rank - Commissioner of Police
Organization:Site - Aba (for Ndiegoro Police Division
OrganizationArea:organization_id
OrganizationArea:area_id
Area:geonames_name - Aba South Local Government Area (we'd have to double check Geonames, but this would be the Area for Ndiegoro Police Division - anytime a crime/event happens in an area and a organization responds we assume that that area is part of the organization's area of operations)
```

Similar to the article above, depending on what else is in the database these other fields could be involved as well:

```
Person:other_names
PersonMembership:date_first_cited
PersonMembership:date_last_cited
OrganizationOrganization:date_first_cited
OrganizationOrganization:date_last_cited
OrganizationSite:date_first_cited
OrganizationSite:date_last_cited
OrganizationArea:date_first_cited
OrganizationArea:date_last_cited
```

And then sometimes we'll get articles that cover large personnel shifts:
https://web.archive.org/web/20130508014613/http://www.vanguardngr.com/2013/05/ig-orders-redeployment-of-11-cps-with-immediate-effect/

Or that look back at the career of an individual:
https://web.archive.org/web/20140726071006/http://www.vanguardngr.com/2014/07/police-job-best-nigeria/

All of these articles could also result in a researcher suddenly realizing that several different people are actually the same person - like in the last article I shared. Another common thing that happens is we have an article where we stumble across information that contains quite a bit of information that we need to update several different People or Organizations.

This email has already gotten very long - but the one of the last things I'll mention is there are articles which mention both police and military organizations/people and otherwise will mention different branches of security forces.

As another note - while we are extracting a lot of data from an article that doesn't necessarily mean there is a lot of data out there - as of right now I have 7 different sources for the Organization:Site for the 1 Brigade - and that is after a scan of articles from Nigerian newspapers from 2002 to 2016. To put that in more perspective, a brigade is a major military unit, ranging from roughly 3000 to 5000 soldiers.

**Comment by evz** [comment]
To me, this suggests a data entry wizard. Something that a researcher could use to start with a source or an event and walk through the process of creating the various entities contained within it.

**Comment by tlongers** [comment]
Closing.
