### ISSUE TITLE
[Staging] Newly added sources appear in data entry typeahead but not in main search results

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#504]
Some weirdness when adding sources:

1. Add a source and save it.
2. To go the main search for sources and search it on title: it won't be returned in the results.
3. Edit any record, and search for the source in the source picker's typeahead: the source will appear in the results.

**Comment by tlongers** [comment]
Duplicate of #566

**Comment by tonysecurityforcemonitor** [comment]
Tested via #566 and fixed.
