### ISSUE TITLE
Geometry download format

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#510]
@tlongers Over in the description for the bulk downloads, you mention that you'd like to include GeoJSON and KML versions of the downloads that include location information. I'm having a bit of trouble rolling that up into a single file per country. For instance, my laptop (which has far more memory than either of the servers that we are running the site on) runs out of memory when trying to generate the file with the AOOs for organizations in Mexico. It seems like perhaps the next best thing for the geometries would be to roll it up by organization and then perhaps bundle the whole thing into a zip file or something. A downside there would be then you'd end up with a thousand or so files in the case of Mexico. 

I'm not super sure where to go from here. Any thoughts?

**Comment by tlongers** [comment]
Thanks @evz. I think the key to make that work would be to have a quick method of selecting groups of organizations (e.g. by security force branch, command tree etc) about which to grab the geo, which is more work that we have time for right now.  As long as we have OSM ID numbers in the downloaded we can grab the relevant geometries ourselves. So, put this feature on ice for now.

**Comment by evz** [comment]
OK sounds good.

**Comment by tlongers** [comment]
No longer needed.
