### ISSUE TITLE
[Staging] The two UNMILs

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#515]
`~en/organization/view/f209b6b8-c03b-46c5-9ff1-f00474fbb74c/` - UNMIL as a org in Nigeria
`~en/organization/view/69a42593-92ed-4a13-9306-4d90c94fe71d/` - UNMIK as an org in Liberia

The latter is correct, but the members of this missions are attached to the one designated to Nigeria. Do we have an importer issue here? @tonysecurityforcemonitor

**Comment by tonysecurityforcemonitor** [comment]
@tlongers - yep it's an importer issue we have the same issue in WWIC, expect for UNMIL it seems!

https://whowasincommand.com/en/organization/view/453/
https://whowasincommand.com/en/organization/view/1576/

We can fix once the data entry is up and running :)

**Comment by tlongers** [comment]
Gah.... one for @evz I think.

**Comment by evz** [comment]
@tlongers I had a conversation with @tonysecurityforcemonitor about this and I'm struggling to figure out where (I suspect it might have been in an email exchange). Basically what is going on is that, in the case where an organization is a member of another organization, we don't have a division ID in the spreadsheet for the umbrella organization. The importer just looks up that organization using the division ID of the organization that is the member. If it doesn't find anything, it makes a new, possibly spurious, organization. This, obviously, doesn't work when organizations are members of organizations that are not based in the same country. In the earlier conversation, I seem to remember this coming down to the fact that there were only a few umbrella organizations that would be effected and we might be able to just wait to fix them in the edit interface. If that's not the case and we want to fix it in the importer, I think the easiest thing would be to add the correct division ID for the umbrella organizations into the spreadsheet and I can adjust the importer accordingly.

**Comment by tonysecurityforcemonitor** [comment]
I think it will be easier to just fix in the edit interface rather than fiddling with the importer at this stage in the game.

**Comment by tlongers** [comment]
Fixed by designating the country of the umbrella org, and displaying the origin country of units that are members.
