### ISSUE TITLE
Download functionality - substance of downloads

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#516]
Thanks for implementing the downloads @evz - here's my notes on what I found. 

- it's great seeing these slices of the data: it'll save us a *lot* of time in analysis
- There's a general issue with the values in `real_start` fields: they should be `Y` or `N` not `t` or `f`
- In personnel, you split out the date values into their parts, but in in org dumps you didn't. I really like having the parts - it saves us a lot of yak shaving in dealing with the fuzziness.

## Usability
- put the country name (or ISO shortcode)  in the download filename

## Basic
- `org:notes` is missing from the download
- data in the column `start_date_of_organization` is `f` or `t` or `empty`: should be `Y` or `N`

Optional augmentation wish-list - a set of QA things:
- org_last_updated: timestamp of the last update on the org
- org_has_sites: number of sites
- org_has_areas: number of areas
- org_has_parent: number of immediate parents
- org_has_child: number of immediate children
- org_has_memberships: number of orgs in which it is memberships 
- org_has_personnel: number of personnel posted to the 

## Parentage

- same issue with `t` and `f` as values in `real_start_date`  field

## Memberships

- `member_name` country ID should be included
- is the country of the org in which others orgs are members subject to the value set at the point of download? For example, if a unit from Nigeria is a member of a mission from Liberia, would it appear in the Nigeria download or the Liberia one? There may be an importer or modelling issue here (see #515)
- note field from  `orgs` is missing here; also perhaps

## Sites

- country ID of site is missing
- same issue with `t` and `f` as values in `real_start_date` field

Augmentation wishlist:

ingest_date: date the location was pulled down from OSM

## Areas

- country ID of site is missing
- same issue with `t` and `f` as values in `real_start_date`  field

Augmentation wishlist:

ingest_date: date the location was pulled down from OSM

## Personnel

- notes field is missing
- person country is missing

Augmentation wishlist:
- person_last_updated 

# Sources

- Although access points are correctly defined, the page numbers that create the access point are missing. A good example here  is source `0717c474-c48e-4d9e-a9fc-a3bf09d5203d`, which has 19 access point all of which are defined by page number differences as opposed to archive URL differences.
- There's no UUID for publication: if this is available in WWIC's db, please include it. We assign a UUID manually in our current source table.

Augmentation wishlist:
- datapoint_count: number of datapoints the source evidence

**Comment by jeancochrane** [comment]
For the dev team's reference, here's the PR that this issue is referencing: https://github.com/security-force-monitor/sfm-cms/pull/512/files

**Comment by jmithani** [comment]
I broke up this issue into basic functionalities we need to add/adjust (#602) and a wishlist (#603). The only other questions that remains exclusively in this issue is this:

> is the country of the org in which others orgs are members subject to the value set at the point of download? For example, if a unit from Nigeria is a member of a mission from Liberia, would it appear in the Nigeria download or the Liberia one? There may be an importer or modelling issue here (see #515)

**Comment by tlongers** [comment]
Closing; we've iterated past this point with respect to downloads.
