### ISSUE TITLE
Create initial data for Violation Type

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#52]
As mentioned in #26 @tonysecurityforcemonitor provided a spreadsheet that includes the fixed listing of violation types and their translations that we'll need to worry about. Let's turn these into an initial data file that Django can consume: https://docs.djangoproject.com/en/1.9/howto/initial-data/

**Comment by tonysecurityforcemonitor** [comment]
@evz And just in case I didn't say it before - the only violations we code are the "top level" ones - "Violations of the right to life", "Violations against personal integrity", "Violations against the right to liberty", etc.

@jpmckinney @tlongers I just realized --- should we have the huri_code related to each entry somewhere under the hood to make it easier to mashup the Monitor's data with other projects?

**Comment by jpmckinney** [comment]
@tonysecurityforcemonitor Sounds fine to me. It's easy to add an extra field to the model to track that code. I assume there is only one code per entry?

**Comment by tonysecurityforcemonitor** [comment]
@jpmckinney Right now an event can have multiple violation types that are semicolon seperated - so that an event can both Violations against personal integrity, Violations against the right to liberty. Each violation type only has one unique code related to it in the HURIDOCs standard though.

**Comment by evz** [comment]
Closed with d65a8993f78f30e6c5432955d25284154b1035ec
