### ISSUE TITLE
[staging] Police in Alexandria

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#523]
Does not return any results

**Comment by tlongers** [comment]
Think this has [been fixed](https://whowasincommand.com/en/search/?q=&start_date=&end_date=&entity_type=Organization&selected_facets=countries_exact:Egypt&selected_facets=classifications_exact:Police&selected_facets=sites_exact%3AAlexandria%20Governorate). Closing.
