### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#53]
@tonysecurityforcemonitor @tlongers  To think about - what displays do we want to see in the initial dashboard after logging in?

**Comment by evz** [comment]
Are there any thoughts on this yet?

**Comment by tonysecurityforcemonitor** [comment]
**Tools for tracking workflow:**

1. See total count of sources added by a user
2. See count of sources added by a user in a given period of time (last week, last month, to date)
3. Total count of People, Organizations, and/or Events per country/division_id
4. Total count of People, Organizations and/or Events for the entire Monitor

**Reviewing work**
1. Having some workflow to approve an entry - and seeing which user submitted it for review/approval
2. It seems like the Monitor will implement a hard versioning/update schedule (lets say quarterly updates) - I would see this being able to review and basically enter data without automatically updating the front-end UI as part of this.

**Would be nice - but probably hard to implement now**

1. Seeing a list of entries that haven't been updated in awhile - basically some ability to see what entries for a country/division_id might need attention. Having the ability to "check off" ones that have been reviewed - but nothing new had been found would be great.
2. Count of Organizations tied to geographies- It would be really helpful to be able to easily answer a common question - example - How many police stations do we have data on in Lagos State? We can sometimes find a total count of a "type" of organization -meaning that there will be multiple organizations with the same word or several words in its Name - i.e. Police Station, Battalion, Brigade, etc. We sometimes will know how many of those exists in a ADMN1 or ADMN2 or just the country as a whole. Being able to query the database to get a sense of how complete the data is would be super helpful - but I suspect somewhat hard to implement.

**Comment by tlongers** [comment]
@tonysecurityforcemonitor There's a bundle of stuff in this that needs unpicking: 

* Roles and permissions: data review, workflow management and review/approval of entries. I'm not sure how roles and permissions are conceived in the tool as yet. @evz what do we have there already for defining and management this stuff?
* Reporting: finding and working through stale data, counting attributes are useful for analysis and data quality assessment. Wouldn't that kind of query building be some kind of "advanced search" or somesuch? Would also need to consider export functions -perhaps some of this analysis is better done outside of the tool.
* Release management: organising and scheduling the release of new and updated data (for example, each month) will require a lot more thinking through. There are good policy reasons for it. I would be interested in throwing some ideas around about how to make it work in a user focussed way. 

Before thinking about what goes on the user homepage, can we get a sense of what sort of functionality from the above list we have available to pull from?

**Comment by evz** [comment]
@tlongers @tonysecurityforcemonitor Thanks for packing and unpacking this :wink: 

* **Workflow tracking** I can conceive of very simple queries that will return those numbers and I'll go ahead and stick those up front on the home page for now and maybe make the "Add source" thing more prominent while I'm at it. Actually, now that I think through it a bit, the queries you have listed in the "Would be nice" section are not actually that hard, either. 

* **Roles & permissions** This is something that we'd probably want to really put some thought into before attempting to implement. It tends to be one of those things that seems simple but can get hairy quickly. That said, it might be as simple as toggling an "ok to publish" (or some such) flag on a row in the database and only allowing certain groups of users to toggle it. We could also use that flag to figure out which things to serialize via the API, etc. Anyways, lets talk more about that.

* **Release management** Again, might be as simple as toggling a flag but we'll want to talk through it a bit.

I'll open issues for these last two and the reporting function, which I feel like will need more discussion to properly flesh out.

**Comment by tlongers** [comment]
Stale; closing.
