### ISSUE TITLE
[PR544] person:role value fails to update when edited from within unit record, but updates fine from person record

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#548]
Related to PR #544 

1. Edit a unit to which at least one person is linked.
2. Navigate to the `Personnel` tab.
3. Update the value for `person:role` and save.
4. The update is not saved.

An update to `person:role` can also be achieved through the person record, where it works just fine.

**Comment by tlongers** [comment]
Same error pattern when attempting to update `start date` and `end date` for postings.

**Comment by tlongers** [comment]
Still an issue.

**Comment by jmithani** [comment]
Addition: Testing locally, this affects all fields tied to personnel. Attempting to change any of them from within the unit fails.

**Comment by tlongers** [comment]
I made test updates to all the fields  in a posting, following the instructions per the PR. The issue is fixed.
