### ISSUE TITLE
[PR544][Question] Should a person record be included in downloads if that person does not have a role in a unit?

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#549]
Currently, a `person` can be linked to a `unit` without specifying `person:role`. If this isn't specified, then the record will not be included in the download. @tonysecurityforcemonitor do you think this is correct behaviour can you recall any cases where `person:role` has not and would not be specified?

**Comment by tonysecurityforcemonitor** [comment]
@tlongers - If possible the download function should download all persons related to an organization. It's fairly rare for a person not to have a role, though it does happen. There are just cases were a source relates a person to an organization but their role is unclear/not mentioned.

It's not mission critical at this moment, per se, but it would be good to have that functionality at some point.

**Comment by tlongers** [comment]
May return to downloads, but this is stale at this point.
