### ISSUE TITLE
Get internationalization working as expected.

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#55]
Translations for the interface pieces as well as translations for the values that are stored in the database are not quite working yet but there is a lot of code that is included in the complex-fields package that seems to be an attempt at making this easier to manage. One thing that's kind of a wild card at the moment is the Arabic translations for things stored in the database. Just copy/pasting them in there reverses the direction of the letters which is a problem. I suspect having an actual Arabic keyboard layout might solve this.

**Comment by tlongers** [comment]
@tonysecurityforcemonitor would be worth looping in an Arabic-language  contributor to assist with this aspect of the work

**Comment by tonysecurityforcemonitor** [comment]
@evz @tlongers I'll have a couple of people that could potentially assist with the language side of things - but not really on the database issue. Let me know how best to utilize their skills to assist here.

**Comment by tlongers** [comment]
Do we have an interface translation yet? Would be good to have one for @evz  to work with. Also, what seems sensible to non-native speakers may look and operation in a ridiculous way for native speakers. As soon as basic input is technically possible in Arabic, let's bring an Arabic-speaking colleague in to test.

**Comment by tlongers** [comment]
Resolved. This product is fully internationalized :)
