### ISSUE TITLE
[PR544] Server error when accessing person postings, immediately after edit

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#554]
`/en/person/edit/postings/be5f9e0f-f01e-46aa-8596-3bfac91ef34e/1956/`

Updated the start and end date for the posting of `Tier 2 Commander` to `Tier 2 Unit`. The save was successful. When I attempted to edit the record again, selecting `postings`, a server error occurred.

**Comment by tlongers** [comment]
The precise record used to illustrate this issue has gone,but the issue can be recreated. 

1. Create a new org.
2. Create a new person.
3. Edit the org, go to personnel, and link the newly created person to the org. Save
4. Visit the newly created person, edit, go to postings - you'll get a server error.

**Comment by derekeder** [comment]
I tried re-creating this error several times by following the steps in https://github.com/security-force-monitor/sfm-cms/issues/554#issuecomment-513260685, but was unable to.

Can we confirm this bug is still happening?

**Comment by tlongers** [comment]
Thanks @derekeder I tried it again on staging and it's not happening anymore.
