### ISSUE TITLE
Search index not updating when new source added

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#566]
Tested on staging server:

1. Create and save source with name "Test Source". Keep a record of the UUID generated for the URL
2. Validate source exists by visiting URL in new browser window.
3. Search "Test Source", faceting for sources.
4. Source is not found.

**Comment by tonysecurityforcemonitor** [comment]
This appears to be resolved.

Tested with: "New GOC takes over at 1 Division, Kaduna". Added source and result displayed in search results.

![image](https://user-images.githubusercontent.com/18744855/63614705-b3ec4580-c5b1-11e9-9b5d-1af8395f5c3d.png)

**Comment by tlongers** [comment]
Agreed. Fixed.
