### ISSUE TITLE
Extend facets for sources - but with what?

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#568]
What do we need to search/filter for with sources? We currently have three active facets; I think adding a facet for the number of access points would be useful for QA work. @tonysecurityforcemonitor what do you think?

General filters

- [x] Publication Date (in general filters)
- [x] Country of Publication (in general filters)

Source specific filters

- [x] Publication Name 
- [ ] Number of access points
- [ ] others?

Related to #392

**Comment by tonysecurityforcemonitor** [comment]
Source Name (i.e. the title of an article rather than the Publication Name of Reuters)

**Comment by tlongers** [comment]
>Source Name (i.e. the title of an article rather than the Publication Name of Reuters)

That would create facets with 1000s of entries, so we let search box takes care of searching titles. Facets are to narrow down titles by one or more criteria. I'm tempted to add "year archived"?

**Comment by tlongers** [comment]
Settled on just `publication:name`. May revisit but closing for now.
