### ISSUE TITLE
division_id

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#57]
@evz @tlongers - Currently I don't think we have the division_id fields implemented in the data entry:

- Person:division_id
- Organization:division_id
- Site:division_id
- Area:division_id
- Event:division_id

It might be an idea to place it in the data entry workflow at the start so that when the autocomplete/search function that happens when entering a Person, Organization, Site, Area or Event occurs it is only looking through existing entries that share the same division_id.

It would help avoid a situation where a researcher inputing data for the 1 Battalion of country X accidentally instead adds details from their source to 1 Battalion of country Y

It could also save on workflow time where a researcher almost 99% of the time will be entering information on People, Organizations or Events in one country.

**Comment by evz** [comment]
This is probably something that can automatically populate once a the user gives us a country. Maybe it makes sense to collect that when we are getting info about the source? We have a "publication country" select box already. Maybe we could also get a "activity country" or something (I'm terrible at naming things)?

**Comment by tonysecurityforcemonitor** [comment]
@evz That would work almost 99% of the time -- the only issue is with sources that discuss peacekeeping operations because the peacekeeping force would have a division_id of the country its operating in.

For example - a source describes how the 1 Battalion (based in Nigeria) is sending some soldiers to participate in UNMIL (mission in Liberia). We'd have both the 1 Battalion and UNMIL as Organizations in the Monitor, but with different division_ids.

**Comment by evz** [comment]
@tonysecurityforcemonitor The way I'm approaching this is to just add the appropriate field to each of the effected forms. That should allow for a pretty decent amount of flexibility. I'm also just using an autocomplete widget to generate the division IDs so users won't have to look them up separately.
