### ISSUE TITLE
Source picker: archive timestamp value should be used in as access point hyperlink text

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#570]
`~/en/organization/edit/composition/76cd0d81-1c70-4630-bf8b-5876868942ee/4/`

Two access points for the same source are correctly displayed as evidence for this data point: 

![image](https://user-images.githubusercontent.com/2115933/57772730-207fba80-770e-11e9-9b6d-86811fcb36aa.png)

However, data are in the wrong place so we can't tell the difference between them:

<img width="564" alt="WhoWasInCommand" src="https://user-images.githubusercontent.com/2115933/57773302-9d5f6400-770f-11e9-926c-ecfc5b532bd3.png">

**Comment by jeancochrane** [comment]
The archive timestamp introduced in #587 should make this work easier.

**Comment by tlongers** [comment]
Nice work. The only change needed here is to set `target="_blank"` for the Access Point links, so they open in a new tab.

**Comment by jeancochrane** [comment]
Good catch! I just deployed 32ed413257d61ea73422a2b79205407a40cbad1e to add `target="_blank"` to access point links, let me know if all looks good.

**Comment by tlongers** [comment]
Yes, that fixes it. Thanks @jeancochrane.
