### ISSUE TITLE
Add ability to remove an access point, whilst keeping the source

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#577]
Currently we can add access points but not remove them. Check if the function exists to remove, and figure out a safe delete UX.

**Comment by tlongers** [comment]
This may be helpful: https://github.com/security-force-monitor/sfm-cms/issues/420#issuecomment-423573653

**Comment by jeancochrane** [comment]
Blocked by #420.

**Comment by tlongers** [comment]
Works well, and safeguards against deleting any  access point that is associated as evidence for another entity.
