### ISSUE TITLE
Add cancel button to new source creation page

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#578]
`~en/source/create/` needs a cancel button that either return the user to the page they were looking at before, or takes them home.

**Comment by tonysecurityforcemonitor** [comment]
Cancel button works!

**Comment by tlongers** [comment]
In the PR, the test instructions is to return the user to the previous page they were looking at before `edit` was selected.  As implemented, `cancel`  has two different behaviours, depending on the user's starting point:

- Clicking `cancel` from `~/source/update/[source_uuid]` returns the user to `~/source/view/[source_uuid]`, which is in line with the PR's aim.

- Clicking `cancel` from `~/source/create` returns the user to the `~/search/?entity_type=Source` irrespective of the page they were on when they started to create a new source. Is this intended behaviour?

**Comment by jeancochrane** [comment]
@tlongers At first we implemented it to send the user directly back to the page they were looking at before, but I found that to be confusing from a UX perspective. You can see some of our discussion about it here: https://github.com/security-force-monitor/sfm-cms/pull/585#discussion_r311100651 I think this is more in line with Create -> Cancel behavior across the app, which generally takes you to the search page for the entity that you're creating, but we could rethink that paradigm if you feel like it's worse UX.

**Comment by tlongers** [comment]
That all makes sense, thanks Jean. Closing this again.
