### ISSUE TITLE
Use field label not table fieldname in essential field warnings

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#581]
Label and warning should match:

![image](https://user-images.githubusercontent.com/2115933/61544066-8fde9700-aa3c-11e9-9deb-19e3c35b062d.png)

This exposes the table fieldname and not the label used in the UX. Check localization too.

**Comment by tlongers** [comment]
Same issue area as #574

**Comment by jeancochrane** [comment]
@derekeder I'll be curious to know how widespread this problem is. If it turns out that almost all of the error messages are showing the fieldname instead of the label, we may want to take a step back and consider what our options are for fixing it (i.e. whether we have to comb through all the templates and change them or whether there's a more modular fix we can put in place).

**Comment by derekeder** [comment]
Good point @jeancochrane. I'll review and document where I encounter this issue and we can take it from there

**Comment by jeancochrane** [comment]
Great 👍 All of the errors I've encountered so far have seemed to originate from one of the `BaseForms` in `sfm_pc.forms`, which hopefully should mean that this is already well-modularized.

**Comment by tlongers** [comment]
When a validation error is thrown, the form refreshes which wipes the values that caused it. I think this is brutal but good  - it means there is no ambiguity about what's saved and what's not saved. Alternatives would be to keep the erroneous value but highlight it somehow, but this adds more things to learn about an already complicated mechanism so I don't think it's necessary. However, after the form is refreshed because of a validation error, the edit focus (and therefore the source picker) is focussed on the first field in the form. It would be better usability to focus the source picker on the field that triggered the error, so the user can keep rolling.  Is that a simple, or time consuming addition to make?

**Comment by jeancochrane** [comment]
I agree that would be a real usability improvement @tlongers. I think we could do it, but it wouldn't be a simple change. We have a convenience function, `loadSources`, that triggers the source picker for a certain input when each page loads. This function is called separately in every create/edit template, e.g.:

https://github.com/security-force-monitor/sfm-cms/blob/fb7123f08d2db2ec304fea06d0b6cd40f58710cb/templates/organization/create-composition.html#L211-L213

There are two major challenges to adjusting this function to target inputs with validation errors:

1. The function is called separately in every template, so we'd either have to adjust every template or refactor them to share common logic
2. In general form field elements are defined in bare HTML across all create/edit views (as opposed to being automatically rendered by the Django `Form` object) so we can't easily make a principled link between the items in the `Form.errors` link and the corresponding HTML input elements when we call `loadSources` 

I think if we did a major refactor along the lines of https://github.com/security-force-monitor/sfm-cms/issues/597, we could make it much easier to support this kind of change by sharing more common template code and pushing more of the rendering logic onto the `Form` object. Short of that, it's hard to imagine a time-efficient solution.

**Comment by tlongers** [comment]
Thanks for the explanation @jeancochrane. It's good as is for now, and when we do a usability round we can return to this.
