### ISSUE TITLE
Refactor Create and Edit templates to share form elements

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#597]
As far as I can tell, all of the Create and Edit templates display the same form elements, yet in the templates themselves these form elements are usually fully duplicated. This makes maintaining the forms difficult, as @jmithani pointed out in https://github.com/security-force-monitor/sfm-cms/issues/446#issuecomment-521583696, because

1. Any time you make a change to a form element you have to make sure it's also changed in the other template
2. It's difficult to tell which parts of the Create and Edit forms are actually different, and which parts are just copy/pasted out of convenience

To me, this is probably the biggest code-quality issue within the data entry system.

We should try to get a better sense of why this duplication exists and if there's a good reason to preserve it; if not, we should refactor the templates so that as many identical form elements as possible are shared between Create and Edit templates, with the goal that each template should only implement functionality specific to that template.

**Comment by jeancochrane** [comment]
Related: it would also be great to gain an understanding of why we render so many form elements by hand instead of making the Django `Form` objects automatically render them. If we can push more logic off to the `Form` objects we'll be able to dramatically reduce the surface area for bugs across the data entry system.

**Comment by tlongers** [comment]
Closing. Useful issue for background if we revisit data creation in WWIC, but for now there's nothing actionable here.
