### ISSUE TITLE
Removing sources when removing data

### ISSUE THREAD

**Issue by derekeder** [security-force-monitor/sfm-cms#598]
While investigating https://github.com/security-force-monitor/sfm-cms/issues/553, I noticed that changing the value of `rank` to blank without removing the corresponding source caused an error. Here's how I reproduced:

1. Go to a unit with personnel attached to it, and edit it.
2. Go to `personnel` and pick a posting with a rank value.
3. Clear the value for rank (select `------`), but **do not clear clear the source**, then save.
4. You will get a server error: `Manager isn't accessible via MembershipPersonRank instances` on https://github.com/security-force-monitor/sfm-cms/blob/master/sfm_pc/forms.py#L393

There are two approaches to address this:

1. Add form validation that stops the user from saving until they remove a source related to a blank/removed value
2. Automatically delete any sources for a value that is set to blank/removed

Which approach do we prefer?

**Comment by tonysecurityforcemonitor** [comment]
> 1. Add form validation that stops the user from saving until they remove a source related to a blank/removed value

This makes the most sense to me - as in general we edit something to change the value in the field, and want to leave the sources the same (we realize that we misread the source, or had made an error in what we input into a field). So it seems like there is a risk of accidentally hitting save too quickly without updating the field. This mechanic would be a useful reminder.

Less often we completely remove a value from an organization, person, or incident. In that case I think path #1 is a good check in that process as well.

**Comment by jeancochrane** [comment]
@tonysecurityforcemonitor Is it OK if we get started on this? Seems like a pretty clear bug to me. I can drop it in the hopper for this project if so.

**Comment by tonysecurityforcemonitor** [comment]
@jeancochrane - yes absolutely!

**Comment by tlongers** [comment]
Closing.
