### ISSUE TITLE
Downloads—Augmentation wish list

### ISSUE THREAD

**Issue by jmithani** [security-force-monitor/sfm-cms#603]
Splitting off from #516 

- org_last_updated: timestamp of the last update on the org
- org_has_sites: number of sites
- org_has_areas: number of areas
- org_has_parent: number of immediate parents
- org_has_child: number of immediate children
- org_has_memberships: number of orgs in which it is memberships
- org_has_personnel: number of personnel posted to the

- Memberships: note field from orgs is missing here; also perhaps
- Sites: ingest_date: date the location was pulled down from OSM
- Areas: ingest_date: date the location was pulled down from OSM
- Personnel: person_last_updated
- Sources: datapoint_count: number of datapoints the source evidence

**Comment by jmithani** [comment]
@tlongers a few of these look incomplete—would you mind updating the requests when you get a chance?

Also, is this an augmentation or necessity? "In personnel, you split out the date values into their parts, but in in org dumps you didn't. I really like having the parts - it saves us a lot of yak shaving in dealing with the fuzziness." (Working on prioritizing!)

Thank you!

**Comment by jmithani** [comment]
cc @tonysecurityforcemonitor (for the above comment!)

**Comment by tlongers** [comment]
@jmithani Thanks for pulling these out.  It's useful to see these all in one place! I see what you mean about them being incomplete too; I think they all need looking at carefully see if there is still a case for each of them. 

For now, however, they are not a priority.  Down the line we can return to the list of possible augmentations  (and also think about some of the challenges we had getting other data out of the system e.g.  - https://github.com/security-force-monitor/sfm-cms/issues/510). So let's give the current focus to getting the download requirements listed out in https://github.com/security-force-monitor/sfm-cms/issues/602  bulletproof per the goals of [Iteration 1: Squash blockers and deploy bulletproof CRUD on a user-testable system](https://github.com/security-force-monitor/sfm-cms/projects/4).

**Comment by tlongers** [comment]
Resolving; we may revisit downloads but no need to keep this open.
