### ISSUE TITLE
Search results: New person not displaying

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#608]
Process:
1) I created a new source "New GOC takes over at 1 Division, Kaduna"
2) I added the person Faruk Yahaya
3) Searching for the person did not display results (though 11 results were supposedly found)

![image](https://user-images.githubusercontent.com/18744855/63615043-6c19ee00-c5b2-11e9-9c26-36b4c282c658.png)

Blocked from being able to add additional details to this person (postings, ranks, etc)

**Comment by jeancochrane** [comment]
Weird, I'll take a look. Another case where I can do this in dev, so I think something's up with the staging server.

**Comment by jeancochrane** [comment]
OK, I think I know what's going on here. There's a bug we noticed while testing #606 where if a new person doesn't have a posting the app won't be able to render the template for the Personnel search results. In dev it throws a big error page, but it looks like in staging/production it just fails silently.

@tonysecurityforcemonitor I added a dummy posting for this person and was able to confirm the page loads now. You should be able to adjust the posting to something sensible if you'd like. In the meantime, I'll update #606 to specify that it should close this issue.

**Comment by tlongers** [comment]
I can't replicate the issue, but that may because it is fixed. @tonysecurityforcemonitor can you spot any remnant of it?

**Comment by tonysecurityforcemonitor** [comment]
This appears fixed - I created a person with no posting and was able to see them in the search results : )
