### ISSUE TITLE
Person Save and Continue versus Save

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#609]
Adding this a note for future iteration, not a blocker but a good next step when adding a person.

Currently, when adding a person a user can enter in the fields in the "Basic" screen and then the user has the option to hit "Save and Continue Editing" or "Save".

Both options take the user to the person's page where, where as I'd I want "Save and Continue Editing" to allow me to then edit the Person's "Postings" screen. I see the logic of "Save" meaning the user is done editing and should be taken to the profile page of the Person, so that should stay as is.

**Comment by tlongers** [comment]
Superseded; closing.
