### ISSUE TITLE
Source display problems for Incidents

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#616]
Two problems with the source displays for Incidents:

- There is no footnote for "Perpetrator classifications"
- Clicking on any footnote on the page only renders the sources for the description

Once we can save different sources for these attributes in https://github.com/security-force-monitor/sfm-cms/pull/612, we should be able to properly display these sources.

**Comment by tlongers** [comment]
There is some relevant discussion about this on https://github.com/security-force-monitor/sfm-cms/issues/605#issuecomment-529537249

**Comment by jeancochrane** [comment]
Closing this as it's a feature not a bug!
