### ISSUE TITLE
Search for Source during data entry does not display results

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#619]
I added a new source Deployment of troops in South-West and confirmed it was saved to the staging site via a search

![image](https://user-images.githubusercontent.com/18744855/64178304-3afdb100-ce2f-11e9-8b6e-dc7bb5ecdb32.png)

However - when I search for this source while adding a new person no results are displayed:

![image](https://user-images.githubusercontent.com/18744855/64178395-6385ab00-ce2f-11e9-9000-60c419e230d2.png)

I'm not sure what the issue is, I noticed when searching for the source the full title doesn't display results either (below). I'm only able to find it when searching for part of the title (first screenshot)

![image](https://user-images.githubusercontent.com/18744855/64178574-b5c6cc00-ce2f-11e9-827d-3758a8584903.png)

**Comment by jeancochrane** [comment]
@tonysecurityforcemonitor I believe this discrepancy is occurring because the `Add sources` search box is actually searching for access points, not sources. Does the search show up as you expect when you add an access point to the new source?

**Comment by tonysecurityforcemonitor** [comment]
@jeancochrane - ah ha! Adding an access point resolves the issue on both points. Thanks for quick response!
