### ISSUE TITLE
Question: Organization Selector for Person

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#620]
Editing a test person for Nigeria raised a question for me on the dynamics of the selector for the Organizations field for a person.

As I start to add an organization (starting with just a "2") I'm given options for any organization, including those outside of Nigeria (their division_id is another country), which is good.

![image](https://user-images.githubusercontent.com/18744855/64181277-296ad800-ce34-11e9-9579-b046472793d4.png)

As I enter more into the field the selection narrows, but it exposes a potential issue, I'm not sure which "2 Battalion" I'm selecting. Is it the [2 Battalion of Nigeria](https://whowasincommand.com/en/organization/view/1551e1da-0a56-4814-9815-c563710ffa84/) (the one I want) or the [2 Battalion of Saudi Arabia](https://whowasincommand.com/en/organization/view/14431c2e-bdbf-42c1-9333-d65e24881d6d/) (which was not my intention).

![image](https://user-images.githubusercontent.com/18744855/64181829-320fde00-ce35-11e9-8def-e4f2d04630b8.png)

The simplest fix in my mind would be to add the division_id for the Organization after the name, basically expanding the amount of information in the field available to the user so that they can select the correct organization.  But obviously there are other paths as well.

**Comment by jeancochrane** [comment]
Great question! I like the idea of modifying the display of the unit name search results to also show their countries, and I think it would be a pretty simple tweak. My only question is: Does name + country always uniquely identify a unit, or are there some cases of two units in the same country with the same name? If it's possible to have two units share the same name in the same country we may want to think about what other additional information we can show here to help sort through the units.

**Comment by tonysecurityforcemonitor** [comment]
> My only question is: Does name + country always uniquely identify a unit, or are there some cases of two units in the same country with the same name?

Good question! In those cases we've added something to the name to help distinguish them. A good example is the multiple Central Police Station units in Nigeria:
https://whowasincommand.com/en/organization/view/7eedbf8f-364e-4274-8b89-d920054a7126/
https://whowasincommand.com/en/organization/view/6491e43f-f717-4a34-8c92-d5c2582d08b5/

I think we should continue this practice so that two units of the same country can never share the same name (even though in theory UUIDs would mean we don't have to add to a unit's name, I've found those geographic or other additions really help to distinguish between units at a glance).

**Comment by jeancochrane** [comment]
Great, that's good to know! In that case, I think the right solution is to display the country name or division ID alongside the unit name in the search results.

**Comment by tlongers** [comment]
Agreed, good call - suggest including the full country name rather than the ISO code.

@tonysecurityforcemonitor would it also be worth including `org:classification` too, or would this be overkill

**Comment by tonysecurityforcemonitor** [comment]
The full country name will be great! 

I don't think 'org:classification' will help us since in these cases the classification will very likely be the same (as they are in this example).

**Comment by jeancochrane** [comment]
Awesome! For future reference, the code that generates the autocomplete results is here:

https://github.com/security-force-monitor/sfm-cms/blob/8c523561139593b50003c5a2e5ef43d76c74ccd2/organization/views.py#L685-L708

As you can see, we already pass the country data through in the JSON response, we just don't render it (since Select2 will render whatever is assigned to the `text` key of the results dictionary).

**Comment by tlongers** [comment]
Stale issue; closing.
