### ISSUE TITLE
Setup - warning when running update_countries_plus

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#623]
When working through the updated installation instructions I got this warning when running `python manage.py update_countries_plus`:

```
WARNINGS:
languages_plus.Language.countries_spoken: (fields.W340) null has no effect on ManyToManyField.
```

Is there any  significance to the warning, and does it affect the install at all?

**Comment by jeancochrane** [comment]
This is an artifact of a dependency of `django-countries-plus`, the library that we use for parsing and displaying countries. It's a benign warning indicating that they tried to set `null=True` for a `ManyToManyField` but that doesn't do anything in Django. It looks like the library [was patched back in 2015](https://github.com/cordery/django-languages-plus/pull/5) to fix the warning; we could either upgrade to the latest version to get rid of the warning or add a note saying it's safe to ignore.

**Comment by tlongers** [comment]
Thanks. As it's benign let's leave it and circle back. Leaving it open for now.

**Comment by tlongers** [comment]
@hancush This is an old one but does the current importer need anything from this issue? If not, let's close it.
