### ISSUE TITLE
Enable Arabic translation in Rosetta

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#639]
@jeancochrane can you make an Arabic .po file available to Rosetta so we can bring a basic translation into use?

**Comment by jeancochrane** [comment]
@jmithani pushed this up to staging this afternoon! From the Rosetta dashboard, looks like Arabic translations are now available.

**Comment by tlongers** [comment]
Yep, I see it - thanks @jmithani 

After we've made changes here, am I right to recall that some process needs to be run to deploy it on staging?

**Comment by jeancochrane** [comment]
My understanding was that if you save the translations on https://back.securityforcemonitor.org, you should be able to see them immediately. In order to persist them to the GitHub repo we'll have to download them, however. Does that match your expectations?

**Comment by tlongers** [comment]
Yep that's great; thanks Jean. Closing this.
