### ISSUE TITLE
Harmonising field names across our research, platforms and tools

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#640]
Between the various products, tools and platforms we use to enable our research there are a number of discrepancies in what we call things. At a simple level `violations`, `events` and `incidents` are technically the same things. So are `organizations` and `units`; `sites` and `emplacements` and so on.  At the field level, we have things like this:

- Research handbook: [Site: Base](https://help.securityforcemonitor.org/v/en/data-model/organizations#organization_site_base)
- Data entry spreadsheet: "Headquarters (Barracks, Base, Physical Asset)"
- Data entry in WWIC: `Location other names`
- When referenced casually in Github: `org:site:hq`
- When Tom renames it for use in a GIS: `o_s_hq`

Some of it is not worth changing  at this point as its so wired into the code. Some of it is simpler to change, such as form field labels. I propse that we at least harmonize three things: the shortname for a field, and the labels we use in the app and in our Research Handbook. Luckily for us, I have already done a version one of this a while back, which can be [accessed as a spreadsheet here](https://docs.google.com/spreadsheets/d/1AlqyYWywZ8-lJhBIr-14GRkC1GXHeRYNpj6Z_-t2u6c/edit#gid=0.).  It has a few mistakes in it, so will need going over again to check for coverage.

I propose introducing some simple shortcodes across our work e.g.

The field currently called `Organization:Name` would become `o_n`. Its source would be `s_o_n`, and its confidence value `c_o_n`. This would mean all fields would be unique, short, simply machine readable and easy to reference when we're talking about them.

With respect to the data creation spreadsheets, this would mean:

- updating the field headings to use the shortcodes

With respect to the research handbook, this would mean:

- Updating the labels and fieldnames
- Introducing the shortcodes into the documentation

With respect to the development of WWIC, this would mean:

- updating some of the labels in use in read-only and data entry views
- updating the download labels to use the short-codes

@jeancochrane What's your view on this?

**Comment by jeancochrane** [comment]
In general I really like the idea of working to reduce the number of names we use to reference entities in the app. I think I need a little more clarification on the value of shortcodes in this effort.

The two perspectives I have on this issue are as a developer and as a casual consumer of the data (albeit one who knows the data model unusually well). As a developer, the biggest problem with our inconsistent naming is that it introduces a major hurdle to onboarding, which I see as a form of technical debt and maintenance risk. In our experience, it's uncharacteristically hard for new devs to wrap their head around the data model because we don't have consistent names for some entities and their models/attributes. Apps that make it hard to onboard new devs tend to be more fragile and more difficult to change. I see this as being a difficult change in the short term with a big payoff in the long term.

As a casual consumer of the data, the biggest problem with inconsistent naming is that it sometimes makes the UI confusing (e.g. the "Create new" tab instructs you to create a new "Organization," whereas the search page instructs you to filter by "Unit"). We've made great strides in addressing this over the past few years and I think a final push to harmonize entity references in the UI as you suggest would be straightforward.

Given these two perspectives, what's your pitch for including shortcodes as part of this effort? My initial reaction is that it introduces yet another reference type for devs and casual consumers to be indoctrinated into. Are there types of "shortcodes" that already exist in the app that we would be harmonising by introducing a new system?

**Comment by tlongers** [comment]
Thanks for adding in these twin perspectives, particularly the insight into what these inconsistencies mean to a developer and the overall maintainability of the software. I hadn't considered that introducing short-codes would cause further confusion; [the curse of xkcd ](https://xkcd.com/927/) strikes once more.

How did this situation develop? The data model draws many concepts and field sets from the [Popolo project](https://www.popoloproject.com/), an open government data standard and process. That's why we have terms like `organization`, `person` and `event` as the building blocks of the field sets.  The field names ended up being extended using those terms as roots:

`organization_id`

`organization: date first cited`

`organization: parent organization`

`Source: OrganizationOrganization:parent_id`

etc 

As we developed the platform many discrepancies began to emerge between the terminology used by developers in the platform code and those used in our own data entry, which remained inside spreadsheets. This resulted in hacks like this in field names; visual aids and cues  that are helpful orienting in a 116-column spreadsheet:

`Comments-specifics relevant to the review process, such as fixes, refinements, other observations. This is different from "Notes", which are intended for publication.`

`Headquarters (Barracks, Base, Physical Asset)`

In addition to this we made changes on-the-fly to the labelling of fields in WhoWasInCommand.com. These  were meant to give users a better indication of the platform's content and context: in our domain `unit` is definitely more intuitive way to define a discrete component within a security force structure, whereas `organization` is suggestive of something larger such as the branch of the security force as a whole. `Event` is very generic; `incident` conveys the violence of the event more appropriately (but acknowledging the uncertainty in a way that `violation` doesn't). And so on. But we didn't propagate these changes backwards into our data creation work: so our spreadsheet for incidents is still called `events`. Largely, this is because we have become habituated to working with these terms.

I started using the short-codes when working with downloaded data to make maps. The specific reason was to sidestep the 10-character limit on fieldnames that .shp files for use in QGIS have (thanks for nothing [dbase](https://pro.arcgis.com/en/pro-app/tool-reference/tool-errors-and-warnings/001001-010000/tool-errors-and-warnings-00126-00150-000142.htm)!). The codes I created specified a distinct and legible replacement name for the field. This was better than taking the risk of having the GIS automatically truncate long fields to 10 characters, and ending up with a confusing mess like `organizat1` and `organizat2`.  As well as avoiding this issue their consistency really simplifies data wrangling and analytical tasks because I don't need to think of what to call something. It also provides a framework for others analysts working for us: rather than create ad-hoc field names by "slugifying" them, or stripping all the spaces or special characters, short codes give them a coherent approach.

That said, this particular short-code approach is really compressed: it's legible to me because I work with it every day. For a newcomer or casual user, I agree with you that basing our field names on short codes would be annoyingly obscure. Field naming with a bit more content would be helpful. So, rather than `o_n` perhaps `org:name` or `org_name`, `organization:name`. Or, if we choose to take the leap, it's time to start using `unit:name:source` and `unit:name:confidence`. What's important is that we choose a consistent approach to both the content of the field name, and the way it is structured. 

How do we get out of this situation? Now is definitely a good time to address this, as we are long past the phase of rapidly evolving the data model and intense platform building that caused the problem.  There seem to be two zones where we can take useful action. 

- First, the places that are visible to both us and all users: working spreadsheets, application front end, research handbook, and exports. 
- Second, the names used by developers within the application itself: models, table names, variables, functions.

Both require that we finally settle on what to call things and the appropriate level of information density for the field name, but I think the first zone is far easier to implement. @jeancochrane  What do you think about tackling zone one field? What would be an appropriate level of density for field names?  And what sort of effort do you think would be involved in this?

**Comment by jeancochrane** [comment]
This detailed history of the reasoning behind field names is really helpful 👍 Definitely bookmarking this issue for future onboarding needs.

> The specific reason was to sidestep the 10-character limit on fieldnames that .shp files for use in QGIS have (thanks for nothing dbase!)

Sort of tangential, but I just want to say this is heinous! 10 characters is not nearly enough for a fieldname limit!

> What do you think about tackling zone one first? ... And what sort of effort do you think would be involved in this?

Definitely agree that zone one is the right place to start. I don't anticipate the work will require too much development time, maybe 4-6 hours or so -- mostly we'll just have to scour a lot of templates and make small tweaks here and there. The big lift as I see it is on your end: nailing down the slug format and making sure it's clearly spec'd out before we get started.

My instinct would be to start with a draft update to the research handbook documenting a unified slug format. While that's happening, the dev team can work on the frontend of the application, cleaning everything up to make sure that we consistently use the correct frontend terminology (i.e. make sure all references to `Organization` are changed to `Unit`). Then once the research handbook draft has been finalized, your team can update the working spreadsheet and research handbook while we fix up the exports.

Does that seem like a reasonable plan of attack? Anything I'm missing here?

> What would be an appropriate level of density for field names?

For slugs, I find e.g. `organization:name` to be the clearest format, and I like the extensibility implied by `organization:name:source`. That's just my personal opinion, though, and I'd prioritize the opinions of current consumers of the data. Will slugs in the format `entity:fieldname` pose problems for your shapefile work, or are you planning to continue support for the shortcodes as well?

**Comment by tlongers** [comment]
>Does that seem like a reasonable plan of attack? Anything I'm missing here?
Okay, this all sounds good. But before changing anything in the app templates, let me create an updated fieldset containing the new fields in the `[entity]:[fieldname]:[extension]` format, along with the right human readable label. Most of these labels are correct in the app already, but I'll confirm that, which should make any tweaks easier to locate and implement. I think that these changes will improve things for existing data users (and for ourselves).

>Will slugs in the format entity:fieldname pose problems for your shapefile work, or are you planning to continue support for the shortcodes as well?

I'll maintain some kind of crosswalk table for GIS work that involves shapefiles, but other analysis will not be affected.

**Comment by tlongers** [comment]
I've completed the field harmonization work. Per the discussion above, I am ready to implement these in the places that are visible to both us and all users. This would cover working spreadsheets, application front end, research handbook, and exports. I had a few questions before we embark on this:

- Am I right to think that the importer works on column position, and not field name. So long as the data is in the right column, the importer doesn't care what the column is called?
- The new field names will be things like `unit:other_names`. Are there any good reasons or other obstacles why colons should not be included in field names? Might they break the sql (or is that easily overcome?)
-  How do you want me to communicate the changes  that would been needed to different templates or outputs in WWIC? Set up a PR and do it myself?  List out the URL structures of where changes are needed, along with the change? Or annotate a set of screenshots? Let me know what would be more efficient here?

**Comment by jeancochrane** [comment]
Awesome, that's great to hear! Excited to see the new field names.

> Am I right to think that the importer works on column position, and not field name. So long as the data is in the right column, the importer doesn't care what the column is called?

Yup, this is correct.

> The new field names will be things like unit:other_names. Are there any good reasons or other obstacles why colons should not be included in field names? Might they break the sql (or is that easily overcome?)

I understood the scope of this issue to be harmonizing how field names are displayed across the app, not harmonizing their internal representations. Is that right? If so, SQL queries won't be affected by this work since the internal representations of the fields will stay the same.

> How do you want me to communicate the changes that would been needed to different templates or outputs in WWIC? Set up a PR and do it myself? List out the URL structures of where changes are needed, along with the change? Or annotate a set of screenshots? Let me know what would be more efficient here?

If you feel comfortable making a PR you're always welcome to do so! Otherwise, I think a nested list based on views or URL structures should be fine, e.g.:

> - `/`
>     - "Add new" Organization -> Unit
>  - `/download/`
>     - Basic
>         - "other_names" -> "unit:other_names"

If there are fixes that are particularly hard to communicate, feel free to leave screenshots instead.

**Comment by tlongers** [comment]
Thanks for the suggestions. I'll go with a nested list!

> If so, SQL queries won't be affected by this work since the internal representations of the fields will stay the same.

Yes, you're right that does not cover internal representations at this point. 

Possibly demonstrating my own ignorance here, the thing that prompted me to ask was after looking at https://github.com/security-force-monitor/sfm-cms/pull/646 where the field names in the downloads correspond to the names given in the sql:

`substring(MAX(division_id.value), position(':' IN MAX(division_id.value)) + 1, 2) AS area_country_iso`

Would replacing `area_country_iso` with `unit:area_country_iso` break the `AS` here?

**Comment by jeancochrane** [comment]
We can use double-quotes to escape the colon in the field name. E.g. the following query will work:

```sql
substring(
  MAX(location.division_id),
  position(':' IN MAX(location.division_id)) + 1, 2
) AS "unit:area_country_iso",
```

**Comment by tlongers** [comment]
Heh, my n00b concern assuaged. Thanks!

**Comment by tlongers** [comment]
Completed these changes a bit back! Closing issue.
