### ISSUE TITLE
Incident descriptions truncated when semi-colon is present

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#645]
@tonysecurityforcemonitor spotted a glitch in how incidents are displaying:

![image](https://user-images.githubusercontent.com/2115933/65160871-79e65600-da2e-11e9-998b-95ca10a2faa8.png)

`https://whowasincommand.com/en/violation/view/0bd09224-a7da-4e3c-98e7-a8be68b8e506/`

The full text of this incident should be:

> According to Amnesty International: "KALERI, 9 JULY 2011 On 9 July 2011 at around 8pm there was an explosion near a JTF vehicle in Kaleri Ward, Maiduguri. Most of the men in the community were in the mosque and the women were in their houses. According to residents, JTF soldiers blocked roads in the area preventing anyone from entering or exiting. The soldiers entered approximately 20 houses, searching them and bringing out residents who were made to lie on the ground. The JTF then set fire to homes, cars and motorcycles. Several men found inside the houses were shot dead. At least 18 men are believed to have been killed. Adam Abdullahi Suleiman (42) was a staff member at the University of Maiduguri who lived in Kaleri. A neighbour of Adam Abdullahi Suleiman interviewed by Amnesty International said he saw the JTF shoot Adam Abdullahi Suleiman. Adam Abdullahi Suleiman had two wives and 10 children. Adam Abdullahi’s wives, H.I. and Z.S. were in their house that evening. One of them described to Amnesty International what happened: “soldiers came into our house with two of our children and asked for our husband; we told them that he has gone to the mosque. The soldiers told us to come out and asked us to lie down into a culvert. We were then asked to give them matches and I saw them taking fuel from our electric generator set which they used to burn down our house… We saw our husband’s corpse the following morning. His identity card was in his hand... We left for our respective villages after the funeral. The university gave us an assistance of N50,000 [$317] and children’s clothes. We are yet to receive his death benefits from the university; we were given his two month salary. We have gone back to our respective families and our children have been withdrawn from the private school and are now attending public schools. We did not lodge any complaint anywhere.” A.I. lived in Kaleri with her husband and four children. She also witnessed the execution of a neighbour on 9 July 2011: “When they [brought me outside] they made me lie there with one man. He was Dahiru Muhammad, he had three wives and 13 children. When I was brought out to lie down Dahiru Muhammad was already shot. He moved. [The soldier] said ‘ah, he hasn’t died’ then he shot him again and he died.” F.I. told Amnesty International she was at home with her six children aged between five and 15 when soldiers from the JTF blocked the entrance to the community and began searching houses. The soldiers also searched F.I.’s house: “He asked, ‘where is your husband?’ I told them he has travelled. He [the soldier] said I have hidden him inside the room and I should bring him out. One of the soldiers slapped me twice and I fell down, when I stood up we went into the room and he asked me to lift the mattress. He said ‘Where is his gun?’ I said ‘he doesn’t have a gun.’ They said ‘where is his bomb?’ I answered ‘he doesn’t have a bomb.’ The soldier that followed me into the room kicked me down and I fell... I had traditional beads on my wrapper [cloth used a skirt] he pulled at the beads and my wrapper came off. He lay on top of me. He put down his gun next to me, like he was going to rape me but he didn’t take his trousers off. My four younger ones were under the bed in the same room. It lasted for about five minutes... At that time I couldn’t talk, I couldn’t control myself, I couldn’t answer... They brought me to the roadside naked [without my wrapper]. A car was ablaze. The soldier asked me to go inside the fire. Another soldier said ‘no, don’t set fire to women and children.’ They set fire to my house.” When F.I. was made to lie down outside she witnessed the summary execution of her neighbour and his children: “They were lying down next to me and were shot by my side. I was lying next to M.A., who was with her husband, Al-Ameen Abdullahi (70), and their three children, Tasi’u Al-Ameen (25); Sunusi Al-Ameen (23); and U.A.(13). Al-Ameen Abdullahi, Tasi’u Al-Ameen and Sunusi Al-Ameen were shot dead while lying face down. They spared U.A.. The woman M.A has been taken to the village, she is insane now.”

There is another example [here](https://back.securityforcemonitor.org/en/violation/view/b01a86de-9849-4ccd-932f-aa7c1df1d903/). Looks like the importer is only bringing in everything after the last semi-colon in the text provided.

**Comment by jeancochrane** [comment]
We create `location:description` using the `make_relation()` method in the importer script, which defaults to splitting text by semicolons to make multiple entities:

https://github.com/security-force-monitor/sfm-cms/blob/e7323ef8130276a9899cf139f1c58dea8d163fcb/sfm_pc/management/commands/import_google_doc.py#L957-L960

Might take a little bit of thinking to design a DRY workaround in this case that won't cascade to other elements. It might be simplest to just manually perform the import for this field instead of relying on `make_relation()`. Either way, it seems like a good candidate for some importer test data!

**Comment by tlongers** [comment]
That's an oddity. The `incident:description` shouldn't require additional processing to bring it in, as it's always been a single value rather than a multiple (like `org:classification` or org:othernames` for example. Can you give me a little more detail on what a manual import would involve here?

**Comment by jeancochrane** [comment]
Sorry, "manual import" is probably a bad way to refer to it. The `make_relation()` convenience method tries to factor out the logic of creating a variety of different attributes on entities. (We don't use it consistently across the importer, but we rely on it for the Incident imports.) This logic includes parsing source and confidence values for the attribute, determining if it is required and raising appropriate errors, etc. The "manual import" option is simply to perform this logic without using `make_relation()`, which is e.g. how we import most attributes of Units.

**Comment by tlongers** [comment]
Thanks for the clarification. There's no reason to use `make_relation()` on the `incident:description` field, so please go ahead and remove it.

**Comment by jeancochrane** [comment]
Got it, I can make that fix today.

**Comment by jeancochrane** [comment]
Pushed up a fix in https://github.com/security-force-monitor/sfm-cms/commit/d603011ca4fdaf8ef52b6618d718ea49b42bafc2. Will move this over to QA once I've rerun the import on staging.

**Comment by jeancochrane** [comment]
Refreshed the import and confirmed that full text is displaying on https://back.securityforcemonitor.org/en/violation/view/0bd09224-a7da-4e3c-98e7-a8be68b8e506/. Moving this to QA!

**Comment by tlongers** [comment]
Should have closed this back then!
