### ISSUE TITLE
When adding a site to a unit, the source picker cannot be re-focussed on "Location name" once another field as been selected

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#649]
While looking at #610, I picked up this interaction error. 

1. Edit a unit, go to the `Locations` tab.
2. Select "Add site".
3. The source picker is focussed on `Location name`.
4. Click on or tab to `Date first cited`, or any other field.
5. Click or tab to `Location name` again. 
6. The source picker is not focussed on `Location name`.

Expected behaviour is that sources can be attributed to `Location name`

**Comment by jeancochrane** [comment]
Looks like we had neglected to add the HTML class that flags a select2 input for use with the source picker. Pushed up a quick fix in https://github.com/security-force-monitor/sfm-cms/commit/e5b439f41ee91e46bf02ab44af9adbb54a73a05b, let me know if you can still reproduce the problem.

**Comment by tlongers** [comment]
Can't reproduce the issue anymore;  fixed! 👍
