### ISSUE TITLE
Question: sources and confidence for person:deceased

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#654]
@jeancochrane Does the app have specific source and confidence fields for the field `person:deceased`, or do they inherit from `person:date_of_death`?

**Comment by tonysecurityforcemonitor** [comment]
I'd see these as different concepts potentially - where there could be a source indicating someone was deceased but we don't have any value to put in `person:date_of_death` - so each field should have source and confidence fields

**Comment by jeancochrane** [comment]
Looks like the data entry system treats them as attributes with separate source and confidence values:

https://github.com/security-force-monitor/sfm-cms/blob/98c430831ce9c5f842d32118150915d790018474/templates/person/create-basics.html#L196-L203

https://github.com/security-force-monitor/sfm-cms/blob/98c430831ce9c5f842d32118150915d790018474/templates/person/create-basics.html#L228-L236

Playing around with the staging site, that appears to be working in the UI.

**Comment by tlongers** [comment]
Yeah, my view was same at Tony's - they're separate fields.  I had seen in WWIC that it was implemented that way (which is correct). I just wanted to confirm that was the case. Thanks Jean! Closing.
