### ISSUE TITLE
violation:exact_location is importing the wrong value

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#655]
Spun off from https://github.com/security-force-monitor/sfm-cms/issues/650#issuecomment-540195298:

> Digging into `Exact Locations` some more, I believe @tlongers is right that we're not saving them properly in the importer. The code [I referenced above](https://github.com/security-force-monitor/sfm-cms/issues/650#issuecomment-537528235) was saving values to `Violation.LocationName` and `Violation.LocationId`, which are actually deprecated `Exact Location` attributes that are no longer used -- the relevant code for importing `violation:location` below demonstrates that we indeed use the value of `City or smallest administrative area`, aliased to `geo`:
>
> https://github.com/security-force-monitor/sfm-cms/blob/51bbcde892c5ad3666e59e78f5bbd101bb6f1f74/sfm_pc/management/commands/import_google_doc.py#L2103-L2109
>
> Two options for addressing this are:
>
> 1. Open a new issue for this discrepancy and fix it
> 2. Wait for a more comprehensive refactor of the Violation Location models

**Comment by tlongers** [comment]
Resolved in Locations overhaul.
