### ISSUE TITLE
Updates to help links in WWIC

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#656]
We have [updated our Research Handbook](https://help.securityforcemonitor.org) (in line with #640) and have also rebuilt it in Sphinx so it can be published using ReadTheDocs rather than Gitbook. There are two implications for this:

1. Update root handbook URL

Currently the root URL is :

`https://help.securityforcemonitor.org/v`

It should be changed to:

`https://help.securityforcemonitor.org/`

2. Addition of a "version" setting in Django setting

Settings for the root url and language are already included in WWIC's settings.  The ReadTheDocs url structure also includes a part for "version":

`https://help.securityforcemonitor.org/en/latest/datamodel.html`

Is it worth making this a separate setting and adapting `sfm_pc/templatetags/help.py`, or just include `latest` in the part of the link content that is specified in the help blocks?

2. Updates to links in the WWIC codebase

The substantive parts of the help URLs have changed a bit in the migration from Gitbook to ReadTheDocs. 

I grepped the codebase for `{% help`, pulled out the partial links in the results and have added the update requirements here:

https://gist.github.com/tlongers/e731b2d73739189c8b521f479794dd9f

**Comment by jeancochrane** [comment]
> Is it worth making this a separate setting and adapting `sfm_pc/templatetags/help.py`, or just include `latest` in the part of the link content that is specified in the help blocks?

I like the idea of pinning the application to a specific version of the docs as a way to ensure that the links always resolve as we expect. However, the tradeoff is that it'd be harder to make small (i.e. non-structural) doc changes visible in the production application, since we'd need to push a production app deployment every time we wanted to update the docs. So I would say that if you expect to want to make frequent small changes to the docs, we should always point to `latest`; otherwise it makes sense to pin to specific versions.

> I grepped the codebase for `{% help`, pulled out the partial links in the results and have added the update requirements here:

This is super helpful, thanks!

**Comment by tlongers** [comment]
Thanks @jeancochrane, that's helpful. Near-term we don't plan to extend the number of places where help links are offered; nor would we need to keep older versions of the help around. Likely, the updates we will be content, not structure. So,  for now at least, let's leave the help links pinned to version `latest`;  just append it to the links included in the help blocks.

**Comment by jeancochrane** [comment]
This change has been pretty straightforward to work on; many thanks to @tlongers for the upfront work getting everything catalogued.

One quick question: Do we want to continue interpolating the user's language code and linking them out to documentation based on that code? E.g. currently there's no Spanish translation, but a user looking at the Spanish translation will be taken to http://help.securityforcemonitor.org/es/latest/ if they click on a help link, which currently doesn't exist. (I feel like my ideal behavior here would be for RTD to redirect to the English docs by default if there's no translation for a given language code, but I'm not sure if that's a configuration possiblity or not.)

**Comment by tlongers** [comment]
We should keep the interpolation, as it's a mid-term goal to bring the Research Handbook and guidance on the use of WWIC into different languages.  RTD can be configured to serve different language versions; I'll take a little time to that set up and will write on this issue when that's done.

**Comment by tlongers** [comment]
I've configured our Read The Docs instance to run a Spanish translation of the Research Handbook, so we can continue to insert the language chosen by the user into the help outlinks e.g.

`https://help.securityforcemonitor.org/es/latest/unitrec.html`

RTD will continue to display the original English message strings on the Spanish versions whilst we organize translations.

**Comment by tlongers** [comment]
For future readers of this issue, [here's a bit of info about the how the ReadTheDocs/Transifex process works](https://github.com/security-force-monitor/research-handbook/blob/master/README.rst) in the context of our Research Handbook.

**Comment by tlongers** [comment]
Closing.
