### ISSUE TITLE
Update CRUD templates for field harmonization

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#659]
After refactoring Create and Edit templates to share the same templates (#597), update the templates to make sure that they work with the new harmonized fields. This includes:

- [ ] Audit and update top-level entity names (Person, Unit, Incident)
- [ ] Update help links to point to new documentation (#656)
- [ ] Make sure new fields are exposed and deprecated fields are removed from templates

**Comment by tlongers** [comment]
Superseded; development on data entry system paused.
