### ISSUE TITLE
Allow user to turn source/confidence values on and off for data downloads

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#661]
Provide a toggle switch to allow the user to optionally include source/confidence values in their data downloads.

As part of this work, refactor the data downloads to use the ORM. This will make it much easier to conditionally toggle source/confidence.

**Comment by jeancochrane** [comment]
We had to roll back the source downloads in #686 because the queries to generate the materialized views required more disk space than was available on either staging or production (~50GB). The confidence score downloads are still active, and the architecture we have in place will support source downloads with a revert of #686 once we've figured out the disk space issue. If it's alright by you @tlongers I can push this change up to production today.

The root problem causing the queries to run out of disk space is the joins that we do to pull in sources. (Postgres uses temporary tables on disk to accomplish joins, which explains why disk space is the limiting resource here.) By removing the joins on the source tables, I was able to reduce the order of magnitude of query time from hours to seconds, and eliminate the disk space issue. This confirms to me that sources are indeed the problem, although we don't know yet if all source tables are affected equally or if there are some source tables in particular that are blowing up the query. (For example, these queries run fine when run on the subset of data we worked with during field harmonization; when expanded to the full production database, they slowed down and ran out of disk space.)

There are a couple of reasons that I suspect sources are causing problems for us:

- Aggressive normalization: Each source for each attribute of each entity has its own dedicated table. This means that for every attribute we want to source in the downloads, we need an extra join in the query.
- Many-to-many relationships: Each attribute can have multiple sources; each source can support many attributes. This increases the complexity of the results returned by each query.
- Size of the data: The above two problems are tractable on small subsets of the data, but behave something like exponentially, and so become worse as the size of the data grows.

These are relatively normal data modeling problems, so I feel optimistic that we can find a solution with some clever query writing that doesn't require a rewrite of the data model. Still, it took us 5-10 extra hours to rewrite the query so it would work on the smaller data subset, so I wouldn't be surprised if we're looking at a similar or greater investment to get to the root of the problem.

**Comment by tlongers** [comment]
For now the solution is pragmatic and keeps most of the functionality available for users. Thanks for the clear explanation and fix, and please push it to production.

**Comment by tlongers** [comment]
This is a very useful thread that tells us a lot about the issues we face in delivering downloads. On the issue itself, sources are paused, and confidence scores are implemented but as integers not text (so `1` rather than `Low`), but that can be addressed later. Closing this issue.
