### ISSUE TITLE
Update public-facing templates for field harmonization

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#662]
Update all templates that face the public to make sure that they work with the new harmonized fields. Save CRUD templates for #659, since these are less important. This includes:

- [x] Audit and update top-level entity names (Person, Unit, Incident)
- [x] Update help links to point to new documentation (#656)
- [x] Make sure new fields are exposed and deprecated fields are removed from templates

**Comment by tlongers** [comment]
All good.
