### ISSUE TITLE
Incident icon changes to plus/minus on facet dropdown

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#664]
On the incident search view, toggling the `Filters for Incidents` dropdown causes the icon to change to plus/minus erroneously:

![2020-02-26 11 56 25](https://user-images.githubusercontent.com/14170650/75373105-42a68b80-588f-11ea-818d-3a065fb93044.gif)

There's probably a JQuery selector that's accidentally grabbing too much here.

**Comment by jeancochrane** [comment]
This seems to happen for Sources, too.

**Comment by tlongers** [comment]
Well noticed! Low priority for now, but we should do UX round in the near future I think.

**Comment by tlongers** [comment]
Issue resolved at some point (possibly by https://github.com/security-force-monitor/sfm-cms/commit/4c3b2d6aaee68bd7682c11a8495b08a89c3eb5e8)
