### ISSUE TITLE
Sources of OSM administrative boundary data

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#666]
The [free to use boundary extraction service run by Wambacher](https://wambachers-osm.website/boundaries/) has been down for a few days. This service has been really useful to us, and I really hope it returns. @jeancochrane can you remind me if WWIC is still dependent on it for any boundary data (per https://github.com/security-force-monitor/sfm-cms/commit/b771908ee24718216de696ac874ac1706465fb9b) or does the location app create everything itself from Geofabrik's OSM extracts?

**Comment by jeancochrane** [comment]
Great question! I had to do a quick read-through of `import_osm.py` to remind myself. When building the `osm_data` table, we use Wambacher's extracts to load boundaries in the `downloadBoundaries()` and `importBoundaries()` methods, and we use Geofabrik's extracts to load points in the `downloadPBFs()` and `loadPBFs()` methods. So it seems we depend on both data sources.

**Comment by tlongers** [comment]
Thanks. I've reached out to Wambacher to see if there is a long term issue with their service. My view is that we should in any event invest in creating our own method of obtaining administrative boundaries from OSM, as they're fundamental to our ability to geolocate and vizualize. It may be that we need to give bump up the importance of a general discussion about locations.

**Comment by tlongers** [comment]
As of this morning, the Wambacher service is back online again. Closing the issue for now.

**Comment by jeancochrane** [comment]
Seems like Wambacher is down again. This thread indicates it's not being actively maintained: https://forum.openstreetmap.org/viewtopic.php?id=68844

**Comment by tlongers** [comment]
What do you need? I may have copies already.

Also - have you checked out this clone of the service: https://osm-boundaries.com/ ?

**Comment by tlongers** [comment]
We have resolved this with custom tooling.
