### ISSUE TITLE
French locale setup

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#672]
Notwithstanding  https://github.com/security-force-monitor/sfm-cms/issues/671 ... @jeancochrane can you set up a French locale for WWIC? If you can expose it on ~/rosetta on staging, that'd be great.

**Comment by tlongers** [comment]
Actually, my bad -  it's already set up [here](https://github.com/security-force-monitor/sfm-cms/tree/master/locale/fr/LC_MESSAGES) and is in Rosetta. Can you verify that it's updated to reflect the current status?

**Comment by jeancochrane** [comment]
Yeah, I'll slot this on my plate for early next week. Updating the .po file and making sure it's available on Rosetta should be fast. Actually making that translation available on the frontend might involve some amount of refactor, since the way we currently do it seems hard to extend in a modular way:

https://github.com/security-force-monitor/sfm-cms/blob/320b5fd56637bd6c0f6136aaa3b5dca5dc80dad1/templates/base.html#L147-L169

**Comment by jeancochrane** [comment]
I double-checked to make sure that the French translations are up to date on staging, and opened up #673 to add the necessary changes to expose that translation on the frontend. Let me know when you'd like to expose the translations and we can pull it in.

**Comment by tlongers** [comment]
Got it, thanks Jean.

**Comment by tlongers** [comment]
Remind me: aside from the small update to the language selector button, if we introduce translated strings through Rosetta are the changes immediate, or is there a sysop step to get the platform to display them?

**Comment by jeancochrane** [comment]
Unfortunately I think we need to restart the Nginx server to see new translations. From the [Rosetta docs](https://django-rosetta.readthedocs.io/usage.html#translate-away):

> This means your project’s labels will be translated right away, unfortunately you’ll still have to restart the web server for the changes to take effect. (NEW: if your web server supports it, you can force auto-reloading of the translated catalog whenever a change was saved. See the note regarding the `ROSETTA_WSGI_AUTO_RELOAD` variable in conf/settings.py.

We haven't set this variable in `sfm_pc/settings.py`, and as far as I can tell from the docs it's [not recommended to enable it in production](https://github.com/mbi/django-rosetta/blob/3c249d344eaf667b58a61a0433d65fb2a8c72355/docs/settings.rst#settings).

The good news is that restarting the web server is instantaneous on the backend.

**Comment by tlongers** [comment]
Thanks! That's really helpful.

**Comment by tlongers** [comment]
I think we can close this issue now. If you restart the web server, we can get the first cuts of the French translation up now.

**Comment by jeancochrane** [comment]
Great, I'll pull in #675 which will restart the server as part of the deployment process.

**Comment by tlongers** [comment]
Bingo! Closing.
