### ISSUE TITLE
Redirect /countries and /help to the docs site

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#675]
From @tlongers:

> We both think that if we're going fully multi-lingual on WWIC we should reduce the amount of text on the platform, to free up time and resource we can use to keep the interface elements localised. To that end, we'd like to strip out ~/countries/ and ~/help/ from the platform, and move the content across to help.securityforcemonitor.org. We can host, develop and maintain it better there, and it removes some of the overhead involved in translating the platform. We'd expand the text in ~/about/ a little bit to let users know where they can find more help and documentation.

Related to #672.

Once we have the redirect links for `/countries` and `/help` and the new text for `/about` we should be able to get this merged in pretty quickly.

**Comment by tlongers** [comment]
Thanks Jean, I'll get those to you ASAP.

**Comment by tlongers** [comment]
Both `~/help` and `~/countries` should redirect to `~/about`, and should no longer appear in the nav bar. 

The revised about text for `~/about` is [here](https://docs.google.com/document/d/1lVQUoZRJsyW7-UzRUVzPoFBh5Btwr4acIk48syDM5R8/edit#) and should be a simple page with no sidebar. 

Once the changes are up, can you regenerate the localization files and make them available through Rosetta?

**Comment by jeancochrane** [comment]
Can do @tlongers! I'll let you know as soon as it's up.

**Comment by tlongers** [comment]
Can I bump this up? The translator is ready to go.

**Comment by jeancochrane** [comment]
My apologies, I've been out of commission with illness for the past few days. We'll have this online and ready today.

**Comment by tlongers** [comment]
Argh, apologies also  - I didn't know! Thanks Jean.

**Comment by jeancochrane** [comment]
Alright, this should be up on staging! Let me know if anything looks off and I can take a look.

**Comment by tlongers** [comment]
Looked good Jean, thanks! The redirects work, the new text is in place, and the updated strings are in the .po file for the translator to work on.

**Comment by jeancochrane** [comment]
Awesome, closing this then 👍
