### ISSUE TITLE
Importer is not bringing in all values from incident perpetrator classification field 

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#676]
The field `incident:perpetrator_classification` ([docs](https://help.securityforcemonitor.org/en/latest/incidents.html#incident-perpetrator-classification)) can hold multiple, semi-colon separated values. On a recently-established private instance, it looks like the importer is only importing and displaying the first value. For example see incident `3543e1f4-786e-4ab9-a1f5-01bae3f2fdd3` on that instance, which should have two classifications but currently displays only one in the `Perpetrator classifications` field in the incident record header.

**Comment by tlongers** [comment]
@hancush does this still look to be an issue?

**Comment by hancush** [comment]
It looks like [both classifications are present for that incident on the site](https://whowasincommand.com/en/violation/view/3543e1f4-786e-4ab9-a1f5-01bae3f2fdd3/), so unless you see other examples of misbehavior, this looks to be addressed.

**Comment by tlongers** [comment]
Thanks 👍 closing.
