### ISSUE TITLE
The Site facet is showing a value of "None"

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#689]
From https://whowasincommand.com/en/search/?entity_type=Organization:

<img width="877" alt="Screen Shot 2020-06-03 at 10 55 47 AM" src="https://user-images.githubusercontent.com/14170650/83659273-f010f580-a588-11ea-9f4b-51d56736873c.png">

I expect either the import script is failing to find these geographies, or the search indexing script is accessing them incorrectly.

**Comment by jeancochrane** [comment]
After digging into this a bit more, it seems like two things are going haywire.

The first problem is that the name of this facet appears to be misleading. This facet is populated with the `Location.adminlevel1` value for every emplacement for a unit. As a result, if a unit has an emplacement but the geography for that emplacement has no value for `adminlevel1` (actually OSM admin level 6, [according to our import code](https://github.com/security-force-monitor/sfm-cms/blob/5988de96da685a7738bacc827a2a4fc418a27094/sfm_pc/management/commands/link_locations.py#L87-L89)), this facet will incorrectly indicate that the unit has no "Sites." We can see this e.g. for [a search for`Batallón de Embarcaciones y Vehículos Anfibios del Pacífico` with Sites selected as `None`](https://whowasincommand.com/en/search/?selected_facets=organization_adminlevel1_ss_fct_exact%3ANone&selected_facets=organization_adminlevel1_ss_fct_exact%3ANone&q=Batall%C3%B3n+de+Embarcaciones+y+Veh%C3%ADculos+Anfibios+del+Pac%C3%ADfico&entity_type=Organization&start_date=&end_date=), where the results all have a value for "last site" in the display table but a Site of `None` according to the facet, because those `Location` objects don't have corresponding `adminlevel1` attributes.

The second problem is that somehow when we index documents with no value for a given facet, pysolr can wind up returning a value of `None` for that facet. We can see this e.g. for the unit with ID `f0744906-80ca-4e05-b9e6-4da3d60ef1a0`. When querying the Solr search index directly, the document shows no value for `organization_adminlevel1_ss`, the field we use for facets; however, pysolr's `response.facets` dictionary shows the key-value pair `'organization_adminlevel1_ss_fct': [None, 1]`.

Problem number 1 requires some discussion with @tlongers on why we're using admin level 1 as the key facet for `Sites` and what we can do to mitigate missing data. Problem number 2 seems potentially like a bug within pysolr but could be routed around at the application level by updating the [`format_facets()` method](https://github.com/security-force-monitor/sfm-cms/blob/5988de96da685a7738bacc827a2a4fc418a27094/sfm_pc/utils.py#L779-L821) to ignore any facet that is a `NoneType`.

**Comment by tlongers** [comment]
We've discussed aspects of this matter at length before  in https://github.com/security-force-monitor/sfm-cms/issues/650, in which we looked at location data about incidents. In this case, the app was assigning inferred administrative levels when it should have been taking the value directly from the import sheet. Do you think we have the same behaviour in the present issue?

**Comment by jeancochrane** [comment]
Yeah, I think a similar thing is definitely going on here for Units. It looks like if `unit:site_exact_location_id_latitude` exists, we use that OSM geometry (including its inferred administrative levels) to make the Site; otherwise we fall back to `unit:site_nearest_settlement_id`:

https://github.com/security-force-monitor/sfm-cms/blob/b95454e4943d825728e70452f4152a98a04922fb/sfm_pc/management/commands/import_google_doc.py#L1300-L1317

The refactor here will be more challenging than for incidents, since for incidents we separately store references to `location`, `adminlevel1`, and `adminlevel2`, which made it easy to refactor the importer to save each of those values separately in https://github.com/security-force-monitor/sfm-cms/commit/2c354a5f4d917ae35627c7c38f981be5d3d5a2d5. However, I do think it's doable.

All of that being said, do we still think it's appropriate that the `Site` filter looks for the `adminlevel1` value of the Emplacement's `Location`? Why not use `Location.name` instead?

**Comment by tlongers** [comment]
Thanks Jean. Broadly, this sort of facet is a simple proxy for a real location-aware search and corresponding UI. If anything, this facet should contain the values in `unit:site_first_admin_area_name` ([docs](https://help.securityforcemonitor.org/en/latest/units.html#unit-site-first-level-administrative-area-name)), which would provide a broad drilldown with a manageable number of entries (probably <50). The question here is whether the importer actually ingests those values from the import shorot and assigns them to sites, or whether it automagically assigns them.

**Comment by jeancochrane** [comment]
Got it. The current behavior of the importer is to retrieve the OSM ID for `Emplacement.site` using `unit:site_exact_location_id_latitude` if it exists, and if it doesn't, to fall back on `unit:site_nearest_settlement_id`. Once it has an OSM ID, it infers the admin levels via the `Location` model. I believe this is the core reason that many facet values are missing for `Site` -- almost none of the Mexico units have an `exact_location`, so instead we're using `nearest_settlement`, whose OSM objects will not have inferred values for `adminlevel1` because they themselves represent a `Location` of the `adminlevel1` resolution.

We could try approximating a switch to `unit:site_first_admin_area_name` for the facet by querying `Location.adminlevel2` instead of `Location.adminlevel1`. This would be a fast change but wouldn't fix the core problem that the importer is inferring admin levels instead of reading them from the sheet. Unfortunately fixing the core problem will be challenging because the automatic inference of admin levels is coupled pretty tightly with the current data models for `Emplacement` and `Location`, but if that's the path we want to take I can take some time to sketch out what I think the refactor should look like.

**Comment by tlongers** [comment]
Resolved by changes to Location model and geospatial import processes (~ March 2021)
