### ISSUE TITLE
Link to generate OSM API key is broken

### ISSUE THREAD

**Issue by hancush** [security-force-monitor/sfm-cms#702]
Dead link: https://wambachers-osm.website/boundaries/ :-(

N.b., the Wambacher API was a free service from which we downloaded OSM boundaries that is no longer available. It is not the same as the [OSM API](https://wiki.openstreetmap.org/wiki/API_v0.6#URL_.2B_authentication).

Related to #666.

**Comment by tlongers** [comment]
Yes, very sadly Wambacher's OSM Boundary Service is now dead and we need to find an alternative solution. Another developer has stepped in and created [OSM Bounadries](https://osm-boundaries.com/), which replicates the functionality of the Wambacher site. It's  lot newer and its not clear if its a long term project we should rely on for our geospatial needs Longer run, Overpass API can do everything that we need (convert an OSM ID into geometry, grab admin metadata and so on) but this needs some fairly dramtic retooling of WhoWasInCommand's importer process. I'm working on how we can approach this conceptually and will have an update shortly.

**Comment by hancush** [comment]
Thanks, @tlongers, this is super helpful! @jeancochrane gave me a thorough onboarding yesterday, based on that extra context, I've updated the issue description to relate this thread to #666. I'll keep this open as a reminder to update the docs based on the revised approach to location and load in a dump of one of the deployed databases to get a local version running.

**Comment by tlongers** [comment]
That's a great stopgap, thanks @hancush.

**Comment by tlongers** [comment]
Closing this: external boundary service no longer required by WWIC.
