### ISSUE TITLE
Refactor Location import to use new location file

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#704]
SFM is working on a new data standard that will include a new GeoJSON file representing Location objects. Refactor the data import process to use this new file to import Location objects instead of pulling down a huge batch of OSM data and using it to infer Locations.

The changes I expect us to make should include:

* Remove the [`import_osm`](https://github.com/security-force-monitor/sfm-cms/blob/master/sfm_pc/management/commands/import_osm.py), [`link_locations`](https://github.com/security-force-monitor/sfm-cms/blob/master/sfm_pc/management/commands/link_locations.py), and [`clean_locations`](https://github.com/security-force-monitor/sfm-cms/blob/master/sfm_pc/management/commands/clean_locations.py) management commands
* Check to make sure our [`Location` model](https://github.com/security-force-monitor/sfm-cms/blob/ce84206da1f43fc5a68ce483993165484a09f470/location/models.py#L9-L24) matches the new spec and update any fields as necessary
* Write a new management command to load the GeoJSON file, iterate each feature, and create a new `Location` object from that feature
    * Write some simple fixtures and tests so that we can start building a test suite for this command
    * Make sure to update docs to reflect the sequencing of this step in relation to `import_google_doc`
* Update the `import_google_doc` management command to use the new Locations sheet
    * Adjust tests and fixtures in the [importer tests](https://github.com/security-force-monitor/sfm-cms/blob/master/tests/test_importer.py) and [importer fixtures](https://github.com/security-force-monitor/sfm-cms/tree/master/tests/fixtures/importer) to make sure you use your new management command for creating `Locations`
    * Update `create_organization()`
        * Remove [`area_positions` and `site_positions`](https://github.com/security-force-monitor/sfm-cms/blob/ce84206da1f43fc5a68ce483993165484a09f470/sfm_pc/management/commands/import_google_doc.py#L494-L508) from `create_organization()`
        * Update [`make_emplacement()`](https://github.com/security-force-monitor/sfm-cms/blob/ce84206da1f43fc5a68ce483993165484a09f470/sfm_pc/management/commands/import_google_doc.py#L1233) and [`make_area()`](https://github.com/security-force-monitor/sfm-cms/blob/ce84206da1f43fc5a68ce483993165484a09f470/sfm_pc/management/commands/import_google_doc.py#L1107) to fit the new format, including the subsidiary methods that they call like `get_exact_location()` and `get_or_create_site()`
        * Update the [Emplacement and Area assignments](https://github.com/security-force-monitor/sfm-cms/blob/ce84206da1f43fc5a68ce483993165484a09f470/sfm_pc/management/commands/import_google_doc.py#L649-L673) in `create_organization()`
    * Update `create_event()`
        * Remove [`ExactLocation`](https://github.com/security-force-monitor/sfm-cms/blob/ce84206da1f43fc5a68ce483993165484a09f470/sfm_pc/management/commands/import_google_doc.py#L2206-L2211) and [OSM admin levels](https://github.com/security-force-monitor/sfm-cms/blob/ce84206da1f43fc5a68ce483993165484a09f470/sfm_pc/management/commands/import_google_doc.py#L2226-L2238) from the `create_event()` field config dict
        * Strip out the [geography inference code in `create_event()`](https://github.com/security-force-monitor/sfm-cms/blob/ce84206da1f43fc5a68ce483993165484a09f470/sfm_pc/management/commands/import_google_doc.py#L2315-L2428) and replace it with the same kind of Location assignment that you use for `create_organization()`
    * Make sure to check and test the warnings/errors that get raised when Locations are missing to make sure they're clear

For more background, see the `Locations` section in [these notes](https://docs.google.com/document/d/1U1JQNN_HcsCS_2eLu4jOvMAqBZnMBbO5KyCd3pqL2IQ/edit?usp=sharing).

This issue should supercede #666, #702, and #624.

**Comment by tlongers** [comment]
What changes about the above  if we're just passing over a `geoJSON` instead?

**Comment by jeancochrane** [comment]
Great question! It means that we'll be able to skip most of the steps in bullet 3 ("Update the `import_google_doc` management command...") and instead focus on bullet 4 ("Figure out how to use the new Location data file..."). I have thoughts on how to do this but I think it would be mutually beneficial to discuss them on a design call with @hancush before settling on them. Hannah, do you have a free 30 mins for that this week? If not I can just go ahead and leave my thoughts but I figure this could be a good opportunity to make sure we're on the same page about how to think about importer design changes.

**Comment by hancush** [comment]
Sure, @jeancochrane, I created an event tomorrow morning. Feel free to propose an alternate time if that doesn't work for you. (We'll be off Thursday and Friday this week.)

**Comment by jeancochrane** [comment]
Updated the initial comment to reflect the fact that we'll be importing Locations from a dedicated GeoJSON file using a new management command.

**Comment by hancush** [comment]
Hi, @tlongers, I could use your help updating the test cases so they reflect the change in locations. The "current" (relative to the state of the import refactor) versions of the test cases live here: https://github.com/security-force-monitor/sfm-cms/tree/import-refactor/tests/fixtures/importer

Would you mind updating the units and incidents CSV files to conform to the new location reference format? Ideally, the update would represent the same information, just in the new format. You can share the revised versions with me via GitHub comment or through email, whatever works best for you.

(Also let me know if you need any additional context – I'm not sure how the test case creation process went before.)

**Comment by tlongers** [comment]
Does 852ab66bd5d9f92c104b64194f603e15bbb99695 do the job?

(I'd submit it as PR request, but being a complete amateur, I found it making the PR against the very first commit on sfm-cms in its former repository!)

**Comment by hancush** [comment]
I think so! I can grab the file from the commit to spare you more admin, but for future reference, you can change the base of your PR [like this](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request). Thank you kindly, @tlongers. :-)

**Comment by hancush** [comment]
Actually, @tlongers, could you send [`locations.tsv`](https://github.com/security-force-monitor/sfm-cms/commit/852ab66bd5d9f92c104b64194f603e15bbb99695#diff-e9eb318dfb3482b7ea7b45cb963a84b2f99626fc94bbdecfbe5c2c09b12915b0) in the new GeoJSON format, instead? That's how we'll be ingesting that information.

**Comment by tlongers** [comment]
Thanks; I won't attempt a PR this time! See e811e9f2e0e0c2fd8dcad424fbe737930ce80357 for the GeoJSON version of the importer test locations.

**Comment by hancush** [comment]
@tlongers Thanks a ton for helping me with the fixtures! [The units fixture you sent over](https://github.com/security-force-monitor/sfm-cms/blob/852ab66bd5d9f92c104b64194f603e15bbb99695/tests/fixtures/importer/units.csv#L8) shows the "Has Member Organization" as a member of itself. I assume that related unit information should be associated with the following unit, "Is Member Organization". Is that correct, and if so, can you confirm [this is the correct representation of that relationship](https://github.com/security-force-monitor/sfm-cms/blob/a86781833b5c17de90117b5099324d32588ab2e9/tests/fixtures/importer/units.csv)?

**Comment by tlongers** [comment]
Sorry about that; my mistake.

`Is-member Organization name` should be a member of `Has-member Organization name`. 

The [fixture you reference here](https://github.com/security-force-monitor/sfm-cms/blob/a86781833b5c17de90117b5099324d32588ab2e9/tests/fixtures/importer/units.csv) is the correct represetnation of that relationship.
