### ISSUE TITLE
Consolidate Unit relationships in the importer using a new unit:related_type field

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#706]
SFM has proposed a new `unit:related_type` field in the source spreadsheets to distinguish between Compositions and MembershipOrganizations, which would allow the spreadsheet to consolidate the `unit:related_unit` and `unit:membership` fields into one set of fields.

In the long term it may prove useful to consolidate the `Composition` and `MembershipOrganization` models in a similar fashion, but in the short term the most important piece of work is to refactor the importer to accommodate these new field names. Roughly I expect the work to look like:

* Add new tests and fixtures to the [importer tests](https://github.com/security-force-monitor/sfm-cms/blob/master/tests/test_importer.py) and [importer fixtures](https://github.com/security-force-monitor/sfm-cms/tree/master/tests/fixtures/importer) to make testing your changes easier
* Consolidate [`composition_positions`](https://github.com/security-force-monitor/sfm-cms/blob/ce84206da1f43fc5a68ce483993165484a09f470/sfm_pc/management/commands/import_google_doc.py#L455-L492) and [`membership_positions`](https://github.com/security-force-monitor/sfm-cms/blob/ce84206da1f43fc5a68ce483993165484a09f470/sfm_pc/management/commands/import_google_doc.py#L510-L542) to refer to only one set of fields, and add `unit:related_type` to the consolidated config dict
* Update the [composition](https://github.com/security-force-monitor/sfm-cms/blob/ce84206da1f43fc5a68ce483993165484a09f470/sfm_pc/management/commands/import_google_doc.py#L675) and [membership](https://github.com/security-force-monitor/sfm-cms/blob/ce84206da1f43fc5a68ce483993165484a09f470/sfm_pc/management/commands/import_google_doc.py#L781) import blocks to switch on the new `unit:related_type` field and create compositions/memberships appropriately

For more background, see the `Relationships` section of the [notes doc](https://docs.google.com/document/d/1U1JQNN_HcsCS_2eLu4jOvMAqBZnMBbO5KyCd3pqL2IQ/edit?usp=sharing).

**Comment by tlongers** [comment]
Any localization impacts?

**Comment by jeancochrane** [comment]
Not that I anticipate. Rather than change our underlying models, this issue is suggesting that we instead change the importer to use `unit:related_type` as a switch in the logic. If we ever decide to consolidate the `Composition` and `MembershipOrganization` models to a single model that uses `unit:related_type`, we may need to redo the translations of those field names depending on whether or not Rosetta can automatically detect the switch (I'm not confident either way).

**Comment by tlongers** [comment]
@hancush Do these changes necessiate any updates to the test cases? If so how can I be helpful here?

**Comment by hancush** [comment]
@tlongers I updated our existing unit test cases to reflect the new relationship structure (but not the new location structure, yet): https://github.com/security-force-monitor/sfm-cms/tree/import-refactor/tests/fixtures/importer/units.csv

Didn't realize but am happy to hear we get test cases from you! 🎊  Moving forward, I will definitely tap you for help. The next update to the test cases will be the new location format in support of https://github.com/security-force-monitor/sfm-cms/pull/716.

FWIW, our current test cases live in this directory: https://github.com/security-force-monitor/sfm-cms/tree/import-refactor/tests/fixtures/importer

**Comment by tlongers** [comment]
Okay, super. We'll do our best to provide test cases as needed; just ask.
