### ISSUE TITLE
[dev-server] server error on specific unit record

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#712]
The development server is throwing an error on the unit record for `55 Light Infantry Division` of the Myanmar army:

`[staging]/en/organization/view/27da2e9e-f5ad-4f7e-940c-d1e67ca3bca1/`

The same issue is not experienced on WWIC production:

`https://whowasincommand.com/en/organization/view/27da2e9e-f5ad-4f7e-940c-d1e67ca3bca1/`

**Comment by hancush** [comment]
Looks like this got resolved! https://back.securityforcemonitor.org/en/organization/view/27da2e9e-f5ad-4f7e-940c-d1e67ca3bca1/
