### ISSUE TITLE
[solr-refactor] [staging] applied facets are not resulting in changes to the search result set

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#717]
[Connects to issue #674] 

From the home page, selecting a country (`mexico`) and entity type (`unit`) takes us here:

`~/en/search/?q=&entity_type=Organization&selected_facets=countries_exact%3AMexico`

The  entity and country facets are set correctly in the left hand side bar:

![image](https://user-images.githubusercontent.com/2115933/107041821-dcbdc600-67b8-11eb-925a-6d66b27f084f.png)

However, the results shown are not those we would expect to appear filtered by the country facet:

![image](https://user-images.githubusercontent.com/2115933/107041874-ef37ff80-67b8-11eb-8b53-0e2501068f60.png)

Similarly, the options retreived for facets specific to units are also not narrowed down to Mexico (containing as they do the `Saudi Arabian National Guard`):

![image](https://user-images.githubusercontent.com/2115933/107042201-62da0c80-67b9-11eb-9f2d-c3ab5e0e70c4.png)

The facets are also not functioning correctly. If we select the "membership" facet for one that we _know_ refers to Mexico:

![image](https://user-images.githubusercontent.com/2115933/107042327-8735e900-67b9-11eb-8869-84f3aeb669f8.png)

The result set is not yet filtered to show "all units in Mexico that are members of Operation Conjunta Chihuahua":

![image](https://user-images.githubusercontent.com/2115933/107042403-a0d73080-67b9-11eb-9f48-e6b0bf98cd05.png)

**Comment by hancush** [comment]
@tlongers Would you believe the fix for this was a one-line change? https://github.com/security-force-monitor/sfm-cms/pull/711/commits/cc0484c73a09b760775e3d025e3f48d7060bea82 😅

Deployed to the dev site for your approval.

**Comment by tlongers** [comment]
Yep that does the trick. There are a few other issues with the faceting that I'll outline in another issue. Closing this though.
