### ISSUE TITLE
[solr-refactor] [staging] changing entity during searches means facets mismatch entity

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#718]
Start with a query on `persons` that includes a facet on `Mexico` and a facet for persons of the rank `General de Brigada`:

`~/en/search/?selected_facets=countries_exact:Mexico&start_date=&end_date=&q=&entity_type=Person&selected_facets=ranks_exact%3AGeneral%20de%20Brigada`

Change the entity to `incidents` and run the query again, and the following is returned

`~/en/search/?selected_facets=ranks_exact%3AGeneral+de+Brigada&selected_facets=countries_exact%3AMexico&q=&entity_type=Violation&start_date=&end_date=`

<img width="875" alt="image" src="https://user-images.githubusercontent.com/2115933/107055536-4cd44800-67c9-11eb-92a0-915f3af1a6d6.png">

The `ranks_exact` facet is passed into the query on incidents, which fries it; the facets specific to `incidents` are not rendered available to the user. The behaviour we'd expect when switching between entities is that only facets that are general are passed into the query, and that entity specific facets are removed from the query. So in this case, this is what we expect:

`~/en/search/?entity_type=Violation&selected_facets=countries_exact%3AMexico`

**Comment by hancush** [comment]
Addressed in 5943a4a54366d5e27be0141ecb46111132b65e44, deployed to the dev site. Working as expected @tlongers?

**Comment by tlongers** [comment]
Great, thanks; that fixes it. Closing!
