### ISSUE TITLE
Ability to merge entities

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#72]
We'll need the ability to merge Organizations, People and the odd Event. For now, the entry point for discovering what needs to be merged and merging them will be the search interface. @tonysecurityforcemonitor gave some concrete examples of use cases in #27 which I'm putting over here just to make it a little cleaner: 

Here are the steps in my mind (though of course they are based on merging via a spreadsheet). Also - I realized that I didn't mention in my orginal note that very, very occassionaly we will discover events that should be merged.

1) I would expect would there would be some functionality to "pull out" the relevant records for merging.
2) I'd want there to be some way that the researcher could make decisions and the relevant sources would "move" along with those decisions. The big decision is around the name (since there can only be one, versus aliases where there can be many names)

Example:
Researcher Tony finds an article from Vanguard newspaper from June 2010 with: "Colonel John Smith is commander of 1 battalion" - the researcher enters this information into the CMS.
Researcher Sarah finds an article from Daily Trust newspaper from July 2010 with: "Colonel Jonny Smith is commander of 1 battalion" - the researcher enters this information into the CMS as a separate person.
Researcher Tom finds an article from The Nation newspaper from August 2010 with: "Colonel John Alfred Smith is retiring from his post as commander of 1 battalion. Jonny Smith has served with the army over 20 years" - the researcher enters this information into the CMS as a separate person.

3) The researcher decides John Alfred Smith is the name of the person, every other name (John Smith and Jonny Smith) should be relegated to the Alias field, and ideally the sources (Daily Trust, The Nation AND Vanguard - which calls the person both John Alfred Smith and Jonny Smith) would move seamlessly over. All the sources agree on the Organization, Role and Rank - so ideally they could be merged together in the relevant fields. Finally, the date of first citation should be from the Vanguard newspaper source and entry and the date of last citation should be from The Nation entry. The entry for date of first citation that was tied to the entry from the Daily Trust source doesn't actually have anywhere "to go" and should "disappear" somehow.

A more complicated - and common - version of this is when we discover that a Captain John Smith of the 1 Regiment, Colonel Jonny Smith of the 2 Battalion and Brigadier General John Alfred Smith of the 3 Brigade are all the same person. Then the sources attached to the Organization, Role, Title, Rank, First and Last Citations could all be very different, potentially with some, but not complete overlap (ie 5 sources agree that Smith was commander of all of those units, but only 3 give information on Rank for his time with the Brigade, 2 give information for Rank with Brigade and only 1 gives information on Rank for his time with the Regiment)

4) In terms of functionality I think its important for the researcher to be able to "move" fields around without having to re-enter data.

**Comment by evz** [comment]
@tonysecurityforcemonitor One question that springs to mind right away is how to source the merge itself. The model that we have in place for "sources" is based upon a source being published somewhere on the internet. The "source" for this would seem to be whichever researcher decides to perform the merge. I just wonder how we'll record and convey that to consumers of the data.

**Comment by tonysecurityforcemonitor** [comment]
@evz I'm glad you pointed out the source model is based on something being published somewhere on the internet --- we definitely include non-digital sources as well, which wouldn't really change the model expect that obviously there would be no urls to enter.

> The "source" for this would seem to be whichever researcher decides to perform the merge. I just wonder how we'll record and convey that to consumers of the data.

Can you elaborate a bit more on this point?

**Comment by evz** [comment]
So, the way you described the use case, it sounds like the decision to merge two or more entities is based on a judgment call made by a researcher. This means that the "source" is the researcher's brain, not an article or book or whatever. Or is that not the case? Would there need to be a source that the researcher cites? Either way, it seems like this is going to be tricky to describe since, instead of adding or modifying data as it exists, we're talking about perhaps changing a name to an alias, or maybe adding a new entity that supersedes existing entities which I guess would be easy enough source but what happens to the ones that were superseded?

**Comment by tonysecurityforcemonitor** [comment]
@evz - Yes there often won't be a source that sparks a merge by directly saying that Colonel Bobby Smith and Colonel Robert Smith are the same person (there sometimes could be a source that does say this, but not always).

> Either way, it seems like this is going to be tricky to describe since, instead of adding or modifying data as it exists, we're talking about perhaps changing a name to an alias, or maybe adding a new entity that supersedes existing entities which I guess would be easy enough source but what happens to the ones that were superseded?

My assumption with a merge is that if we are merging Colonel Bobby Smith and Colonel Robert Smith - and we are deciding that Colonel Robert Smith is going to be the "canonical" entry then everything that was attached to Colonel Bobby Smith would now be attached to Colonel Robert Smith and the Colonel Bobby Smith entry would no longer exist as it has been updated through merging as it were. Having someway to track what records had been merged (so they can be unmerged if there was a mistake) would be very helpful.
