### ISSUE TITLE
Adjust Person posting import to accommodate new format

### ISSUE THREAD

**Issue by hancush** [security-force-monitor/sfm-cms#720]
Person postings will now reference a unit by ID rather than name. Update the field and import logic to accommodate this.

![Screen Shot 2021-02-12 at 9.16.10 AM.png](https://images.zenhubusercontent.com/5b0dc8d3348b7966b4340de0/901d52d9-b7d5-4121-8e86-06e183ea607c)

**Comment by hancush** [comment]
Hello again, @tlongers! Similarly to https://github.com/security-force-monitor/sfm-cms/issues/704#issuecomment-778258447, the persons sheet in our test cases needs an update to reflect this change in data format. Can you provide that at your earliest convenience?

**Comment by hancush** [comment]
Reformatted person test cases here: https://github.com/security-force-monitor/sfm-cms/blob/852ab66bd5d9f92c104b64194f603e15bbb99695/tests/fixtures/importer/persons.csv

**Comment by tlongers** [comment]
I updated the  `persons.csv` to feed into the import test cases as part of a bul update of all of them. For info, though `persons.csv` was untouched e811e9f2e0e0c2fd8dcad424fbe737930ce80357 is the most recent update to the test cases (done to add `locations.geojson`). Ping me if any of this breaks!
