### ISSUE TITLE
[solr-refactor][staging] incident search result  - remove time elements from date values in result tables

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#721]
Replicate at:

`~en/search/?selected_facets=countries_exact%3AMexico&q=&entity_type=Violation&start_date=&end_date=`

This is what we get:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/2115933/107803822-08155780-6d5b-11eb-80c6-e55023623e7b.png">

We shouldn't have `midnight` appended to each date value in this view.

**Comment by hancush** [comment]
Staged: https://back.securityforcemonitor.org/en/search/?q=&entity_type=Violation&selected_facets=

**Comment by tlongers** [comment]
Thanks. For some reason, the date format used in the incidents search results table is in this format `January 20, 2019` but in the persons and units search results tables it is `20 January 2019`. Can you bring the incidents search into harmony with units and persons?

**Comment by tlongers** [comment]
This is fixed; thanks. Closing.
