### ISSUE TITLE
Sources are not necessarily on the Internet

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#73]
As @tonysecurityforcemonitor mentioned in #72, sources can be non-digital.

**Comment by evz** [comment]
If a source is not on the internet, what attributes do we want to capture about it?

**Comment by tonysecurityforcemonitor** [comment]
@evz I think we can utilize the current fields we have - I'd just instruct the data entry to be done a bit different for non-Internet sources.  @tlongers It would be good to get your thoughts on this before we make a hard decision however.

As an example I'll use the most complex non-Internet source I can think of which is a couple of pages from a chapter in a larger edited volume. Currently we have it cited like this:

Policing Nigeria in the 21st Century. Edited by Solomon E. Arase and Iheanyi P.O. Iwuofor. "Police Mobile Force: How Far, How Well?" John B. Abang, CSP. Spectrum Books Limited. 2007. Page 345-346

Using the current source entry setup I'd enter the following:

Source Title: "Police Mobile Force: How Far, How Well?" John B. Abang, CSP. Page 345-346
Date Published: 2007
Publication: Policing Nigeria in the 21st Century. Edited by Solomon E. Arase and Iheanyi P.O. Iwuofor.
Publication Country: Nigeria
Source URL: (blank)
Archive URL: (blank)

With any source, Internet or non-Internet - we always try to include the page number!

**Comment by evz** [comment]
OK. It sounds like the solution here, from the backend perspective anyways, is to just make both the URL fields optional.

**Comment by evz** [comment]
Actually, in light of me getting #21 to work, I'll just remove the archive URL field altogether
