### ISSUE TITLE
Search results pagination - increase default number of search results to 25

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#732]
Connects #674.

The default number of search results returned for each entity is currently 5. Minimising the number of results in this way made sense when we showed multiple entities on a single search page. As we now just show a set of search results for a single entity, we should increase the number of results shown. I think 25 should work well, with the options to increase the increments to 50 and 100.

**Comment by hancush** [comment]
This is already done in the refactor! 🎊 It's just not deployed to staging while we focus on the import changes.

**Comment by tlongers** [comment]
Great. Closing.
