### ISSUE TITLE
Search results - expand "General filters" panel and "Country" facet by default to give users a better view

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#733]
Connects #674.

The general filters panel in the left hand sidebar is pretty useful, but currently collapsed by default, so it looks like this:

![image](https://user-images.githubusercontent.com/2115933/108830196-00f31280-75c1-11eb-8962-31fbc21bccbe.png)

By default, it should be expanded, and the `Country` facet should also be expanded. In this way the user can see that there are two things they can quickly do to refine the results. This is a more useful starting point I think: 

![image](https://user-images.githubusercontent.com/2115933/108830361-2d0e9380-75c1-11eb-979c-98a39088dd2a.png)

This idea could be developed further to give us some nice usability improvements. I think it would be good to also expand the entity-specific facets. However, unless we truncate the number of options offered to the user initially it could make the view more confusing. What's the work involved to just show the top 5 facets (along with their counts), with an option to show more?

**Comment by hancush** [comment]
Not much work at all! I took a shot at it in some downtime:

![expand_facets](https://user-images.githubusercontent.com/12176173/109065785-b4d3cb00-76b1-11eb-9a4f-e8b731811e92.gif)

All facets default to expanded, with the top 5 values shown and, if there are more than 5 values, an option to see more. I also expand the full value list if there's an active filter on that facet.

We can workshop this more when we pick search back up!

**Comment by tlongers** [comment]
This looks great; thanks for taking a swing at it. We'll test it out when it's up on staging.

**Comment by tlongers** [comment]
This is successfully implemented now. @hancush anything further on it?

**Comment by hancush** [comment]
If you're satisfied, then nope, it's good to go! Great suggestion, @tlongers – I think this represents a nice improvement to the search UI.
