### ISSUE TITLE
Person records - incorrect labelling in left side panel

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#734]
Change "memberships" to "postings" in Person record views:

![image](https://user-images.githubusercontent.com/2115933/108831837-96db6d00-75c2-11eb-80e5-a48d37937857.png)

**Comment by hancush** [comment]
Fixes this in https://github.com/security-force-monitor/sfm-cms/commit/a6faa681bf8066bb91907e4e87f256e02fe7fd52. Look ok, @tlongers?

**Comment by tlongers** [comment]
Super.
