### ISSUE TITLE
[staging] Unit records - "none" values in "site" facet; but site data is provided to importer

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#735]
[Connects #674, #704]

The `site` facet for units should contain the values stored in the `location:admin_level_4` field for the relevant locations. The `site` facet is currently reporting a large number of `none` values, which it should not as all location data provided should have a value in `location:admin_level_4`.

For example, run an empty query on staging (which at the time of writing has only Nigeria data in it) and then open up the site facet:

`~/en/search/?q=&entity_type=Organization&start_date=&end_date=`

Let's select the `none` value to see what we get:

`~en/search/?q=&end_date=&start_date=&entity_type=Organization&selected_facets=organization_adminlevel1_ss_fct_exact%3ANone`

![image](https://user-images.githubusercontent.com/2115933/108833768-339f0a00-75c5-11eb-8a24-734e39b65c43.png)

The search results are showing records that do have site values e.g.

![image](https://user-images.githubusercontent.com/2115933/108833787-3b5eae80-75c5-11eb-860d-0b5ec324c21a.png)

When we visit the full record (`~en/organization/view/343638c0-1a67-40f6-83a6-a7442213c460/`), the `site` is represented by a polygon, which is permitted by the data model and happens in ~10-20% of cases:

![image](https://user-images.githubusercontent.com/2115933/108833820-43b6e980-75c5-11eb-8ebf-f0db2e6f3645.png)

In this case, the polygon is [Ogun](https://www.openstreetmap.org/relation/3718463), which is tagged as an administrative boundary level 4 entity. 

In the import data Ogun has the relevant metatadata that declares this _and_ includes itself as its own 

location:status:admin | location:comments:admin | location:id:admin | location:humane_id:admin | location:name | location:id | location:geo_type | location:origin | location:source | location:country | location:admin_level | location:admin_level_10 | location:admin_level_9 | location:admin_level_8 | location:admin_level_7 | location:admin_level_6 | location:admin_level_5 | location:admin_level_4 | location:admin_level_3 | location:admin_level_2 | location:notes:admin | location:first_check_time | location:last_check_time | location:error | location:as_of_date
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   | 511896a5-260a-4947-9736-292dd3b18a87 | Ogun (osm, poly) 511896a5-260a-4947-9736-292dd3b18a87 | Ogun | 3718463 | poly | osm |   |   | 4 |   |   |   |   |   |   | Ogun (osm, poly) 511896a5-260a-4947-9736-292dd3b18a87 |   | Nigeria (osm, poly) 5e3623b0-7894-43b3-a62b-c50cfacf0b5d |   | 2021-02-14T19:39:01Z | 2021-02-14T19:39:46Z |   |  

The WWIC importer has all the data it needs to populate the site facet.

What might be the issue?

- Because the `site` is defined by a polygon not a point, the importer has not extracted the relevant AL4 data?
- Because the location is self-referential, the importer has not extracted the relevant the AL4 data?
- Something else?

**Comment by hancush** [comment]
@tlongers The old version of the search (and indexing) is currently deployed to the staging site. Can we revisit this issue once we return to refining the search revision?

**Comment by tlongers** [comment]
Yes, of course.

**Comment by hancush** [comment]
We populated this facet from our convenience `adminlevel1` attribute (equal to admin level 6) on related sites. 

https://github.com/security-force-monitor/sfm-cms/blob/34837fb372a2bf8aa3bc923f12f9a43ca2598777/search/management/commands/make_search_index.py#L143-L161

Two obvious issues here:

- If we're after admin level 4, then we should be using `adminlevel2`.
- We don't set the corresponding convenience attribute if the location is itself admin level 6 or 4. This, I think, is the source of the None values.

I updated how we populate this facet in https://github.com/security-force-monitor/sfm-cms/pull/746/commits/5ca68ab531941b3a26edbfda36ac2c9631a845c9 to use the admin level 4 metadata tag from associated sites, instead. 

The index is rebuilding now. Is this more in line with what you expect? https://back.securityforcemonitor.org/en/search/?start_date=&selected_facets=countries_exact:Nigeria&q=&entity_type=Organization&end_date=&selected_facets=adminlevel1s_exact%3AOgun

(If so, I should also update the name of the facet, which became a misnomer with this change!)

**Comment by tlongers** [comment]
So, to confirm:
 - the sites facet takes the AL4 value from the corresponding location record
 - where the location is itself an AL4, this will be put into the sites facet

**Comment by hancush** [comment]
@tlongers Yes, that's correct.

**Comment by tlongers** [comment]
Great, thanks. As you, say perhaps renaming the facet with a more intuitive name is the final steps. Then I think this can be closed.

**Comment by hancush** [comment]
Done!
