### ISSUE TITLE
Figure out data import

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#74]
@tonysecurityforcemonitor and the gang have a bunch of data that they have already put into Google Spreadsheets. Let's figure out how to front load this system with what they have in there already.

**Comment by evz** [comment]
It occurs to me that @jpmckinney might have already done some work on this. Is that the case?

**Comment by tonysecurityforcemonitor** [comment]
I think the last import from @jpmckinney was a bit back and into the temporary database that he setup to test the front-end UI... right?

**Comment by evz** [comment]
@tonysecurityforcemonitor I put in a bit of time working on this today and wanted to confirm a couple things about how these spreadsheets are structured.

* I'm noticing that there are several things that are not sourced. Because of the way the data models are setup, we're assuming that everything is sourced. How should I handle those attributes?
* It seems like the "ID" column is the person who entered the info. I can probably programmatically create user accounts for these folks, I'd just need to either fake their email addresses or get real ones for them. Also, does the date next to their name refer to when the entry was made? Should I be capturing that?
* There are quite a few date fields in the spreadsheet which we no longer have in the CMS. How should I be handling those?

I'm sure I'll have some more questions as I get farther along, just wanted to get the conversation started.

**Comment by jpmckinney** [comment]
@evz: Like @tonysecurityforcemonitor wrote, the data was imported into a temporary database, with this code: https://github.com/security-force-monitor/sfm-proxy/blob/master/tasks/import.rake

1. Which things are not sourced? (one example would be fine)
2. I don't think my importer used the ID column. I forget what the plan was for it.
3. Which date fields are no longer in the CMS?

**Comment by tonysecurityforcemonitor** [comment]
> I don't think my importer used the ID column. I forget what the plan was for it.

@jpmckinney I believe the ID column was going to give an unique ID # to every entry

**Comment by jpmckinney** [comment]
Yeah, that's what I remember. But as far as the importer goes, we didn't need to fill that column in the spreadsheet.

**Comment by evz** [comment]
@jpmckinney By "not sourced" I mean in the spreadsheet they don't have a source listed. That was more a question for @tonysecurityforcemonitor. 

The date fields that we removed from the CMS are founding date for an Organization and death date for a Person.

**Comment by tonysecurityforcemonitor** [comment]
@evz The not sourced entries need a source! Many of the parent relationship entries were left blank because the research wasn't done on those yet. But now the research is in so I can update. Some other blank entries appear to be errors as well. Everything should have a source.

**Comment by evz** [comment]
@tonysecurityforcemonitor So, I guess, if an attribute doesn't have a source, should I skip it for the time being? As a cast off from importing these spreadsheets, I can also give you something that tells you what is not sourced, if that is useful.

**Comment by evz** [comment]
Also, how much general cleanup can I assume? I'm noticing some things that kinda deviate from the way that the data entry guide suggests (so for instance sources aren't always semi-colon separated).

**Comment by tonysecurityforcemonitor** [comment]
@evz Hmmmm - I'm trying to think what is the easiest for you/makes the most sense. In the past for testing development I've taken clean subsets of the data --- which we could do if that is easier. However, having a list of errors (including none sourced entries) would be hugely helpful - and it seems the only way we could get that is through the import process.

Its hard for me to guesstimate in terms of cleanup - there shouldn't be that many records that need to be merged (which I see as the biggest/most time consuming clean up) but it's harder for me to get a sense of the smaller issues like sources that aren't semi-colon separated (they all should be!) by looking at the spreadsheet. There were quite a few errors in the data last time James attempted an import, which I spent lot of time cleaning, so hopefully we aren't that far off. I'm also planning to spend nights/weekends to get everything rapidly in shape.

**Comment by tonysecurityforcemonitor** [comment]
> The date fields that we removed from the CMS are founding date for an Organization and death date for a Person.

@evz yes those fields can be skipped -- sorry I haven't had a chance to clean those out from the spreadsheet.

**Comment by tonysecurityforcemonitor** [comment]
> The date fields that we removed from the CMS are founding date for an Organization and death date for a Person.

@evz - Are you referencing column AN - Is this the founding date? (Y/N) - that is tied to the Site, not the organization. Column AR - Is this the dissolution date? (Y/N) - is old and can be ignored, as Column AS - Assume Site (City or smallest administrative unit GeoName and/or AMIN1) to Current Date? (Y/N) - has replaced it.

I don't see any columns referencing a death date for a Person - column AD - End date? (Y/N) - is just tied to the person's membership with the organization.

**Comment by evz** [comment]
@tonysecurityforcemonitor That was mainly a response to @jpmckinney when he asked which date fields we removed from the CMS. But that's useful info!

**Comment by evz** [comment]
@tonysecurityforcemonitor I have a pretty good start on a script to import data from the Google Spreadsheet. The major challenge that I came across was figuring out how to reliably parse the sources. I've come up with a way that is somewhat brittle (on purpose mainly because I don't want to potentially put jibberish into the database) and, if it can't parse out a source for a field, that field just gets skipped and logged out so we can maybe go back and fix them later. 

Other than the source fields, it seems to be pretty simple and I should be able to get it wrapped up pretty soon.

**Comment by tonysecurityforcemonitor** [comment]
@evz That's great - and I agree with you that its better for it to be brittle so that we can correct entries as needed.

**Comment by evz** [comment]
@tonysecurityforcemonitor Data importer is going pretty well, I should get it finished up today. One question I have is related to the events worksheet. It looks like there is no "confidence" assigned to anything in there. Should I just default it to "Low"?

**Comment by tonysecurityforcemonitor** [comment]
> Data importer is going pretty well, I should get it finished up today. One question I have is related to the events worksheet. It looks like there is no "confidence" assigned to anything in there. Should I just default it to "Low"?

@evz - there aren't any confidence scores for the data in Events

**Comment by evz** [comment]
So, over the past few days, I've been building out a Django management command to import data from the spreadsheets that @tonysecurityforcemonitor and his team have been using to track this information thus far. After my initial attempts, he had a few observations which I'll respond to here: 

### Assumptions/Data model

> "No Area Geoname info for" errors - There were 341 "No Area Geoname info for" errors --- and when I looked at the corresponding row the cells associated with Area were blank. Is the CMS assuming that every organization has an area, making this a required field? Not all organizations will have an associated area.

This is not a required field for organizations. I guess that is more of an informational message than an error (maybe I should add a column in the output indicating that). The upshot is that no area is created for the organization but the organization itself is still created.

> "No confidence for Alias" errors - When I looked at the corresponding rows the cells associated with Alias were blank. Is the CMS assuming that all organizations will have an alias? This error was a little unclear because there were many rows with no Alias that didn't return an error - like rows 131, 134

This is an issue with the importer not checking if the field has something in it before checking if there is a confidence associated with the value. I'll fix that now.

> "No confidence for EndDate" errors - This one was a little unclear to me because I wasn't sure what EndDate it was referring to - however, when I looked at the corresponding rows the cells associated with an end date for parent relationship, site or Area they were blank. Is the CMS assuming there will always be an EndDate or a date of last citation for these fields? Organizations may not have a date of last citation for parent relationship, site or Area

This, believe it or not, is the same as the issue above. Under the hood, the field that we are saving "last cited" dates into is called "EndDate" so, yeah your assumption is correct. 

### Unable to parse published on date from source string

> This error centered largely around sources with either no date of publication

> The big question I have is this only an import issue or is the CMS assuming at that all sources have a complete date of publication (day, month, year)? Because there will be sources in the future that either do not have a date of publication or their date of publication is  

> There were a number of sources where the full date was in the citation but it could be read --- not sure how to address that....

First, a note about the, admittedly fragile, method that I landed on for parsing out the sources. It kinda hinges on finding a publication date some place in the string that represents a source. From there, I know that the stuff before the publication date is related to the title of the source and the title of the publication and the stuff after that are links. If there is no identifiable publication date, the whole thing kinda collapses and I default to failing on that source. I now realize that this method really only works with internet based resources and basically any book is going to fail since the "date" is a year. This also fails when there is some kind of date or date-like thing in the source title. Maybe we can put our heads together and come up with a better way of doing this or at least have it perform a bit better. 

### Unable to parse source title and publication title from source string

This is somehow related to the stuff above. I'm looking into it.

**Comment by evz** [comment]
@tonysecurityforcemonitor 

> @evz - there aren't any confidence scores for the data in Events

Does this mean that confidence is just not required for those or that it just wasn't entered?

**Comment by tonysecurityforcemonitor** [comment]
> Does this mean that confidence is just not required for those or that it just wasn't entered?

@evz It means that confidence is not required... meaning that it simply doesn't "exist" for Event data

**Comment by evz** [comment]
@tonysecurityforcemonitor OK, I've made the necessary modifications to accommodate making a confidence measure optional.

**Comment by evz** [comment]
@tonysecurityforcemonitor I made a few updates to the way that I am getting the source information and have generated a few new files showing where the import is failing. Would you like me to send these along to you? I think the only major differences are that I was able to pick up some more of the sources that I was unable to parse earlier and that I stopped logging things that didn't really represent a "failure" (in the sense that it didn't create something).
