### ISSUE TITLE
[staging] incident record - lcoation popover not displaying location label. Bug or feature?

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#740]
Not sure if this is by design or accident but clicking on the pin inside a location map doesn't activiate a popover for the site label: `~/en/violation/view/e914ac41-4c84-4ebf-a205-b360f1a12cee/`

![image](https://user-images.githubusercontent.com/2115933/108843210-4b30bf80-75d2-11eb-9ad1-b30759b0bddb.png)

This _may_ be down to slightly different conventions around how we have expressed locations for incidents, preferring instead to use a description for a single location (formed by concatenating values) rather than a table that lists site(s).

**Comment by hancush** [comment]
I'm not seeing this on the live site, either, @tlongers: https://whowasincommand.com/en/violation/view/e914ac41-4c84-4ebf-a205-b360f1a12cee/

I could add a popup fairly easily if you like?

**Comment by tlongers** [comment]
Yeah, I think it's by design.

@tonysecurityforcemonitor What do you see in this issue?

**Comment by tonysecurityforcemonitor** [comment]
Design-wise that makes sense to me, since incident = single location, whereas we have map popovers for sites and areas of operations which could have multiple locations on the map at once...

I think we're ok to leave as is for now

**Comment by tlongers** [comment]
Closing. We wil revisit the incident map design at some point however.
