### ISSUE TITLE
[staging] sites and areas of operation map not displaying where geom is OSM type "way"

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#742]
[links #704]

`~/en/organization/view/952f9889-b03c-4eb3-8173-2a4f5fb50fa5/`

![image](https://user-images.githubusercontent.com/2115933/108845815-c8a9ff00-75d5-11eb-952e-c28f9496eaa6.png)

The unusual thing about this record is that the location used for the site is a `way` rather than a `relation` or a `node`. A `way` can resolve to a closed polygon or a line, so we have classed it geotype as `line` in our location model. The specific location in the import data is: `Trans-Ekulu (osm, line) 3111303b-1a02-4d5e-b190-33d0e2cdfa63`. It's actually the only `line` in this particular import dataset; others have more.

**Comment by hancush** [comment]
@tlongers Just pushed a fix for this: https://back.securityforcemonitor.org/en/organization/view/952f9889-b03c-4eb3-8173-2a4f5fb50fa5/

I removed shading from ways, since they represent lines rather than polygons (though they can be polygons). What do you think about that decision?

**Comment by tlongers** [comment]
Can the plotting library tell if the `way` is a closed area or not?

**Comment by hancush** [comment]
I would guess so! Would be a good thing to verify when we bring in locations that are lines rather than closed areas. Are you saying leave the shading if the way is a closed area?

**Comment by tlongers** [comment]
>  Are you saying leave the shading if the way is a closed area?

Yes, though on reflection I think it's going in the right direction to remove the shading; so, good call. This is a good fix!

The wider issue is that the concepts of `site` and `area of operations` become a little blurred when the geospatial information used to represent them can be of any type. From a user perspective, I would ask what the difference is! I think it's a another information design matter to add to the pile. 

Closing here and opening this more general issue at #744.
