### ISSUE TITLE
Unit profile - add country to memberships table

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#745]
Complex multi-country operations can have units from many different countries. It is not currently possible to see this in the "member units" block at the current time e.g. `United Nations Mission in Liberia`

https://whowasincommand.com/en/organization/view/cd4cfaea-b809-434f-a786-929954d69e3d/

![image](https://user-images.githubusercontent.com/2115933/109842810-5cb53f80-7c42-11eb-8a06-ff9a562e3503.png)

To resolve this, add a unit's `unit:country` value into the table, in the second column. Default sort should be on `unit:country` followed by `unit:related_unit_first_cited_date`, `unit:related_unit_last_cited_date` and then `unit:name`.

**Comment by hancush** [comment]
Ahoy, @tlongers! I've deployed the new column to the staging site: https://back.securityforcemonitor.org/en/organization/view/cd4cfaea-b809-434f-a786-929954d69e3d/

Can you say a bit more about sorting? 

AFAICT, we don't currently support sorting on the client side, nor do we sort memberships on the back end. I think the list is sufficiently short that a sort on the front end wouldn't be a huge help for information discovery, but I welcome your expertise / counterpoints there! On the other hand, it makes sense to me to apply a sort on the back end so the table supports the most common pattern of finding what users are looking for. What do you think that is? 

(If there are significant user groups with different patterns of discovery, e.g., some are looking for a particular unit while others care more about citation date, that could be an argument for client side sorting.)

**Comment by tlongers** [comment]
Super, thanks.  Apologies for not being clearer; I didn't intend to add any interactivity to that table. You are correct here:

>On the other hand, it makes sense to me to apply a sort on the back end so the table supports the most common pattern of finding what users are looking for. What do you think that is?

There's no sense adding client-side interactivity to that table.  I think enabling users to scan the table and quickly eyeball a block of units that come from specific countries is the most useful arrangement here. The way you've implemented it achieves that nicely within the current style/layout options. This record shows it better, as there are more countries:

`~/en/organization/view/fffa0ffc-e7e6-4d82-9173-d91df2edaf5d/#org-members`

Does that help?

**Comment by tonysecurityforcemonitor** [comment]
The table is fantastic with the addition of the countries :)

**Comment by hancush** [comment]
Thanks for the clarification, @tlongers, yes, that's super helpful! Though the example record has blocks of countries, we aren't explicitly sorting the list on the back end, and I'd like to add that for consistency and ease of use. 

Looking at your proposed sort –

>  Default sort should be on unit:country followed by unit:related_unit_first_cited_date, unit:related_unit_last_cited_date and then unit:name.

– if blocks of units by country is the primary browsing mode, what do you think about omitting citation date from the sort, so country blocks are in alphabetical order and memberships are organized alphanumerically within their country block?

**Comment by tlongers** [comment]
>so country blocks are in alphabetical order and memberships are organized alphanumerically within their country block 

Perfect, thanks.

**Comment by hancush** [comment]
Sort has been staged: https://back.securityforcemonitor.org/en/organization/view/fffa0ffc-e7e6-4d82-9173-d91df2edaf5d/#org-members

**Comment by tlongers** [comment]
Confirmed; great work. Thanks also for updating the corresponding view that units show which other units they are members of. Shall we close this?

**Comment by hancush** [comment]
Sure thing!
