### ISSUE TITLE
[solr-refactor] Unit profile - selected_facets=organization_classification_ss_fct_exact is serving errors

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#747]
Links in unit profile headers are not pointing to the right place:

`~en/organization/view/6ba5daca-dc48-44cc-a235-13894a480b94/`

<img width="730" alt="image" src="https://user-images.githubusercontent.com/2115933/109884024-360ffc80-7c74-11eb-8f07-ba2c8fea13c0.png">

"Military" links to the url below, which returns a server error:

`~/en/search/?entity_type=Organization&selected_facets=organization_classification_ss_fct_exact:Military`

The correct url should be:

`~en/search/?entity_type=Organization&selected_facets=classifications_exact%3AMilitary`

Looks like the facet got renamed at some point?

For extra points, when selecting any `unit:classification` facet from within the unit header area, parse the unit's `unit:country` value into the facet too. That way, the user stays in country context.

**Comment by tlongers** [comment]
Connects #711

**Comment by hancush** [comment]
Staged! https://back.securityforcemonitor.org/en/organization/view/6ba5daca-dc48-44cc-a235-13894a480b94/

Where can I collect my extra credit? 😋

**Comment by tlongers** [comment]
Fix confirmed. Closing!

>Where can I collect my extra credit? 😋

Edible sugar-based prize and accompanying motivational beverage will arrive with you by 09:00.
