### ISSUE TITLE
unit records - parent unit charts are blank

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#748]
URL: `~en/organization/view/1b0c9127-e9ee-4fa6-9b34-fdc8802ee6d8/`

The  parent unit chart is present but blank:

<img width="897" alt="image" src="https://user-images.githubusercontent.com/2115933/109884557-17f6cc00-7c75-11eb-8140-a201278318c6.png">

Could be related to #733 ?

**Comment by tlongers** [comment]
Similarly, the "Chain of Command" chart is being hidden on person records e.g. `~/en/person/view/b7e2e750-6f76-46c2-95c5-5e09f058491b/` On load, it briefly appears and then collapses!

**Comment by hancush** [comment]
First issue: I neglected to run the command to populate the org and command charts into the search index. Did that and the org charts seem to be showing up. 

Second issue: The logic to hide / show the command chart on person pages has a bug. Working on addressing on that now.

**Comment by hancush** [comment]
Fix for the second JavaScript bug now staged: https://back.securityforcemonitor.org/en/person/view/b7e2e750-6f76-46c2-95c5-5e09f058491b/#chain-of-command

Things looking better on your end, @tlongers?

**Comment by tlongers** [comment]
>First issue: I neglected to run the command to populate the org and command charts into the search index. Did that and the org charts seem to be showing up on unit pages.

This fixes the issue on some pages, but not on others. So here is a record where it's fixed:

https://back.securityforcemonitor.org/en/organization/view/ecf3f5d4-78b2-4437-9498-6682a2cc011c/#parent-units

And here's some where it's not:

https://back.securityforcemonitor.org/en/organization/view/2e5a608a-1868-4fad-a4be-718d1a5a694d/
https://back.securityforcemonitor.org/en/organization/view/4ada053f-b39d-4324-bf93-9d8ba85cd247/
https://back.securityforcemonitor.org/en/organization/view/184dcc32-12e5-44aa-accb-09aede60a9d8/

> Second issue: The logic to hide / show the command chart on person pages has a bug. Working on addressing on that now.

Yes, that fixes it. Thanks.

**Comment by hancush** [comment]
My bad, @tlongers, I wasn't handling something correctly. Look ok now?

**Comment by tlongers** [comment]
Yep! All good; thanks. Closing.
