### ISSUE TITLE
Fix mobile usability violations

### ISSUE THREAD

**Issue by hancush** [security-force-monitor/sfm-cms#759]
Google Search Console notified us of a few issues on mobile:

- Content wider than screen
- Text too small to read
- Clickable elements too close together

These specifically affect one page: https://whowasincommand.com/es/violation/view/1609f6d5-f972-4011-aa3c-3bd3d009253b/

I think this is happening because the violation type is super long and the tag does not wrap.

![image](https://user-images.githubusercontent.com/12176173/120332694-9b47ae00-c2b4-11eb-8065-58f8a8318e8a.png)

We should either wrap it or truncate it to see if this resolves the issue.

**Comment by tlongers** [comment]
Yeah, that's a useful catch from the Search Console. I'd say wrap it.

**Comment by hancush** [comment]
Roger that, @tlongers!
