### ISSUE TITLE
Where multiple access points to a single source are used on an entity record, deduplicate the source table

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#760]
At least for now (see discussion in #357) we are not going to show source data to the granuality of _access points_ in the "sources" content area of `persons` and `units` records. 

However, where a source is referenced more than once within a record, the source listing should be deduplicated to show it only once. I caught this issue [here](https://whowasincommand.com/en/organization/view/fffa0ffc-e7e6-4d82-9173-d91df2edaf5d/#sources), where there are three rows for the same UN source:

![image](https://user-images.githubusercontent.com/2115933/120790557-06021f00-c52b-11eb-822d-9bc99f095891.png)

**Comment by hancush** [comment]
Great catch, @tlongers. I staged a patch for this on the org pages, e.g., https://back.securityforcemonitor.org/en/organization/view/fffa0ffc-e7e6-4d82-9173-d91df2edaf5d/#sources

Look ok to you? If so, I can replicate for the remaining entities on Monday!

**Comment by tlongers** [comment]
That's a fix! Thanks. 

I'm not sure if this should be addressed in a different PR but I noticed two other things about the sources table. I've reported in #763 and #764.

**Comment by hancush** [comment]
Hey, hey, @tlongers – I've pushed a fix for this issue and #764 to the staging site. Would you mind checking out a few pages of each entity type to confirm everything looks above board? Will push to prod after your confirmation. Taking a look at #763 separately, now.

**Comment by tlongers** [comment]
#764 looks great. I've responded on #763 - we'll address that problem in the next import round. 

Strikes me we should also add some short descriptive text to the sources section: 

"List of all sources used to evidence the data in this record. Click the "+" symbol next to every data point in the record to see the sources used for that data point."

**Comment by hancush** [comment]
Help text deployed to staging. Look ok?

![Screen Shot 2021-06-11 at 8 38 35 AM](https://user-images.githubusercontent.com/12176173/121695180-6e538200-ca90-11eb-9fdc-54b895683e73.png)

**Comment by tlongers** [comment]
Great; thanks.

**Comment by hancush** [comment]
Deployed!
