### ISSUE TITLE
Django date extensions seems unmaintained

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#78]
The last commit on this project is over a year old: https://github.com/dracos/django-date-extensions/commits/master and it's relying on a convention in the main Django framework that has been deprecated in the most recent version. Let's either fork it and update it or find an alternative so we don't get stuck on an old version of Django.

**Comment by tlongers** [comment]
It's maintained by @dracos from mySociety (wave!) -  any plans for it friend?

**Comment by evz** [comment]
Ha! I knew that username sounded familiar. We did some work on bringing Your Next Rep to the U.S. recently.

**Comment by dracos** [comment]
Hi :) Happy to accept pull requests if something about it is broken or will become broken. Caught me at a good moment, I'll just add tox and get it set up on Travis so we can see where it's at, it's still running okay in things I'm using it in as far as I can tell, at least.

**Comment by evz** [comment]
I (accidentally) upgraded this project to Django 1.10 and got an error about `SubFieldBase` not being supported anymore. In Django 1.9 you get a deprecation warning about the same thing (and really that's what started all this I just wanted the stupid message to go away!). I'd be happy to submit a PR but I'm not entirely sure how that class is used within django-date-extensions.

**Comment by dracos** [comment]
Okay, it's now running on Travis with tox and it's now passing on 1.10:
    https://travis-ci.org/dracos/django-date-extensions/builds/151314376
If you'd like to test that to check it's working before I do an official new release. I'm not sure if just removing `SubfieldBase` and adding a `from_db_value` is all I have to do, but the tests pass…

**Comment by evz** [comment]
That seems to have done the trick! Thanks!

**Comment by tlongers** [comment]
Thanks loads Matthew @dracos
