### ISSUE TITLE
Roles & Permissions

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#80]
We've touched on this in a few other issues (#53 and #25 to be precise) so here is our opportunity to discuss it in a bit more detail.

The main requirements that I've been able to gather so far are:
- Ability for some kind of admin user to approve the edits / additions made by normal users. 
- Only allow admin users to delete things.
- Only allow admin users to revert changes.

@tlongers @tonysecurityforcemonitor Any other things off the top?

**Comment by tlongers** [comment]
Roles and permissions have been defined in [the wiki](https://github.com/security-force-monitor/sfm-cms/wiki/What-product-is-Security-Force-Monitor-making%3F-(July-2017)#what-do-people-need-to-do-on-the-product) since mid 2017, and augmented in subsequent spec docs (also on the wiki). Closing.
