### ISSUE TITLE
Release Management

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#81]
While the data entry work will be more or less constant, the Monitor would like to be able to release large sets of changes on a schedule (perhaps quarterly?) (as @tlongers mentioned in https://github.com/security-force-monitor/sfm-cms/issues/53#issuecomment-238953579). This might be as simple as setting a flag on each row that tells us when it ought to be released and then making sure that it only gets serialized by the API on that schedule. Anyways, let's talk through it here a bit before trying to implement anything.

**Comment by tlongers** [comment]
Release management is still and issue, but being dealt with through [versioning and publication settings as specified here in the wiki](https://github.com/security-force-monitor/sfm-cms/wiki/Adding-a-data-capture-system-to-WhoWasInCommand#a-simple-reviewing-and-publishing-system). Closing.
