### ISSUE TITLE
Reporting functions

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#82]
The fact that we are collecting data about things sorta hints at the fact that we'll want to actually be able to see what that data looks like at a higher level. Let's think about what kind of reports we might want the CMS to generate and how we'll want the CMS to generate them. We already threw around some ideas for high level queries to display on the home page in #53 but maybe there are others that could be generated on the fly?

**Comment by tonysecurityforcemonitor** [comment]
@evz - This is a really good point to raise... thinking off the top of my head:

Every organization with a particular word or words in the name (ie Battalion, Police Station, etc.) and the geography(ies)
Every organization with certain classification with certain AOO at a point in time, or over a particular time period
All people with membership of a particular organization
All people with membership of a particular organization and children of that organization and people with membership to the children organizations
All people with role of commander with membership of organizations with particular classification (ie all army commanders, all police commanders, etc.) at a point in time, or during a given time period.

@tlongers - others?

**Comment by tlongers** [comment]
Still a relevant issue. Moving to current dev tranche.

**Comment by tlongers** [comment]
Stale; closing.
