### ISSUE TITLE
Dashboard - sorting organizations by fields

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#90]
@evz @tlongers building upon what was discussed in #53 - I can see the potential of being able to sort Organizations and Events by Geoname --- and it would be great to build this out a bit more so that there are multiple different fields we can quickly sort by.

For organizations I see the fields I would want to be able to group/sort by would be:
- OrganizationOrganization:parent_id
- Site:geonames_name
- Site:admin_level_1_geonames_name
- Organization:classification
- OrganizationArea
- OrganizationMembership:organization_id

So the use cases would be - 
- what organizations are tied to what parent?
- what organizations are based in what cities?
- what organizations are based in what admin1?
- What organizations operate in what areas?
- What organizations are part of which Joint Task Forces, Joint Operations or otherwise have some membership? (Another example here, what organizations are part of what peacekeeping missions?)

It would be nice to have some sort of selection process - like perhaps I just want to see organizations and their areas or operation. Or maybe I want to really fine tune it to see only Army organizations based in a certain Geoname and see what memberships they have.

This might actually be more related to #82 ....

**Comment by tonysecurityforcemonitor** [comment]
@evz Though - per the conversation about merging records I can envision use cases around each of those fields where we might decide to merge records together (2 Mech Infantry Battalion and 2 Battalion both share the same AOO for instance or have the same parent).

**Comment by tlongers** [comment]
Relevant to #82 and #53. Also worth discussion with respect to present (Sept 2018) development on  reviewing and publishing system. Keeping it alive for now

**Comment by tlongers** [comment]
Stale; no longer needed.
