### ISSUE TITLE
Merging Entities - Need to see more fields

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#91]
@evz @tlongers

This issue might be related to #90 - the merge function is done via a search - however the fields that are displayed are greatly restricted (Organizations only display Name, Aliases and Classification). The researcher needs to be able to select which fields will be displayed in the search and on which they are basing their merge decision on. It may be two similarly named organizations should be merged when it is discovered they operate in the same area for instance.

**Comment by tonysecurityforcemonitor** [comment]
@evz Dates are also very important when making decisions to merge, especially with people

**Comment by tlongers** [comment]
Merge function not currently (Sept 2018) specified, but keeping this around to discuss.

**Comment by tlongers** [comment]
Merging is no longer handled in any form inside the application. Closing.
