### ISSUE TITLE
Merging Entities - canonical record?

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#92]
@evz 

Currently selecting one entity as the canonical record makes the Name of the non-canonical entity become an Alias (and the Aliases of the non-canonical entity are also Aliases for the new canonical entity). This is all as I would expect.

However, its not clear to me what happens to the other fields (classification, site, AOO, parent orgs, etc.) For many fields, an organization can have multiple sites or a person can have multiple memberships. I'd expect that merging two Organizations with different Sites for instance would mean the new canonical organization would have both Sites - but its not clear if that is the case.

**Comment by evz** [comment]
Right now for people and organizations, the intent is just as you stated, the name of the non-canonical entity becomes an alias of the canonical entity (if it's not already) and everything else (sites, classifications, etc) should be appended together.

**Comment by tonysecurityforcemonitor** [comment]
@evz Ok sounds good!
