### ISSUE TITLE
Issues with setup instructions

### ISSUE THREAD

**Issue by jpmckinney** [security-force-monitor/sfm-cms#96]
* `./manage.py loaddata violation_types`: No fixture named 'violation_types' found.
* `./manage.py loaddata classification_types`: No fixture named 'classification_types' found.
* `./manage.py cities --import=all`: Unknown command: 'cities'
* `./manage.py make_search_index`: Unknown command: 'make_search_index'
* `./manage.py make_geoname_lookup`: Unknown command: 'make_geoname_lookup'

**Comment by jpmckinney** [comment]
^ @evz

**Comment by jpmckinney** [comment]
If I can't import data, then I can't test the API.

Do the importers import points from GeoNames and polygons from GAUL, to be used as values for the geospatial properties of the Area, Violation and Geosite classes?

**Comment by jpmckinney** [comment]
Ah, the GitHub clone URL wasn't updated. Let's see if that fixes everything.

**Comment by evz** [comment]
@jpmckinney Did that work? I'll send you some instructions via email for loading data from the spreadsheets that @tonysecurityforcemonitor and his team have been maintaining.

**Comment by tonysecurityforcemonitor** [comment]
@jpmckinney @evz - Would it help to make a "clean" version of the Nigeria data for API testing? Happy to do so if so.

Also - in terms of shapefiles - should I get the shapefiles from Geonames or does that complicate things?

**Comment by jpmckinney** [comment]
@evz Commands are working now. I'll follow-up with smaller issues.

@tonysecurityforcemonitor I think we're good for the Nigeria data and GeoNames shapefiles.
